### ISSUE TITLE
Fix tolerance in simplify polyline example in testapp

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#100]
In #86 we discovered that using 0.00001 as a tolerance worked best. In the simplify polyline example we are still using large tolerances, need to multiply by 0.00001 in the equation so we always get a better tolerance value.

**Comment by zugaldia** [comment]
@cammace Great finding. I brought the default tolerance to `0.00001` in https://github.com/mapbox/mapbox-java/blob/master/libjava/lib/src/main/java/com/mapbox/services/commons/utils/PolylineUtils.java#L210. Reopen if this needs to be updated somewhere else.

**Comment by zugaldia** [comment]
This still needs some fixing, the TestApp, in order to work, does: `Position[] after = PolylineUtils.simplify(before, 0.001 * tolerance, quality);`

**Comment by cammace** [comment]
This was fixed in https://github.com/mapbox/mapbox-java/pull/108/commits/a40c26910c2471967ae5f5f76d4da1f43586350f, Can we close now @zugaldia?

**Comment by zugaldia** [comment]
Fixed via https://github.com/mapbox/mapbox-java/pull/116.
