### ISSUE TITLE
BoundingBox#fromCoordinates is deprecated

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#1018]
From coordinate is deprecated in BoundingBox, being able to create a bounding box from 4 numbers where the caller indicates which is east/north/.. is easy to use and doesn't require the creation of additional LatLng or geometry objects. 

Can some context be added why it was deprecated?

**Comment by langsmith** [comment]
@tobrun 

Blame history for that `BoundingBox` file: https://github.com/mapbox/mapbox-java/blame/master/services-geojson/src/main/java/com/mapbox/geojson/BoundingBox.java

<img width="1007" alt="Screen Shot 2019-05-01 at 7 08 05 AM" src="https://user-images.githubusercontent.com/4394910/57021013-f68fa980-6bdf-11e9-99a2-4bf1c0a9e1ba.png">


https://github.com/mapbox/mapbox-java/pull/789 resolved https://github.com/mapbox/mapbox-java/issues/788

**Comment by tobrun** [comment]
thanks

**Comment by osana** [comment]
@tobrun The reason was that in 3.0.0 release `fromLngLats` method names were used. In BoundingBox renaming did not happen (just was missed). For consistency `fromLngLats` was added and `fromCoordinates` was deprecated.
