### ISSUE TITLE
Rename map IDs to tileset identifiers

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-java#1021]
Map IDs are being renamed to tileset IDs across the board. In the Java SDK, only the Tilequery API code appears to be affected:

https://github.com/mapbox/mapbox-java/blob/9fa87fb4c1b1ae82acdb44fec4a8d488821c3cc5/services-tilequery/src/main/java/com/mapbox/api/tilequery/TilequeryService.java#L35 https://github.com/mapbox/mapbox-java/blob/9fa87fb4c1b1ae82acdb44fec4a8d488821c3cc5/services-tilequery/src/main/java/com/mapbox/api/tilequery/TilequeryService.java#L60 https://github.com/mapbox/mapbox-java/blob/82837f302d84c3321c3fc12b2ad9bbf0e3f75941/services-tilequery/src/main/java/com/mapbox/api/tilequery/MapboxTilequery.java#L208

/cc @osana

**Comment by langsmith** [comment]
Re-opened because #1022 had to be reverted. Will open a new pr to resolve this issue.
