### ISSUE TITLE
Return feature from TurfMeasurement#bboxPolygon

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#1042]
TurfMeasurement#bboxPolygon returns Polygon while it should return a feature wrapping a polygon (see [here](https://turfjs.org/docs/#bboxPolygon)). Additionally it needs to expose an optional parameter which can contain feature properties and ID that can be used to create the feature.

**Comment by langsmith** [comment]
Would you refactor the current methods (leading to breaking semver) or just add new/correct versions of `TurfMeasurement#bboxPolygon`? I'm thinking refactoring because if not, devs would see 4 versions of the same method. 2 versions would return `Polygon` and 2 would return `Feature`...

**Comment by tobrun** [comment]
I think we can get away with calling this a implementation bug so we wouldn't be breaking semver :trollface:

**Comment by langsmith** [comment]
😏
