### ISSUE TITLE
ReverseGeocode on version 8.0.0 plugin 0.8.0 always got error not a json array.

### ISSUE THREAD

**Issue by cabuhatprince** [mapbox/mapbox-java#1043]
I tried the newest version of mapbox but when i try my function reverseGeocode i got this error: java.lang.IllegalStateException: Not a JSON Array: {"coordinates":[121.035026,14.629892],"type":"Point"}

**Comment by LukasPaczos** [comment]
Hey @cabuhatprince, this might be a dependency mismatch. Are you including mapbox services separately in your `build.gradle` file, or using the transitive dependency from the Maps SDK?

If the former, you can remove the dependency entry for mapbox services and use the transitive one, or make sure to use the latest one (`v4.8.0`) or at least `v4.6.0`.

**Comment by codeversed** [comment]
I was using the following:
```
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.3.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places:0.6.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.6.0'
implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:4.8.0'
```
I had the same gson parsing issues. Removed the turf package, no parsing issues.

**Comment by cabuhatprince** [comment]
@LukasPaczos @codeversed Thank you.. i added mapbox services in dependency and boom! it's working now. :)

**Comment by LukasPaczos** [comment]
The JSON parsing has changed a bit in the `v4.6.0`, so if there are versions >= `v4.6.0` and < `v4.6.0` pulled in at the same time as transitive deps, it might result in the crash from the OP.
