### ISSUE TITLE
sources.jar artifacts empty on Maven Central

### ISSUE THREAD

**Issue by gwimmel** [mapbox/mapbox-java#1053]
#### Expected Behavior

sources.jar on Maven Central (current version: [https://search.maven.org/remotecontent?filepath=com/mapbox/mapboxsdk/mapbox-sdk-turf/4.8.0/mapbox-sdk-turf-4.8.0-sources.jar](https://search.maven.org/remotecontent?filepath=com/mapbox/mapboxsdk/mapbox-sdk-turf/4.8.0/mapbox-sdk-turf-4.8.0-sources.jar) ) contains mapbox-sdk-turf sources.

#### Current Behavior
The above file seems to contain only empty folders. Therefore one cannot easily navigate to the mapbox-sdk-turf sources in one's IDE.

#### Possible Solution
If the current behaviour is not intentional, modify the release process for mapbox-sdk-turf such that a valid sources.jar file is generated and uploaded to Maven Central.

#### Steps to Reproduce

Download the sources.jar - file linked above and view the contents.

**Comment by tobrun** [comment]
thank you for the report @gwimmel, confirmed that no java files are included.

**Comment by LukasPaczos** [comment]
This is also the case for all artifacts, not only `turf`.

**Comment by gwimmel** [comment]
I guess this is due to [https://github.com/mapbox/mapbox-java/commit/be2f75ce8506120d44b6f752a0a8650818e155c1#diff-c197962302397baf3a4cc36463dce5ea](https://github.com/mapbox/mapbox-java/commit/be2f75ce8506120d44b6f752a0a8650818e155c1#diff-c197962302397baf3a4cc36463dce5ea). The "**/*.java" - exclusion probably also applies to the sources jars, which it shouldn't.

**Comment by gwimmel** [comment]
The pull reqest seems to be stale - should I open a new one with my suggestion?

**Comment by tobrun** [comment]
@gwimmel I was trying out your proposed solution with a snapshot build but failed to get a build working (see [here](https://github.com/mapbox/mapbox-java/pull/1037#issuecomment-508393882) for context). Feel free to create a new pull request! You deserve the contributions on this one ;)

**Comment by gwimmel** [comment]
Strange - you mean the deployment to jfrog does not work when my proposed solution is applied, but does work otherwise? The problem you cited seems unrelated to me. The sources.jar-Files are also generated/deployed in the current version, the only thing my fix should change is their content.

**Comment by tobrun** [comment]
it doesn't work otherwise either :) I believe your proposed solution will work though I would have loved to verify it with a snapshot build which isn't possible atm :panda_face:

**Comment by gwimmel** [comment]
Here's my pull request. Cannot test it very well either, as in the current build on master the sources.jar-Files seem not to be generated at all (when I execute "gradle assemble"). This definitely worked before the last commit on build.gradle.

**Comment by langsmith** [comment]
Now that Java SDK SNAPSHOTs are working and available, you two should be able to keep investigating if you'd like. I'll try to swing back 'round to #1064 myself.
