### ISSUE TITLE
MapboxOptimization returns code NotImplemented with roundtrip is set to false

### ISSUE THREAD

**Issue by BinaryPigStudio** [mapbox/mapbox-java#1060]
The mapboxoptimization request can't calculate a route for any set of points if the roundtrip is set to false and destination is set to "any".
Multiple combinations were tested but only if the destionation is set to "last" will the route be successfully calculated.

MapboxOptimization.builder().accessToken(my_token)
                    .source(DirectionsCriteria.SOURCE_FIRST)
                    .destination(DirectionsCriteria.DESTINATION_ANY)
                    .coordinates(points)
                    .overview(DirectionsCriteria.OVERVIEW_FULL)
                    .profile(DirectionsCriteria.PROFILE_DRIVING)
                    .roundTrip(false)
                    .build()

This builder gives a 200 OK response with the code "NotImplemented".

what would be the solution?
Thank you

**Comment by BinaryPigStudio** [comment]
This issue was in fact a non-supported functionality.
Is this a feature in the works or is just impossible to get an optimized route without a set destination?

**Comment by langsmith** [comment]
Hey @BinaryPigStudio , thanks for looking into Mapbox. If round trip is false and the destination is set to any location, what would an optimized route be? It sounds like you'd be interested in the Mapbox Matrix API: https://docs.mapbox.com/android/java/overview/directions-matrix

This API would give you duration/distance from any number of points to any other number of the same points. The Matrix logic would fit your false roundtrip and any destination scenario.
