### ISSUE TITLE
Program type present RuntimeTypeAdapterFactory

### ISSUE THREAD

**Issue by v-grishechko** [mapbox/mapbox-java#1063]
I use two libraries mapbox-sdk and internal library from company (which I can't change). In this libraries class `com.google.gson.typeadapters.RuntimeTypeAdapterFactory` copied by hand in a projects, due that gradle build fails with error.

#### Expected Behavior

Gradle build finish successfully
#### Current Behavior

Gradle build fails with error:
```
AGPBI: {"kind":"error","text":"Program type already present: com.google.gson.typeadapters.RuntimeTypeAdapterFactory","sources":[{}],"tool":"D8"}
```
#### Possible Solution
I suggest add dependency:
```
implementation "com.google.code.gson:gson-extras:2.8.5"
```
and remove `RuntimeTypeAdapterFactory` class from project. Then I can exclude `gson-extras` in `build.gradle` file to resolve error. But the only issue with this solution it is adding new maven source. Detailed info [there](https://mvnrepository.com/artifact/com.google.code.gson/gson-extras/2.8.5).

#### Steps to Reproduce
 1. Add mapbox-sdk dependency
 2. Add dependency with copied class `com.google.gson.typeadapters.RuntimeTypeAdapterFactory`
 3. Build project

#### Context (Environment)

Try to build android app by gradle.

**Comment by hrach** [comment]
This is now fixed https://github.com/mapbox/mapbox-java/pull/1153 since 5.3.0, force version by
implementation("com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.3.0")
