### ISSUE TITLE
Turf: add polygonToLine method

### ISSUE THREAD

**Issue by samfader** [mapbox/mapbox-java#1072]
This is a feature request to add http://turfjs.org/docs/#polygonToLine to this library. This method converts a Polygon to (Multi)LineString or MultiPolygon to a FeatureCollection of (Multi)LineString.

**Comment by langsmith** [comment]
https://github.com/Turfjs/turf/tree/master/packages/turf-polygon-to-line

**Comment by pengdev** [comment]
This feature dependents on meta/getCoords, meta/getGeom, which is not yet ported to turf-java.

**Comment by langsmith** [comment]
[`meta/getCoords`](http://turfjs.org/docs/#getCoords) should be equal to the `coordAll` methods in https://github.com/mapbox/mapbox-java/blob/master/services-turf/src/main/java/com/mapbox/turf/TurfMeta.java
