### ISSUE TITLE
MapboxDirections builder throws Exception when approaches is empty. 

### ISSUE THREAD

**Issue by Lebedinsky** [mapbox/mapbox-java#1081]
**Bug Report**

#### Expected Behavior
`MapboxDirections.Builder#build()` should not throw exception when approaches array is empty.

#### Current Behavior
`MapboxDirections.Builder#build()` throws `ServicesException` exception when approaches array is empty.

#### Possible Solution
Cause of this issue is we trying to compare size of `approaches` and `coordinates`. But actually, we should compare size of `approaches` and `waypointIndices`.

#### Steps to Reproduce
1. Set `approaches` as empty array.
2. Call `MapboxDirections#build()` method.

#### Context (Environment)
We want to avoid using nullable types in Navigation SDK. So before we set nulls (`waypointIndices`, `waypointNames`, `approaches`) to builder and it works, but now we will send empty arrays instead of nulls.

**Comment by Guardiola31337** [comment]
Was this addressed in #1118 and #1121? Are we good to close here? @Lebedinsky @korshaknn

**Comment by korshaknn** [comment]
@Guardiola31337 no, it was not addressed. logic inside MapboxDirections was not changed
```
if (!approaches.isEmpty()) {
        if (approaches.size() != coordinates.size()) {
          throw new ServicesException("Number of approach elements must match "
            + "number of coordinates provided.");
        }
        String formattedApproaches = FormatUtils.formatApproaches(approaches);
        if (formattedApproaches == null) {
          throw new ServicesException("All approaches values must be one of curb, unrestricted");
        }
        approaches(formattedApproaches);
}
```

**Comment by Guardiola31337** [comment]
Thanks for confirming @korshaknn 🙇

**Comment by Lebedinsky** [comment]
@Guardiola31337 Not sure, because as we can see [here](https://github.com/mapbox/mapbox-java/pull/1118) `FormatUtils#formatApproaches()` method we still can return `null`, and as I see we pass this potentially null-string to `MapboxDirections` builder.

**Comment by RingerJK** [comment]
> @Guardiola31337 no, it was not addressed. logic inside MapboxDirections was not changed
> 
> ```
> if (!approaches.isEmpty()) {
>         if (approaches.size() != coordinates.size()) {
>           throw new ServicesException("Number of approach elements must match "
>             + "number of coordinates provided.");
>         }
>         String formattedApproaches = FormatUtils.formatApproaches(approaches);
>         if (formattedApproaches == null) {
>           throw new ServicesException("All approaches values must be one of curb, unrestricted");
>         }
>         approaches(formattedApproaches);
> }
> ```

we're good to close the issue, approaches' list is _NonNull_ and here we check that it's not null. Logic inside block, after check approaches is not null is right. The problem was with legacy when approaches were checked if null only(but not if empty)
