### ISSUE TITLE
LocationComponent above all layers

### ISSUE THREAD

**Issue by Ne1c** [mapbox/mapbox-java#1083]
Hello, I had a situation: on my map a lot of markers and other stuff I want to show my current location but problem is tracker icon places below my layers. I found method layerAbove() but it doesn't appropriate for my case I want to show user picker above all my layers on map. How can I do it?

**Comment by langsmith** [comment]
Hey @Ne1c , thanks for using Mapbox! You can use the `layerAbove()` method of `LocationComponentOptions`, which will place the `LocationComponent` puck on top of whatever layer you specify. You can view usage of the `LocationComponentOptions` class in https://docs.mapbox.com/android/maps/examples/location-component-options/. 

You'll have to figure out the layer id of the top layer. This layer id will be used as a parameter in the `layerAbove()` method. You can find the top layer of the style via Mapbox Studio or you can print all of the map style layers to the logcat to see their z index.

https://docs.mapbox.com/android/maps/overview/styling-map/#retrieving-a-map-layer

<img width="632" alt="Screen Shot 2019-10-09 at 8 06 46 AM" src="https://user-images.githubusercontent.com/4394910/66493989-cb04cb00-ea6b-11e9-8bd4-a684f378fb4a.png">

**Comment by Ne1c** [comment]
@langsmith but I have dynamic layers they appear and disappear and I don't have all layers at moment when map style are loaded

**Comment by Ne1c** [comment]
What if I don't know which layer is above of all?

**Comment by langsmith** [comment]
This would print all the layers so that you know what the layer order is:

```java
mapboxMap.getStyle(new Style.OnStyleLoaded() {
	@Override
	public void onStyleLoaded(@NonNull Style style) {
	
	  for (Layer singleLayer : style.getLayers()) {
	    Log.d(TAG, "onStyleLoaded: layer id = " + singleLayer.getId());
	  }
	  
	}
});
```

The following would give you the top layer ID at the current time:

```java
   mapboxMap.getStyle(new Style.OnStyleLoaded() {
        @Override
        public void onStyleLoaded(@NonNull Style style) {

          Log.d(TAG, "onStyleLoaded: last style id = "
              + style.getLayers().get(style.getLayers().size() - 1).getId());

        }
});
```

**Comment by Ne1c** [comment]
In fact I have to do this operation every time when I delete or remove layer. Right?

**Comment by langsmith** [comment]
Yes. Here are two other options you might prefer instead:

1. When initializing the map, you could add an empty layer on top, and place the `LocationComponent` above the empty layer. Then just make sure to always add future layers below the empty layer.

2. https://docs.mapbox.com/android/api/map-sdk/8.4.0/com/mapbox/mapboxsdk/location/LocationComponentConstants.html#SHADOW_LAYER is the bottom layer of the `LocationComponent`. You could add all dynamic layers below `SHADOW_LAYER` to keep everything under the puck. This would only work *after* the `LocationComponent` is fully initialized.
