### ISSUE TITLE
Fix DirectionsRoute annotations so they match what actually comes from the API

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-java#1087]
Currently we have `distance` and `duration` (from `DirectionsRoute`) marked as `@Nullable` in the java wrapper https://github.com/mapbox/mapbox-java/blob/9bd6158292374fc6dd5f7eba33e7586ca1d76177/services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java#L50-L51 https://github.com/mapbox/mapbox-java/blob/9bd6158292374fc6dd5f7eba33e7586ca1d76177/services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java#L59-L60 and @mapbox/navigation-api has confirmed that if a valid route is returned it has to get these two values, so they can be marked as `@NonNull`.

Refs https://docs.mapbox.com/api/navigation/#route-object

**Comment by Guardiola31337** [comment]
cc'ing @abhishek1508 for visibility

**Comment by abhishek1508** [comment]
What happens when no route is returned for a POI. Should they still be non nullable?

**Comment by Guardiola31337** [comment]
> What happens when no route is returned for a POI. Should they still be non nullable?

> if a valid route is returned it has to get these two values

`DirectionsRoute` is only returned when the request goes 👌

**Comment by abhishek1508** [comment]
@Guardiola31337 Nope. When working on GM we came across scenarios, where the `DirectionsRoute` response was received, but there was not route found. It didn't throw any error. @olegzil Correct me if I am wrong.

**Comment by olegzil** [comment]
@abhishek1508 is correct. There were cases when we did receive the response, without a route

**Comment by Guardiola31337** [comment]
Yeah, that's correct but we can control those (`NoRoute`) and don't serialize into a `DirectionsResponse`, right? Basically, treat the error case scenario 😉

**Comment by danpaz** [comment]
Just driving by to note that there is a top level key in the any successful Directions API response called `code`, that will tell you whether the response contains a route or not. The value of `code` is one of `Ok`, `NoRoute`, `NoSegment`, or `InvalidInput`. Only when the code is `Ok` should you attempt to serialize the routes.

For example , a `Ok` response will contain one or more routes in the `routes` array, and each route will have non-null distance and duration.
```
{
  code: 'Ok',
  routes: [ { /* valid route with distance and duration */ } ],
  ...
}
```

A `NoRoute` response will look like this, with an empty routes array:
```
{
  code: 'NoRoute',
  routes: [],
}
```

There's a bit more info on these codes in the API documentation [here](https://docs.mapbox.com/api/navigation/#directions-api-errors).

**Comment by abhishek1508** [comment]
This sounds good. Thanks for sharing this @danpaz

**Comment by cbrennst** [comment]
I also stumbled about this and we work with duration and distance in a lot of code places. Sometimes we handle the `null`-case, sometimes we would hard crash (`checkNotNull(route.duration())`) .

I would really like to get this consistent, because every `null`-handling is more code, we have to maintain. From what I read here, it is actually not necessary...
