### ISSUE TITLE
GeoJSON module via Maven

### ISSUE THREAD

**Issue by tambellinila** [mapbox/mapbox-java#1088]
I was trying to use GeoJSON jar in my Java Spring Boot App. From the docs it looks like it should work without any android dependencies, however I had import com.android.support from the google repo? Is this correct, or am I missing something

**Comment by LukasPaczos** [comment]
We're using nullability annotations from Google's Android package, however, it's only a JAR, so it shouldn't cause any other issues in pure Java projects.
