### ISSUE TITLE
Make a line layer always appear above other line layer 

### ISSUE THREAD

**Issue by saddahussain** [mapbox/mapbox-java#1090]
I have added a source A and a Line Layer A, which draws a black line from point A-B-C.
Then I add another source B and Line Layer B, which draws a white line from point A-B.
Now what I want is to make Source/Layer B to always appear above Source/Layer A. Resultant line should be  (A-B) In white and (A-B)-C in black.

**Comment by langsmith** [comment]
Hi @saddahussain , thanks for using Mapbox. For Mapbox implementation questions, please contact our great Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231. Someone will be able to help you with this question.
