### ISSUE TITLE
Bump versions of StaticMapCriteria style strings

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-java#1106]
https://github.com/mapbox/mapbox-java/blob/master/services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/StaticMapCriteria.java has `static final String`s to use in the `styleId()` builder method for `MapboxStaticMap`.

Opening this ticket to enquire/track whether we need to bump the versions referenced in the `StaticMapCriteria`. `streets-v10` would be `streets-v11` and so on.

The sample code snippet in https://docs.mapbox.com/api/maps/#example-request-retrieve-a-static-map-from-a-style uses `streets-v11`, which makes me think that this ticket is valid in this repo.

cc @mapbox/static-apis

**Comment by riastrad** [comment]
@langsmith thank you for cutting the ticket and tapping us in. Yes, these versions should all be updated by one version, as `streets-v11`, `light-v10`, etc represent the latest versions of the Mapbox provided "style templates".

**Comment by langsmith** [comment]
Great, thanks for the follow-up @riastrad
