### ISSUE TITLE
RouteOptions should expose toBuilder method

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-java#1108]
`RouteOptions` class could be reused to request a route and it should expose a `toBuilder` method so that it can be manipulated.

**Comment by Guardiola31337** [comment]
Maybe we can cut separate tickets but all options classes should expose a `toBuilder` method. So it'd be great if we could audit the code and add those `toBuilder` to any other class that might need it.

**Comment by LukasPaczos** [comment]
Integration in https://github.com/mapbox/mapbox-navigation-android/pull/2416.
