### ISSUE TITLE
Enforce code quality standards

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#111]
The main SDK is thinking of enforcing code quality standards in https://github.com/mapbox/mapbox-gl-native/issues/4299. We should tag along for consistency.

**Comment by zugaldia** [comment]
The basic infrastructure is now in place, just use `./gradlew checkstyle`.

However:
1. We're far from compliance.
2. It isn't yet integrated with Bitrise.
2. I'm not sure we're using the right `checkstyle.xml` (currently using the one from https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml. 

Reopening to discuss these.

**Comment by cammace** [comment]
Discovered this [awesome IDEA plugin](https://github.com/jshiell/checkstyle-idea) which will give you warnings right inline with the code, example:

<img width="584" alt="screen shot 2016-07-13 at 2 21 39 pm" src="https://cloud.githubusercontent.com/assets/5652865/16814748/2b3431b6-4905-11e6-90fa-01d2035db37c.png">

it's pretty configurable too. Still looking into all the rules in `checkstyle.xml`.

**Comment by cammace** [comment]
I've made my way through the massive amounts of documentation checkstyle has and figured out how to add a custom check (in PR #123). Now I'm going through and cleaning up the obvious warnings checkstyle has within the testapp. If it's something i'm not sure we should fix, i'll leave it for discussion and possible removal of that rule.

**Comment by cammace** [comment]
PR #124 includes most of the checkstyle warning fixes. My thoughts so far:

* It successfully catches Hungarian notation!
* Ordering of imports rule, I believe called `THIRD_PARTY_PACKAGE` goes against what Android Studio wants the order to be.
* Android Studio uses 12 indentation but check style is wanting 8 indentation? This is causing a ton of warnings in, for example, [this file](https://github.com/mapbox/mapbox-java/blob/master/libandroid/app/src/main/java/com/mapbox/services/android/testapp/icons/DirectionsList.java).
* Currently a rule that limits lines to a 120 character length. This is good except when you have a long [LineString](https://github.com/mapbox/mapbox-java/blob/master/libandroid/app/src/main/java/com/mapbox/services/android/testapp/turf/TurfLineSliceActivity.java#L43). This can always be moved to the `strings.xml` though.
* A rule should be added to catch variables and imports not being used.
* Checkstyle warns when a variable name is a single letter, which makes sense in most cases except here:
<img width="562" alt="screen shot 2016-07-13 at 4 11 14 pm" src="https://cloud.githubusercontent.com/assets/5652865/16818906/1a676926-4918-11e6-968c-328a49c2f3ea.png">

**Comment by bleege** [comment]
Reference information:

http://checkstyle.sourceforge.net/google_style.html

http://checkstyle.sourceforge.net/sun_style.html

**Comment by bleege** [comment]
Style From Mapbox Android Legacy:

https://github.com/mapbox/ma-sdk-legacy/blob/mb-pages/checks.xml

**Comment by bleege** [comment]
Square Style From Retrofit:

https://github.com/square/retrofit/blob/master/checkstyle.xml

**Comment by zugaldia** [comment]
@mapbox/android As discussed, we're gonna with https://github.com/square/java-code-styles. I'll install and document this and ping you all when ready.

**Comment by cammace** [comment]
After setting up java-code-styles, I attempted to get sqaures checkstyle.xml file up and running in Android Studio and it was outputing quite a few errors. Did a little research and after reading this [ticket](https://github.com/square/java-code-styles/issues/9), it looks like squares using [Google java format](https://github.com/google/google-java-format/) instead with explicitly says:

> There is no configurability as to the formatter's algorithm for formatting. This is a deliberate design decision to unify our code formatting on a single format.

Waiting on this till Monday when we can discuss this more internally.

**Comment by zugaldia** [comment]
@cammace As discussed today, let's continue with researching https://github.com/google/google-java-format/ instead and, if it looks good, let's just adopt it.

**Comment by cammace** [comment]
Looking more into this, I setup `google-java-format` in Studio and quickly realized it only automates the process of reformatting the code in the file, it doesn't cause warnings/errors like checkstyle does. It also doesn't look like integration with CI would be possible. 

Moving forward, I think the best route will be to continue with using the current Google checkstyle in this repo and customizing it where we see fit over the next few weeks. Next steps will be cleaning up the code so all warnings, errors are relieved and then integrating into Bitrise.
