### ISSUE TITLE
Release 5.1.0-beta.1

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-java#1113]
### CHANGELOG

Changes since the `5.0.0` release of The Mapbox Java SDK

- Removed typo in `BannerView` class javadocs (#1111)
- Extract refresh models into separate module (#1107)
- Bumped `StaticMapCriteria` constant style strings to new versions (#1109)
- Add `toBuilder()` method to `RouteOptions` and `WalkingOptions` (#1110)
- Split Directions models from the implementation into a separate module (#1104)

### 5.1.0-beta.1 release checklist 

- [x] Update this repo's `README.md` file (Don't need for a beta)
- [x] Change version name to `5.1.0-beta.1` in `gradle.properties` (removing `-SNAPSHOT`)
- [x] Publish `5.1.0-beta.1` artifact to Maven Central
- [x] Change version name back to having `-SNAPSHOT` at the end
- [x] Update `CHANGELOG.md`
- [x] Create a new release in Github with a release title of `Mapbox Java SDK v5.0.0-beta.1` and a tag version of `v5.1.0-beta.1`
- [ ] Update dependencies in 
  - [ ] the Maps SDK and 
  - [ ] Navigation SDK to the final release version
    
### Post final release   
- [ ] Update [the dependencies file in the Mapbox Android Plugins `/mapbox-plugins-android` repo](https://github.com/mapbox/mapbox-plugins-android/blob/master/gradle/dependencies.gradle#L11)
- [ ] Update version # in config files in the `/help` repo
- [ ] Update [the Mapox Android demo app](https://github.com/mapbox/mapbox-android-demo/blob/master/gradle/dependencies.gradle)
- [ ] After updating the demo app, make the following changes in the `/android-docs` repo: 
  - [ ] Update API reference Javadocs for the Mapbox Java docs section in `/android-docs` repo:
  - [ ] Update [the `JAVA_SDK_VERSION` constant in the `constants.js` file in the `/android-docs` repo](https://github.com/mapbox/android-docs/blob/publisher-production/src/constants.json)
- [ ] Update version # in the Studio Preview for Android app
- [ ] Update version # in the China plugin test app

/cc: @mapbox/android

**Comment by langsmith** [comment]
5.1.0-SNAPSHOT is being used in the Nav SDK https://github.com/mapbox/mapbox-navigation-android/blob/master/gradle/dependencies.gradle#L12-L13

We don't use betas/SNAPSHOTs in the Maps SDK.

No docs need to be updated for Java SDK beta releases. Closing 'cause we're done here.
