### ISSUE TITLE
RouteOptions parsing improvements

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-java#1117]
Currently, if we're trying to reuse `RouteOptions` object for creating route requests we constantly need to switch Object impl -> String representation -> Object impl and repeat the other way around.

An example can be the Directions request's `bearings` field:
- The user needs to pass `bearings` in a `String` format in the Nav SDK to make a request.
- We're parsing this `String` into objects inside of the SDK to match `MapboxDirections`' `addBearing(Double angle, Double tolerance)`.
- `MapboxDirections` parses it back to `String` to make a request.

We should cut that middle conversion. We can possibly do it by moving all of the utility methods based on objects to `RouteOptions`.

/cc @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
Was this addressed in https://github.com/mapbox/mapbox-java/pull/1118 and https://github.com/mapbox/mapbox-java/pull/1121? Are we missing any follow up work? Are we good to close here? @korshaknn @LukasPaczos

**Comment by LukasPaczos** [comment]
Yes, we should be good to close for now.
