### ISSUE TITLE
Version 5.0.0 requires Java 8+ or Android 5+, because of Retrofit 2.7.1

### ISSUE THREAD

**Issue by xit0c** [mapbox/mapbox-java#1127]
With mapbox-java 5.0.0, Retrofit dependency has been updated to 2.7.1 (see [dependencies.gradle](https://github.com/mapbox/mapbox-java/blob/v5.0.0/gradle/dependencies.gradle)).

But Retrofit, from version 2.7.0, requires Java 8+ or Android 5+ (see [Retrofit changelog](https://github.com/square/retrofit/blob/master/CHANGELOG.md)). That's because, in that release, Retrofit's OkHttp dependency was updated to 3.14.4 and OkHttp has those requirements since version 3.13.0 (see [OkHttp changelog](https://square.github.io/okhttp/changelog_3x/#version-3130)).

I suggest to use the 3.12.x branch for OkHttp and the 2.6.x branch for Retrofit, at least until they're supported (December 31, 2020 as explained [here](https://square.github.io/okhttp/#requirements)), since it's the only way to support pre-Lollipop devices.

Furthermore, mapbox-gl-native-android 9.0.0 uses mapbox-java 5.0.0 (see [dependencies.gradle](https://github.com/mapbox/mapbox-gl-native-android/blob/android-v9.0.0/gradle/dependencies.gradle)), so the android library is affected too.

**Comment by xit0c** [comment]
Should I open an issue (that links to this one) in the mapbox-gl-native-android repo too?

**Comment by zugaldia** [comment]
cc: @mapbox/maps-android

**Comment by zugaldia** [comment]
Thank you @xit0c for bringing this up. I've put it on the Nav SDK's backlog for investigation.

It currently doesn't affect Maps SDK because it only consumes the GeoJSON package, which doesn't have Retrofit dependencies. Did you have a different experience?

**Comment by xit0c** [comment]
@zugaldia Sorry for the late :pray: you're right: mapbox-android-sdk is not affected.

I use both mapbox-sdk-services and mapbox-android-sdk in my project, so for now I resolved using version 4.9.0 and 9.0.1 respectively. With this setup, the resultant OkHttp dependency of the project belongs to the 3.12.x branch.

**Comment by Guardiola31337** [comment]
@xit0c is this still relevant? Are we good to close?

**Comment by xit0c** [comment]
Sure, I'm closing!
Thank you for your support.

**Comment by Guardiola31337** [comment]
Thanks for confirming @xit0c and thank you for checking out our SDKs 💃
