### ISSUE TITLE
Release 5.2.0

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-java#1143]
### CHANGELOG

Changes since the [5.1.0](https://github.com/mapbox/mapbox-java/issues/1134) release of the Mapbox Java SDK

- Add step maneuver modifier constants (#1142)
- Refactor turf measurement functions (#1139)
- remove stale bot settings for this repo (#1138)
- Fix typo in DirectionsJsonObject documentation (#1137)

### 5.2.0 release checklist 

- [x] Create release branch off of `master` https://github.com/mapbox/mapbox-java/pull/1144
- [x] Update this repo's `README.md` file 
- [x] Update `CHANGELOG.md`
- [x] Create a new Github release with a release title of `Mapbox Java SDK v5.2.0` and a tag version of `v5.2.0`, targeting the release branch. https://github.com/mapbox/mapbox-java/releases/tag/v5.2.0
- [ ] Update dependencies in the Maps SDK and Navigation SDK to the final release version
    
### Post final release   
- [x] Update [the dependencies file in the Mapbox Android Plugins `/mapbox-plugins-android` repo](https://github.com/mapbox/mapbox-plugins-android/blob/master/gradle/dependencies.gradle#L11)
- [x] Update version # in config files in the `/help` repo
- [x] Update [the Mapox Android demo app](https://github.com/mapbox/mapbox-android-demo/blob/master/gradle/dependencies.gradle)
- [x] After updating the demo app, make the following changes in the `/android-docs` repo: 
  - [x] Update API reference Javadocs for the Mapbox Java docs section in `/android-docs` repo:
  - [x] Update the `JAVA_SDK_VERSION` constant in the `constants.js` file in the `/android-docs` repo
- [x] Update version # in the Studio Preview for Android app
- [ ] Update version # in the China plugin test app

/cc: @mapbox/android

**Comment by kmadsen** [comment]
Need to do a 5.2.1 because I'm forgetting how to java
https://github.com/mapbox/mapbox-java/pull/1146

**Comment by langsmith** [comment]
An interface needed to be made public and that was forgotten before 5.2.0 release

https://github.com/mapbox/mapbox-java/pull/1142#pullrequestreview-411078839
