### ISSUE TITLE
Add support for Optimization API calls with more than 12 coordinates

### ISSUE THREAD

**Issue by pjleonard37** [mapbox/mapbox-java#1157]
For certain use cases and with Mapbox approval, Optimizations API calls can be made with more coordinates than the [standard limit](https://docs.mapbox.com/api/navigation/#optimization-api-restrictions-and-limits) of 12. This ticket proposes modifying the Java SDK to support requests with greater than 12 calls. 

https://github.com/mapbox/mapbox-java/blob/123e7cd6c7aac9b125ed2a679c09f68b6e5dadd7/services-optimization/src/main/java/com/mapbox/api/optimization/v1/MapboxOptimization.java#L480

Similar request to modify coordinate limit for the Matrix API: https://github.com/mapbox/mapbox-java/issues/1124

cc: @zugaldia, @danpat, @langsmith

**Comment by langsmith** [comment]
My initial thought is that the fix for this ticket would basically be duplicating the changes that I made in https://github.com/mapbox/mapbox-java/pull/1133, to the Optimization API wrapper.

**Comment by Guardiola31337** [comment]
Yes it is. Don't know why Github didn't close it automatically after merging https://github.com/mapbox/mapbox-java/pull/1339 🤔 

Anyways, closing as resolved.

**Comment by RingerJK** [comment]
from the pr: 
![image](https://user-images.githubusercontent.com/8738058/145548400-dff9aa36-3bef-41e6-ba47-8dd737131662.png)

need to add the keyword (fixes, close, and so on) for each issue
```
Fixes #1
Fixes #2
...
```
