### ISSUE TITLE
Mapbox SDK Core 5.3.0 is missing from Maven Central

### ISSUE THREAD

**Issue by MaartenTutak** [mapbox/mapbox-java#1161]
**com.mapbox.mapboxsdk:mapbox-sdk-core:5.3.0** seems to be missing from Maven Central.
https://search.maven.org/search?q=g:com.mapbox.mapboxsdk%20AND%20a:mapbox-sdk-core%20AND%20v:5.3.0

**Comment by langsmith** [comment]
Yes, strange that some of the Java SDK's modules didn't make it to a `5.3.0` version. Weird. Sorry about that @MaartenTutak . Thanks for this ticket.

I just put out a `5.4.1` release https://github.com/mapbox/mapbox-java/issues/1162 and `core` is showing `5.4.1` at https://search.maven.org/search?q=g:com.mapbox.mapboxsdk. 

https://bintray.com/mapbox/mapbox/mapbox-sdk-directions-refresh-models/5.4.1 and https://bintray.com/mapbox/mapbox/mapbox-sdk-directions-models/5.4.1 were synced with Maven Central with no issues, so I expect `mapbox-sdk-directions-refresh-models` and `mapbox-sdk-directions-models` to show `5.4.1` at https://search.maven.org/search?q=g:com.mapbox.mapboxsdk soon too.
