### ISSUE TITLE
Build lib and execute a Directions API response round-tripping test

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-java#1170]
This ticket tracks implementation of a script/program that
1. takes a version of Mapbox Java and a Directions API JSON response as arguments
2. compiles the `services-directions-models` JAR
2. performers deserialization -> serialization
3. asserts that the result of the serialization matches the original input

The script/program can be used by upstream providers (Directions API team) to verify that newly introduced changes do not break consumer contracts, or narrow down issues in the platform parsers.

/cc @zugaldia @danpaz @Guardiola31337 @1ec5

**Comment by LukasPaczos** [comment]
Java equivalent of https://github.com/mapbox/mapbox-directions-swift/issues/451.

**Comment by 1ec5** [comment]
Fixed in mapbox/mapbox-java#1198.
