### ISSUE TITLE
Add support for `geojson` geometries in the route response

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-java#1180]
Currently `mapbox-java` only supports polyline encoded geometries while the Directions API also supports GeoJSON geometries (LineStrings).

/cc @mapbox/navigation-android

**Comment by zugaldia** [comment]
This was an intentional design decision - the hypothesis was that by requesting encoded polylines (and decoding them client-side) we could reduce the size of the responses and decrease mobile bandwidth metrics. Is that now a limitation?

**Comment by LukasPaczos** [comment]
I was wondering whether there was something more to it, good to know, thanks @zugaldia :+1: Since that was a design decision, I don't have a strong enough reason to push for this impl, it was only a concern of feature parity between mobile SDKs and server APIs.
