### ISSUE TITLE
Broken with Android API 30

### ISSUE THREAD

**Issue by christophermark** [mapbox/mapbox-java#1193]
I noticed some build errors this morning when running this against Android APK version 30.

## The error
```
java.lang.ExceptionInInitializerError
Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
```

## The source
There's an internal dependency here:
https://github.com/mapbox/mapbox-java/blob/9cae54420bdfe7a7a223c1a1553de284f22828fa/gradle/dependencies.gradle#L9

That hardcodes Retrofit to `v2.7.1`. We'd need to update to version `2.7.2`, which includes a fix for Android 30:
https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-272-2020-02-24

The underlying crash comes from the okhttp package that Retrofit uses:
https://square.github.io/okhttp/changelog_3x/#version-3147

## The fix
Mapbox-Java needs to update retrofit [to v2.7.2](https://github.com/mapbox/mapbox-java/blob/9cae54420bdfe7a7a223c1a1553de284f22828fa/gradle/dependencies.gradle#L9).

**Comment by tobrun** [comment]
FYI, you should be able to workaround this for now by including an own depenency pointing to 2.7.2. 
Gradle will pick the latest version.
