### ISSUE TITLE
Expose lanes property of the step intersections

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-java#1195]
The Directions API already returns lane information at every `intersection` where we have lane data and highlights the best possible lane to take.

Similar to https://github.com/mapbox/mapbox-java/pull/1188 we should expose already available `lanes` property of the step intersections.

cc @asinghal22 @zugaldia @danpaz @LukasPaczos

**Comment by LukasPaczos** [comment]
Noting that the `intersection.lanes` ([`IntersectionLanes.java`](https://github.com/mapbox/mapbox-java/blob/master/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/IntersectionLanes.java)) is already available. We only need to extend it with `active` and `valid_indication` properties.
