### ISSUE TITLE
Add tunnelName to StepIntersection

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-java#1196]
Directions is currently returning tunnel names so it should be good to re-revert https://github.com/mapbox/mapbox-java/pull/1179 back now.

cc @zugaldia @danpaz @kshehadeh @baddleydone

**Comment by zugaldia** [comment]
@korshaknn could you run with a new Mapbox Java release so that we can bring this change to the Nav 1.1 SDK release today?

**Comment by korshaknn** [comment]
@zugaldia yep, going to check it

**Comment by korshaknn** [comment]
@zugaldia got `tunnelName` for the same route and using the same token as https://github.com/mapbox/driver-operations/issues/8423#issuecomment-700983535

**Comment by Guardiola31337** [comment]
> could you run with a new Mapbox Java release so that we can bring this change to the Nav 1.1 SDK release today?

Quick naming question

Should we name it `5.7.0-beta.1` or `5.7.0-beta.2`? Latest release was `5.7.0-beta` (without version number suffix)  https://github.com/mapbox/mapbox-java/releases/tag/v5.7.0-beta 😬 

cc @zugaldia @korshaknn

**Comment by Guardiola31337** [comment]
`5.7.0` release happening in https://github.com/mapbox/mapbox-java/issues/1199
