### ISSUE TITLE
Incidents object is not parsed

### ISSUE THREAD

**Issue by evabishchevich** [mapbox/mapbox-java#1206]
A regular json from directions API looks like
```
{
  "routes": [
    {
      "legs": [
        {
          "steps": [],
          "incidents": [],
          ...
        }
      ],
      ...
    }
  ],
  "waypoints": [],
  ...
}
```
As we may see, `incidents` are included as a separate JSON array into a `leg` object. It means the structure should be like `leg` ->`incidents`. 
[The current implementation](https://github.com/mapbox/mapbox-java/blob/112d2f25916a0f966c19c46d1ab93b357d342d3b/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/LegStep.java#L68) is made for `leg` -> `step` -> `incidents`.

**Comment by korshaknn** [comment]
fixed in https://github.com/mapbox/mapbox-java/pull/1207
