### ISSUE TITLE
Javadoc errors

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#121]
When building the javadoc today for `1.2.1` release, errors were found. Many of the packages are missing info as well. i'd like to go in and fix all these issues and make sure everything is documented well. 

On a side note, I think we should try using the `@since` tag to make it easier for users to know when things have been added to the SDK. 

cc: @zugaldia

**Comment by zugaldia** [comment]
> I think we should try using the @since tag to make it easier for users to know when things have been added to the SDK.

👍

**Comment by cammace** [comment]
libandroid javadoc has now been added throughout with only 5 warning being produced. I've also started work on libjava fixes. Still not ready to close this ticket.
