### ISSUE TITLE
Allow gzipped responses

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-java#1211]
We make requests that return large amounts of JSON data, in particular for Route requests. A low-hanging solution to address the issue with large response sizes, would be to allow the server to gzip the response. This can be done by adding `Accept-Encoding: gzip` to our outgoing HTTP requests, and then decompressing them if we get a response with `Content-Encoding: gzip`.

**Comment by Guardiola31337** [comment]
Should be pretty straightforward. We're already doing that for `mapbox-events-android` requests 👀 https://github.com/mapbox/mapbox-events-android/blob/main/libtelemetry/src/main/java/com/mapbox/android/telemetry/GzipRequestInterceptor.java

**Comment by kkaefer** [comment]
Note that ^^ is about sending gzipped data when making a _request_ (i.e. uploading), while this issue is about adding a request header that would allow us to accept a gzipped _response_, which we then need to decompress.

**Comment by Guardiola31337** [comment]
Thanks for clarifying @kkaefer 👍

**Comment by zugaldia** [comment]
> this issue is about adding a request header that would allow us to accept a gzipped response

Closing as non-actionable. This comment from one of the OkHttp maintainers confirms that this is indeed the default behavior: https://github.com/square/okhttp/issues/2132#issuecomment-165888326. [Docs](https://square.github.io/okhttp/calls/#rewriting-responses) call it "transparent compression":

> It will add an Accept-Encoding header for transparent response compression unless the header is already present.
