### ISSUE TITLE
DirectionsRefresh responses are not parsed correctly

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-java#1224]
In https://github.com/mapbox/mapbox-java/pull/1166, we've changed some of the fields in the `DirectionsRoute` object to be non-nullable, specifically the `distance` and `duration` fields. However, we missed that `DirectionsRoute` object is also used to pass information that comes from the `DirectionsRefresh` response that **does not** contain this data. This means that all route refresh responses fail to be parsed and return errors.

We have 2 options:
1. make the above `DirectionsRoute` fields nullable again
2. introduce a new wrapper for the results of the `DirectionsRefresh` responses.
 
Both of those options are breaking semver, but since the `DirectionsRefresh` feature is basically non-functional at the moment, I think we should pull the trigger anyway and document that in release notes for both `mapbox-java` and the Nav SDK.

The exact mistake that we made is here:
https://github.com/mapbox/mapbox-java/pull/1166/files#diff-e48953afd8419fc7f709203da5f7f68d01972f5311d54ecd50e3f4ddeb639065
where we added data to a test fixture that is never going to be present in a real response. This made the tests pass and missed the issue.

/cc @mapbox/navigation-android

**Comment by LukasPaczos** [comment]
For completeness, currently trying to parse a response returns a:
```
throwable=java.lang.NullPointerException: Null distance
```

**Comment by RingerJK** [comment]
I think we have one more option: always add to RouteRefresh request annotations `ANNOTATION_DURATION` and `ANNOTATION_DISTANCE`. That's not expected for users, but still as an option

**Comment by LukasPaczos** [comment]
The missing fields are not the annotations though, but the top-level `distance` and `duration` values.

**Comment by RingerJK** [comment]
They depend on each other. What annotations you add to [RoutOptions](https://github.com/mapbox/mapbox-java/blob/master/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java#L787) these fields are updated

**Comment by LukasPaczos** [comment]
Right, but those are the [`LegAnnotation`](https://github.com/mapbox/mapbox-java/blob/master/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/LegAnnotation.java)s which work correctly and we're missing the top level [distance](https://github.com/mapbox/mapbox-java/blob/master/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java#L51) and [duration](https://github.com/mapbox/mapbox-java/blob/master/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java#L60) that cause a crash.

**Comment by LukasPaczos** [comment]
Being fixed in https://github.com/mapbox/mapbox-java/pull/1225.
