### ISSUE TITLE
Publish new versions to Mapbox SDK registry

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#1227]
With [Bintray/JCenter sunsetting](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), we need to move publishing new versions of this library to the Mapbox SDK registry. 
Older versions of all mapbox-java library have been migrated already.

**Comment by Guardiola31337** [comment]
https://github.com/mapbox/mapbox-java/pull/1236 landed 🎉 

Are we good to close here @kmadsen?

**Comment by kmadsen** [comment]
Am optimizing, refactoring, verifying the releases. 

Sorry for the noise here, but these are the pull requests https://github.com/mapbox/mapbox-java/pull/1233 https://github.com/mapbox/mapbox-java/pull/1236 https://github.com/mapbox/mapbox-java/pull/1237 https://github.com/mapbox/mapbox-java/pull/1239

Discovering better ways to test our integrations locally.

**Comment by kmadsen** [comment]
🎉  Yay automatic publishing in place!

https://app.circleci.com/pipelines/github/mapbox/mapbox-java/384/workflows/a1bee6de-4c24-4b72-89f8-e6a688d1eb22/jobs/4851

Every commit publishes a snapshot
Every v* release tag published a release
