### ISSUE TITLE
Turn-by-Turn instructions

### ISSUE THREAD

**Issue by niiapa** [mapbox/mapbox-java#125]
Hello, this isn't really an issues but I did not know where I could post it. I've been searching for an example/tutorial/sample code for turn-by-turn directions using Mapbox on Android and I can't seem to find any pages on this. At this point, I'm not sure if it's completely possible (I'm assuming it is). My goal is to provide turn-by-turn directions in speech (voice). Thanks.

Edit: Using V5

**Comment by cammace** [comment]
Hey @niiapa, thanks for reaching out today and your interest in Mapbox Android Services. The best solution for now is to use directions V5 and within your request flag `.setSteps(true)` which will return the directions. You then can use an external voice library. I'd like to point out that we are working on adding Navigation to this SDK which will make integrating of turn by turn directions much easier. For future support questions, I'd recommend using our [contact page](mapbox.com/contact). Hope this helps!
