### ISSUE TITLE
Matching API

### ISSUE THREAD

**Issue by hussenIbrahim** [mapbox/mapbox-java#1256]
Hi
I am using matching API to match some points, but the result is wrong.
this is the request
https://api.mapbox.com/matching/v5/mapbox/driving/43.984533,36.14840;44.151425,36.309043;44.151425,36.309043?geometries=geojson&access_token=ACCESS_TOKEN

**Comment by geografa** [comment]
Distances between waypoints should be no more than 5000 meters. Please refer to the API documentation on the proper use and syntax for the Map Matching API (e.g. correct order of coordinates): 
- https://docs.mapbox.com/api/navigation/map-matching/
- https://docs.mapbox.com/help/tutorials/get-started-map-matching-api/
