### ISSUE TITLE
Optional parameters for the mapbox/driving profile missing?

### ISSUE THREAD

**Issue by bhoogter** [mapbox/mapbox-java#1258]
We would like to use the "Optional parameters for the mapbox/driving profile", as specified by the online documentation listed here:

> https://docs.mapbox.com/api/navigation/directions/#optional-parameters-for-the-mapboxdriving-profile

I cannot find these options in the Java SDK here.  Are these supported?  Is there a way to specify `depart_at` or `arrive_by` via the SDK?

**Comment by LukasPaczos** [comment]
Hey @bhoogter, this is moving in https://github.com/mapbox/mapbox-java/pull/1187. This got slowed down by unrelated factors but will be available in the future.

**Comment by LukasPaczos** [comment]
Resolved in https://github.com/mapbox/mapbox-java/pull/1265 and will be available in the upcoming release.
