### ISSUE TITLE
Use `RouteOptions` in `MapboxDirections` and ensure they are always set

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-java#1262]
[`MapboxDirections`](https://github.com/mapbox/mapbox-java/blob/main/services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java) expose a set of options that reflects the options exposed by the [Directions API](https://docs.mapbox.com/api/navigation/directions/) and are used to set request parameters.

That exact list of options is also copied and stored in [`RouteOptions`](https://github.com/mapbox/mapbox-java/blob/main/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java). This object is later [stored in the `DirectionsRoute`](https://github.com/mapbox/mapbox-java/blob/d7dc8cd86ef5a215d96c378fdfa3789f9caa77ce/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java#L123) so that we can tell what request parameters were used for that particular route and reuse them if we need to make a reroute request or mutate the original request in any other way. `RouteOptions` actually provide even more utility with some builder methods overloads.

This means that if someone uses `mapbox-java` library, they interact with `MapboxDirections` to create request parameters, but if they use the Navigation SDK, they interact with `RouteOptions` instead that [the Navigation SDK later maps to `MapboxDirections`](https://github.com/mapbox/mapbox-navigation-android/blob/v2.0.0-beta.12/libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/router/MapboxDirectionsUtils.kt). Navigation SDK couldn't accept the whole `MapboxDirections` object as a parameter for API ergonomics and dependency management reasons.

I'd like to propose:
1. Removing the public methods from `MapboxDirections` in favor of a simple `MapboxDirecions#setRouteOptions`. This cleans up the API and removes the need for Navigation SDK mappings that require additional maintenance, **additional releases of the Navigation SDK to actually be respected**, and test coverage.
2. Refactoring the `DirectionsResponse#fromJson` and `DirectionsRoute#fromJson` to require an instance of the `RouteOptions` to be provided when deserializing the object. Since `RouteOptions` are necessary for the Navigation SDK to operate correctly, they should be set by developers that request a route by other means, outside of the `mapbox-java` library (for example with `cURL` and then deserializing into object-oriented routes).

There are more considerations when it comes to the Directions API schema actually containing all the requested parameters (or at least waypoints) in the response, but that's currently out of the scope of this discussion and the tools we have available.

cc @mapbox/navigation-android @1ec5

**Comment by kmadsen** [comment]
I'm in favor of a refactor here. `RouteOptions` should be able to create `MapboxDirections` requests. I specificically found myself wanting to move the [MapboxDirectionsUtils](https://github.com/mapbox/mapbox-navigation-android/blob/main/libnavigation-router/src/main/java/com/mapbox/navigation/route/offboard/router/MapboxDirectionsUtils.kt) into mapbox-java. 

One of the reasons, is it would be nice to serialize<=>deserialize the `MapboxDirections` requests in order to save make requests using a file https://github.com/mapbox/navigation-sdks/issues/639

> Refactoring the DirectionsResponse#fromJson and DirectionsRoute#fromJson to require an instance of the RouteOptions

Any reason we should not make RouteOptions optional? I think the `DirectionsRoute` should be able to parse directions api responses without requiring us to build the RouteOptions. Otherwise we'll also need a nice way to convert direction urls into `RouteOptions`

I was also running into these issues while building instrumentation tests for https://github.com/mapbox/mapbox-navigation-android/pull/4375

**Comment by LukasPaczos** [comment]
> Any reason we should not make RouteOptions optional?

The reason is mentioned above:
> [RouteOptions] is later stored in the DirectionsRoute so that we can tell what request parameters were used for that particular route and reuse them if we need to make a reroute request

This is critical for reroute when "silent waypoints" (waypoints that do not describe the leg's end) were used. The response does not contain that information and we wouldn't be able to effectively reroute without it, we would lose the detail of the initial route. That said, there are threads with the API team to make this part of the schema in the future.

> Otherwise we'll also need a nice way to convert direction urls into RouteOptions

That's a good idea! We can implement a `RouteOptions#fromUrl` :+1:

**Comment by kmadsen** [comment]
> > Any reason we should not make RouteOptions optional?

> The reason is mentioned above:

> There are more considerations when it comes to the Directions API schema actually containing all the requested parameters (or at least waypoints) in the response, but that's currently out of the scope of this discussion and the tools we have available.

Ok, am clarifying because it seems we're disregarding the Directions API schema as out of scope and then _forcing_ specific usage. A reasonable approach could be, to require the `RouteOptions` in the `DirectionsResponse`. Because that is indeed the `MapboxDirections` interface. Adding the requirement is confusing, it seems to require domain understanding of the NavigationSDK

``` java
class MapboxDirections {
  void setRouteOptions(RouteOptions routeOptions)
  Call<DirectionsResponse> initializeCall() 
}
```

**Comment by LukasPaczos** [comment]
> we're disregarding the Directions API schema as out of scope and then forcing specific usage

We're not disregarding the schema, we're packaging more information on top of what is already in the schema. In general, a schema is, unfortunately, an overstatement in this case because we need to do a fair share of interpretation from docs rather than using a defined format. We've been also discussing a protobuf or code generation from a proper JSON schema but this is to come in the future.

> Adding the requirement to DirectionsRoute feels confusing, it seems to require domain understanding of the NavigationSDK

Right, this isn't currently ideal, but our SDKs are designed to work with a `route` not a `route response`, that's why the request options need to be pushed as far down as the route so that we can support proper rerouting. We ultimately don't care, nor we should, about where the route is coming from. This has been another point of discussion and we were thinking about pushing waypoints data down to legs which would make things more consistent.

For the implementation itself, we'll have:
```kotlin
val options = RouteOptions.Builder()
    .baseUrl("...")
    .user("...")
    .profile("...")
    ...
    .build()
MapboxDirections.builder()
    .routeOptions(options)
    ...
    .build()
```
instead of the current:
```kotlin
MapboxDirections.builder()
    .baseUrl("...")
    .user("...")
    .profile("...")
    ...
    .build()
```

The necessary knowledge to execute a request doesn't change, just the formatting of it. Passing the options to legs will happen under the hood as it does now. 

cc @dersim-davaod

**Comment by kmadsen** [comment]
👍

Most of the proposal sounds good! Especially like adding the `RouteOptions` to `MapboxDirections`, great idea. Love the new simpler implementation with passing route options to the `MapboxDirections`. 

> Refactoring the DirectionsResponse#fromJson and DirectionsRoute#fromJson to require an instance of the RouteOptions 

I'm specifically surfacing the issues I can think of when adding the _requirement_ here. This would mean that anything that takes a Directions API response and tries use mapbox-java will fail? That would fail the [DirectionsResponseValidator](https://github.com/mapbox/mapbox-java/blob/main/services-cli/src/main/kotlin/com/mapbox/services/cli/validator/DirectionsResponseValidator.kt) because the [route options are not in the test json](https://github.com/mapbox/mapbox-java/blob/main/services-cli/src/test/resources/directions_v5.json). So I think `RouteOptions#fromUrl` is a requirement with this part of the proposal - so maybe we break it up into two deliverables.

> We ultimately don't care, nor we should, about where the route is coming from. This has been another point of discussion and we were thinking about pushing waypoints data down to legs which would make things more consistent.

mapbox-java is designed to only take routes from mapbox directions api. the NavigationSDK does not care where the route comes from. In these cases, i've seen a new objects be proposed. `NavigationRoute` for example, which can be mapped from a directions api response. It seems like that could be an alternative for the #2 part of this (not the #1 part)

**Comment by LukasPaczos** [comment]
> I'm specifically surfacing the issues I can think of when adding the requirement here.

The problem is, that this is already a requirement, just that currently it's implicit. When interacting with the Navigation SDK, you have to provide `RouteOptions` because there's the information mentioned above (waypoints, bearings, approaches, etc) needed that we cannot obtain just from the directions response. Until (and if) we update the schema, which won't happen before the Nav SDK v2 goes stable, we'll have to work with what we've got.

Currently, when you deserialize the response manually when using it with the Nav SDK, you should actually do:
```kotlin
val url = "..."
val response = "..."
val routeOptions = RouteOptions.builder()
    ...
    .build()
val routes = DirectionsResponse.fromJson(response).routes().map {
    it.toBuilder().routeOptions(routeOptions).build()
}
```

`#2` is proposing formalizing this dependency instead of surprising developers that things don't work:
```kotlin
val url = "..."
val response = "..."
val routeOptions = RouteOptions.fromUrl(url)
val routes = DirectionsResponse.fromJson(json, routeOptions).routes()
```

#### Alternative proposal `#2`
I think I understand your concern though - we would be imposing a requirement for `mapbox-java` that's driven solely by the Nav SDK which isn't ideal.

In order to not impact consumers of `mapbox-java` that don't use it as part of the Nav SDK input, we could make the `RouteOptions` argument for `fromJson` methods optional and document that it's needed for interaction with the Nav SDK but otherwise optional:
```java
public static DirectionsResponse fromJson(@NonNnull String json) {
    return fromJson(json, null)
}

public static DirectionsResponse fromJson(@NonNnull String json, @Nullable RouteOptions options) {
    ...
}
```

As part of a parallel effort, I'm planning to add runtime checks to the Nav SDK that would throw an exception when `RouteOptions` are not initialized. If they are not provided while used with the Nav SDK, we'd report that right away and developers would have a straightforward path to address the problem. What do you think?

#### `NavigationRoute`
> In these cases, i've seen new objects proposed. `NavigationRoute` for example, could have these assumptions baked in.

This is interesting, and could actually live inside of the Navigation SDK. However, `NavigationRoute` could not extend the current `DirectionsRoute` because there's no possibility to extend the generated `@AutoValue` classes, we'd have to copy all the fields and maintain 2 nearly equal implementations. Going as far as refactoring the whole library and removing `AutoValue` might is probably going too far for now. Let's see if we can get an update to the scheme first, and refactor then (hopefully with code generation). Also, the necessary information (waypoints, bearings, approaches, etc) could at some point get baked into the Directions API v5 schema itself which would render the `NavigationRoute` redundant. By baking the information into the current `DirectionsRoute` we give ourselves the backdoor to deprecate it at some point (and remove the Nav SDK runtime check) and just use the information from the schema, without any additional breaking changes.

**Comment by kmadsen** [comment]
> In order to not impact consumers of mapbox-java that don't use it as part of the Nav SDK input, we could make the RouteOptions argument for fromJson methods optional and document that it's needed for interaction with the Nav SDK but otherwise optional:
> As part of a parallel effort, I'm planning to add runtime checks to the Nav SDK that would throw an exception when RouteOptions are not initialized. If they are not provided while used with the Nav SDK, we'd report that right away and developers would have a straightforward path to address the problem. What do you think?

Thanks for understanding and digging into ideas. Continuing to support the `DirectionsResponseValidator` and the directions api case sounds good. Run time checks in the nav sdk also sound good 👍 

> but our SDKs are designed to work with a route not a route response

^ i think this is a problem worth considering,  in the NavigationSDK that is the reason we are considering a change to the mapbox-java definition. It's not like we save the `RouteOptions` to every `RouteLeg`. And we define `alternatives` in the `RouteOptions`, but then you can't find the alternatives in a `DirectionsRoute`. [it was added 4 years ago in a different world](https://github.com/mapbox/mapbox-java/commit/62b6d84be7a39c3d54fcccdc03194bfaece2c84d) so maybe it is the problem.

I like making `RouteOptions` as a property that is _always there_. I have been looking for a "single navigation scenario" configuration, and that appears to be a good one. Am building on top of the idea here https://github.com/mapbox/navigation-sdks/issues/1012

**Comment by LukasPaczos** [comment]
> It's not like we save the `RouteOptions` to every `RouteLeg`. And we define `alternatives` in the `RouteOptions`, but then you can't find the alternatives in a DirectionsRoute. it was added 4 years ago in a different world so maybe it is the problem.

There's definitely a lot of history and debt here. I'm sure we can do better but I'm trying to avoid re-engineering things that should be fixed upstream with a refined schema. We'd just introduce a new workaround that costs us a lot of breaking changes. It would clean up the API but ultimately would still be a workaround.

I feel like we have a consensus though:
1. Conflate `MapboxDirections` request params into `RouteOptions` and expose `MapboxDirections.Builder#routeOptions(options)`.
2. Expose `public static DirectionsResponse fromJson(@NonNnull String json, @Nullable RouteOptions options)`
3. Add runtime checks to the Nav SDK to verify that `RouteOptions` are present.

If there are no concerns, I'll take a stab at this in the next couple of days.

**Comment by Guardiola31337** [comment]
As this would imply SemVer we should also think about how to support https://github.com/mapbox/mapbox-navigation-android/issues/4376

**Comment by kmadsen** [comment]
Over communicating something else that is similar here. 

When mapping history files from native, into NavigationSDK domain. We have a similar case of mapping back and forth
https://github.com/mapbox/mapbox-navigation-android/pull/4488

We can re-create set route events using native history files. And the `ActiveGuidanceOptions` are very similar (but not exactly the same) as `RouteOptions`.
