### ISSUE TITLE
Expose include-hov/hot params in `RouteOptions`

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-java#1293]
> We already have `exclude` parameters, e.g., `exclude=toll`.  These parameters can be thought of as, "we will route onto tolls by default; to avoid tolls you have to opt-out using `exclude=toll`".
>
> For hov/hot I'm proposing a new `include` key with these possible values:
>`include=hov2`
>`include=hov3`
>`include=hot`
>
> These parameters can be thought of as, "we will avoid routing onto hov/hot by default; if you want to route onto hov/hot you have to opt-in using `include=hov/hot`".

cc @browndp08 @ktatterso @kelseylivingston @zugaldia

**Comment by Guardiola31337** [comment]
cc'ing @1ec5 for visibility on the iOS side

**Comment by 1ec5** [comment]
mapbox/mapbox-directions-swift#592 tracks the corresponding changes in Swift.
