### ISSUE TITLE
Goecoding autocomplete widget should expose bounding box

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#130]
Now that `setBbox();` is exposed in the geocoder in #89, users should be able to set a bounding box using the Android autocomplete widget. We should also make sure all other available options are exposed.

cc: @zugaldia

**Comment by zugaldia** [comment]
Good catch. We should benefit from the `autocomplete` request param.

**Comment by zugaldia** [comment]
https://github.com/mapbox/mapbox-java/issues/133 addresses both params.
