### ISSUE TITLE
add `ignore` parameter to Map Matching API service

### ISSUE THREAD

**Issue by geografa** [mapbox/mapbox-java#1304]
The Map Matching API service is missing the [ignore parameter](https://docs.mapbox.com/api/navigation/map-matching/). 
> Ignore certain routing restrictions when map matching. You can include several ignore options as a comma-separated list (for example, ignore=access,oneways,restrictions).Possible valuesDescriptionaccessIgnore access restrictions related to mode of travel.onewaysIgnore one-way restrictions.restrictionsIgnore other restrictions, such as time-based or turn restrictions. This option is only available for the mapbox/driving profile. 

Adding the parameter will be helpful for use-cases such as allowing permitted vehicles in taxi or transit only roadways.

**Comment by zugaldia** [comment]
There's increasing customer interest in this feature, let's prioritize this work. I'll update our board accordingly.

**Comment by zainperacha** [comment]
Hey, is there any update on this issue.

Ref: Shotl, Swvl.

**Comment by zainperacha** [comment]
@Daniel ***@***.***>

Could you loop in the relevant engineering folks to validate if this change landing will resolve our positive restrictions requirement?
________________________________
