### ISSUE TITLE
Add DirectionsCriteria to exclude unpaved roads

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-java#1308]
The Directions API’s mapbox/driving and mapbox/driving-traffic profiles now support an `exclude=unpaved` parameter. We should add an `EXCLUDE_UNPAVED` constant to the `DirectionsCriteria` class.

/cc @mapbox/navigation-android @ktatterso

**Comment by LukasPaczos** [comment]
Land in https://github.com/mapbox/mapbox-java/pull/1327.

**Comment by VysotskiVadim** [comment]
Tested on the mapbox-java `6.2.0-SNAPSHOT`. Directions API doesn't fail when I use `DirectionsCriteria.EXCLUDE_UNPAVED` from an example Android app.
