### ISSUE TITLE
Add DirectionsCriteria to exclude toll roads that only accept cash payment

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-java#1309]
The Directions API now supports an `exclude=cash_only_tolls` parameter, regardless of routing profile. We should add an `EXCLUDE_CASH_ONLY_TOLLS` constant to the `DirectionsCriteria` class.

/cc @mapbox/navigation-android @ktatterso

**Comment by LukasPaczos** [comment]
Land in https://github.com/mapbox/mapbox-java/pull/1327.

**Comment by VysotskiVadim** [comment]
Tested on the mapbox-java `6.2.0-SNAPSHOT`. Directions API doesn't fail when I use `DirectionsCriteria.EXCLUDE_CASH_ONLY_TOLLS` from an example Android app.
