### ISSUE TITLE
Setup services for styles API

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-java#1316]
As an effort to introduce the new Mapbox designed route shields, Navigation SDK needs to make following 2 API calls to `styles` endpoint in order to retrieve the blank route shield and placeholder values for positioning the text on top of the shield. 

##### Request a shield:
```
https://api.mapbox.com/styles/v1/:ownerId/:styleId/draft?/sprite/:imageId
```

##### Request text placeholders:
```
https://api.mapbox.com/styles/v1/:ownerId/:styleId/:revision?/sprite(:pixelRatio?).json
```

In order to add these services to this repository there are 2 options:
- Add a new module `services-shields / services-styles`
- Use an existing module to host these new services; probably `services-directions`

I am leaning more towards the 1st option as it clearly states the purpose of this new module and services which kind of doesn't make sense to add it to the `services-directions` or any other module.

I would like to know your thoughts or any other suggestions

cc @mapbox/navigation-android

**Comment by zugaldia** [comment]
I agree that a new `services-styles` makes more sense here.

**Comment by abhishek1508** [comment]
More details on the use case are as follows:

```
https://api.mapbox.com/styles/v1/:ownerId/:styleId/:revision?/sprite(:pixelRatio?).json
```
The request above needs to be made every time there is a change in the map style[eg: style change from light to dark mode, street to satellite mode]. This particular request returns a set of all the shields available and would be favorable to not make this request every time there is a style change. Rather, it would be ideal to cache the request/response and only hit the network when the data becomes stale.

```
https://api.mapbox.com/styles/v1/:ownerId/:styleId/draft?/sprite/:imageId
```
The request above results in a black shield image as shown below
![Screen Shot 2021-08-25 at 10 24 59 AM](https://user-images.githubusercontent.com/1590802/130837200-9ae83f94-de4f-41f4-b3e8-84c6a6238d9a.png) ![Screen Shot 2021-08-25 at 10 27 08 AM](https://user-images.githubusercontent.com/1590802/130837278-f872b43d-2724-4474-877a-a4aae9c25368.png)

It would be ideal to cache these blank shields as they are unlikely to change in real world scenarios and the shields can be cached for a longer period of time ranging from months to an year.

Both these endpoints can be queried for using:
- MapboxJava services
- Common SDK httpclient

Looking at the above caching needs, I propose we use common sdk to make the network calls directly from the Nav SDK without making any additions/modifications to MapboxJava. Downside to using common sdk is that as a response to any network request it only returns a byteArray containing the json response, which we would then have to parse in the SDK, whereas we get it for free using `TypeAdapter` in `MapboxJava`. However, parsing json is not that big of a time consuming task in this context and we should be able to accept it as a tradeoff to leverage caching from Common SDK.

cc @LukasPaczos @Guardiola31337

**Comment by LukasPaczos** [comment]
> I propose we use common sdk to make the network calls directly from the Nav SDK

Agreed with this :+1: What we might want to consider is still adding the `services-shields / services-styles` to `mapbox-java` to expose data models and handle parsing, but make requests from Nav SDK. Similarly, as `mapbox-java` is used for directions requests now - we leverage only the models while actual request is made internally in the Nav SDK.

**Comment by abhishek1508** [comment]
Since we don't need to make network requests using MapboxJava, we don't need to create any services targeting the styles endpoint. Hence, I don't think we probably need any new module in this case. We can just add files in `services-directions-models` to handle parsing.

##### Sample request which needs parsing
- https://api.mapbox.com/styles/v1/driverapp/ckw6z9kkd12sm14pire2bc1zb/draft/sprite.json?access_token=driverapptoken
- https://api.mapbox.com/styles/v1/driverapp/ckw6z9kkd12sm14pire2bc1zb/sprite/rectangle-yellow-2?access_token=driverapptoken

where `driverapptoken` is the access token from driver app account

/cc @LukasPaczos @Guardiola31337 @mapbox/navigation-android
