### ISSUE TITLE
Add position methods to Turf

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#138]
Some of the Turf APIs we expose have methods that take in position values which makes it easier on developers instead of having to convert Position to Points first. We should make sure all Turf APIs include this functionality.

cc: @zugaldia

**Comment by zugaldia** [comment]
@cammace Another option is to have `Point.toPosition()` and `Position.toPoint()` utility methods. What do you think?

**Comment by cammace** [comment]
Currently `Point.fromCoordinates()` can be used to convert position to point but switching to `Position.toPoint()` makes more sense to me. Same case doing the reverse, switching from Point to Position currently can be done doing `Point.getCoordinates()` but would make more sense to call it `Point.toPosition()` since this is what you are doing.

In any case this works, I just wanted to make sure all the Turf methods have methods like the [TurfJoins.inside()](https://github.com/mapbox/mapbox-java/blob/master/libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfJoins.java#L31) to easily pass in Positions.

**Comment by zugaldia** [comment]
> switching to Position.toPoint() makes more sense to me

Noting that after the recent refactor https://github.com/mapbox/mapbox-java/pull/251, `Position` doesn't see the GeoJSON package, while the opposite is true.

**Comment by cammace** [comment]
I think we are safe closing this issue. With the recent refactor work, this doesn't make much sense to do anymore.
