### ISSUE TITLE
Reverse geocoding issues in Malta 

### ISSUE THREAD

**Issue by fobo66** [mapbox/mapbox-java#1381]
Hi! I'm using Java SDK to reverse geocode places in our Android app selected from the map. I've noticed that reverse geocoding of the coordinates from Malta produces at most only postcode results and no addresses. Although it can also be reproduced in the [playground](https://docs.mapbox.com/playground/geocoding/?search_text=14.468677125693802,35.8796954033881&limit=1). Last month it was loading addresses correctly, but now only postcodes at most. 

Here's the response from the playground (I'm getting the same in the SDK):

```json
{
  "type": "FeatureCollection",
  "query": [14.46132726853125, 35.87747478276877],
  "features": [
    {
      "id": "postcode.13570053323186520",
      "type": "Feature",
      "place_type": ["postcode"],
      "relevance": 1,
      "properties": {},
      "text": "QRM",
      "place_name": "QRM, Ħal Qormi, Qormi, Malta",
      "bbox": [14.450586, 35.862435, 14.485113, 35.890889],
      "center": [14.471261, 35.879804],
      "geometry": {"type": "Point", "coordinates": [14.471261, 35.879804]},
      "context": [
        {
          "id": "place.13474353478894160",
          "wikidata": "Q39578",
          "text": "Ħal Qormi"
        },
        {
          "id": "region.10206553194517090",
          "short_code": "MT-43",
          "wikidata": "Q39578",
          "text": "Qormi"
        },
        {
          "id": "country.5289496962302500",
          "wikidata": "Q233",
          "short_code": "mt",
          "text": "Malta"
        }
      ]
    }
  ],
  "attribution": "NOTICE: © 2022 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained. POI(s) provided by Foursquare."
}
```

I'm using SDK version 5.8.0

I would be glad if you can direct me to the correct place to report this or provide some insights on what's going on here

**Comment by Guardiola31337** [comment]
As noted in the docs https://docs.mapbox.com/android/java/guides/geocoder/ we're recommending to not rely on Mapbox Java Geocoder and use the Mapbox Search SDK instead.

> [The Mapbox Search SDK for Android](https://docs.mapbox.com/android/search/guides/) is the recommended way to access the [Mapbox Geocoding API](https://docs.mapbox.com/api/search/geocoding/) on the Android platform. If you've used `Geocoder` to integrate search functionality into an Android application, you should switch to Search SDK using the [Migrate from Geocoder](https://docs.mapbox.com/android/search/guides/geocoder-migration/) guide.

Have you tried that? If not, could you try that out? Please let us know if you still run into similar results.

cc @kalbaxa @DzmitryFomchyn

**Comment by ilissablech** [comment]
@fobo66 We do not have address coverage in Malta. if you update the type list to include only addresses you’ll see we return no results. It's interesting that last month it was loading addresses correctly, as we’ve never had addresses for Malta… Do you have a way to show any history of these addresses for me to look into?

cc @DzmitryFomchyn @SiarheiFedartsou

**Comment by fobo66** [comment]
> Have you tried that? If not, could you try that out? Please let us know if you still run into similar results.

@Guardiola31337 Search SDK didn't work for us: I was able to set up the private repo, but API seems to differ from what I can see in docs, and I already spent too much time on it, so I decided not to continue the struggle.

**Comment by fobo66** [comment]
> We do not have address coverage in Malta. if you update the type list to include only addresses you’ll see we return no results. It's interesting that last month it was loading addresses correctly, as we’ve never had addresses for Malta… Do you have a way to show any history of these addresses for me to look into?

@ilissablech In [docs](https://docs.mapbox.com/help/getting-started/mapbox-data/) I can see that Malta has "basic data quality" for address. That matches with our experience before: I cannot dig out what were the responses we were getting, but from what I remember we've seen at least some street names and localities, without house numbers

**Comment by kalbaxa** [comment]
> Search SDK didn't work for us: I was able to set up the private repo, but API seems to differ from what I can see in docs, and I already spent too much time on it, so I decided not to continue the struggle.

@fobo66 thanks for providing this feedback! We've recently improved the docs and made the repo public https://github.com/mapbox/mapbox-search-android. I encourage you to try it out and file specific issues for what's not working / difficult to set up. That would be very helpful for us to improve.

**Comment by ilissablech** [comment]
@fobo66 which customer is this for?

**Comment by Guardiola31337** [comment]
@fobo66 @kalbaxa are we good to close here then? Feel free to do that if you think so 🙇‍♂️
