### ISSUE TITLE
Add traffic control device flags to Intersection

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-java#1438]
The Directions API now [includes](https://docs.mapbox.com/api/navigation/directions/#route-step-object) new Boolean-typed properties in intersection objects that indicate which traffic control devices are present at the intersection.

* ~`railway_crossing`~
* `traffic_signal`
* `stop_sign`
* `yield_sign`

ios ticket: https://github.com/mapbox/mapbox-directions-swift/issues/686

**Comment by abhishek1508** [comment]
It was already exposed [here](https://github.com/mapbox/mapbox-java/pull/1464). Closing as completed
