### ISSUE TITLE
Add turf.buffer example to the Test App

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#146]
We hear from @morganherlocker that `turf.buffer` uses `jsts` under the hood which is in turn a port of the [JTS](http://www.vividsolutions.com/jts/JTSHome.htm) Java library:

> Re: buffers. GEOS' buffer is functionally equivalent to turf's (really JSTS') implementation. They are both ports of JTS (Java); JSTS being JavaScript and GEOS being C++. These might be easier to work with on Android and iOS.

We don't want to add JTS as a dependency of MAS (at least not yet) because it'll likely bring a large number of methods with it, which is something we want to avoid on Android because of the 64K methods limit.

However, we could bring JTS to the Test App and show how to use its buffer functionality to developers. We'd want to mimic the `turf.buffer` API when building the example, i.e.: `TurfTransformation.buffer(Feature feature, double radius, String units)`.

/cc: @cammace

**Comment by vanshg** [comment]
I'm working on a project where this would be nice to have (the turf buffer method). +1

**Comment by zugaldia** [comment]
@vanshg Glad to hear and thank you for the feedback. Meanwhile you'd like to have a look at [JTS](http://www.vividsolutions.com/jts/JTSHome.htm). When we implement `turf.buffer` we might end up using it under the hood.

**Comment by zugaldia** [comment]
Another option would be to bring JSTS as an [optional dependency](https://blog.gradle.org/introducing-compile-only-dependencies) and let the developer decide whether to include it in their projects or not.

**Comment by cammace** [comment]
JTS looks like a great library which serves the purpose of Turf Buffer, is this ticket suggesting we just wrap the API provided in the JTS library, or are we looking to just add an example to the testapp? If the latter, the example would probably do better inside the Demo App?

**Comment by zugaldia** [comment]
>  is this ticket suggesting we just wrap the API provided in the JTS library, or are we looking to just add an example

The latter, we don't want to force that dependency on developers unless we make it an optional one.

**Comment by cammace** [comment]
Moving this ticket to the demo app repo https://github.com/mapbox/mapbox-android-demo/issues/515
