### ISSUE TITLE
404 errors

### ISSUE THREAD

**Issue by nigelhorne** [mapbox/mapbox-java#1460]
I've started to get 404 errors trying to access https://raw.githubusercontent.com/mapbox/geocoder-abbreviations/master/tokens/en.json

**Comment by LukasPaczos** [comment]
Hey @nigelhorne, the abbreviations are available in https://www.npmjs.com/package/@mapbox/geocoder-abbreviations. I'm not sure why the JSON was hosted separately on GitHub but it doesn't look intentional.
