### ISSUE TITLE
Support `traffic signals`, `yield signs` and `stop signs` as a part of navigator `RoadObjectType`

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-java#1462]
Directions API are now supporting `traffic_signal`, `yield_sign` and `stop_sign` as a part of `StepIntersections` as can be seen in the documentation
<img width="671" alt="Screen Shot 2022-07-15 at 9 45 28 AM" src="https://user-images.githubusercontent.com/9770186/179270522-61ca4871-3b77-4101-811a-32b3877ec666.png">

`DirectionsRoute` should expose these road objects as a part of `StepIntersection`.

/cc @mapbox/navigation-android

**Comment by RingerJK** [comment]
ref https://docs.mapbox.com/api/navigation/directions/#route-step-object
