### ISSUE TITLE
Allow the standalone use of the geocoding model objects

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#148]
Opening this ticket to discuss the issue we are currently having updating to the latest version of MAS and correct me if I'm wrong @bleege. Previously we have been saving search history like so:

```java
public GeocodingFeature adaptTo() {
        GeocodingFeature feature = new GeocodingFeature();
        feature.setText(key);
        feature.setPlaceName(key);

        FeatureGeometry geometry = new FeatureGeometry();
        List<Double> coordinates = new ArrayList<>();
        coordinates.add(longitude);
        coordinates.add(latitude);
        geometry.setCoordinates(coordinates);

        feature.setGeometry(geometry);
        return feature;
    }
```
With the latest MAS release, `1.2.1` the data model is setup so that it can only be worked with through GSON and not as standalone objects making the above code not work anymore. Some options here would be to just add the models in the app and use them instead of the ones found in MAS or make the ones in MAS usable. 

cc: @zugaldia @bleege

**Comment by zugaldia** [comment]
> Some options here would be to just add the models in the app and use them instead of the ones found in MAS

I'd rather change MAS to support this kind of behavior 👍 .

**Comment by bleege** [comment]
@cammace Yep, that's accurate.  Thanks for extending the MAS model @zugaldia!
