### ISSUE TITLE
Make it easier to use wikidata

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#150]
The geocoding API now gives wikidata identifiers which in `1.2` of MAS can be retrieved in the  CarmenContext class using `getWikidata()`. We should instead have a method called `getWikidataId()` which gives the ID and `getWikidata()` which can actually fetch the wikidata information. An example for getting the description could be:
```java
getWikidata().language("en").getDescription();
```

The current soultuion for getting wikidata in an app would be using an external library such as [Wikidata-Toolkit](https://github.com/Wikidata/Wikidata-Toolkit).

cc: @zugaldia

**Comment by cammace** [comment]
On second thought, i'm thinking that if a user needs to get wikipedia information, they should use a separate library. What do you think @zugaldia?

**Comment by zugaldia** [comment]
@cammace 👍
