### ISSUE TITLE
Convenient methods for geocoder response properties

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#156]
The geocoder offers telephone numbers, maki icon suggestions, wikidata, address, and category depending on the geocoder filter search. To access these currently you have to do something like this in your app:

```java
if(feature.getProperties().has("tel")) {
    String phone = feature.getProperties().get("tel").getAsString();
}
```

But this doesn't check if the value's null ([more info here](https://github.com/mapbox/sirius-android/issues/329)). We should expose methods that make accessing these elements easier and gives this feature more exposure in the SDK.

cc: @zugaldia

**Comment by zugaldia** [comment]
While agree with this, it's difficult to decide which fields to expose. According to the [docs](https://www.mapbox.com/api-documentation/#response-format):

> The {properties} property of the feature is unstable: only what is specified in Carmen GeoJSON is part of the stable API.

And the Carmen [spec](https://github.com/mapbox/carmen/blob/master/carmen-geojson.md) says:

> Carmen makes no specifications nor guarantees about the properties of each feature object. Feature properties are passed directly from indexes and may vary by feature and datasource.

At the same time, some of the fields you mention are already available in [`CarmenContext`](https://github.com/mapbox/mapbox-java/blob/master/libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/models/CarmenContext.java).

Another approach could be to expose a convenience method called `feature.getProperty("tel")` that basically simplifies `feature.getProperties().get("tel").getAsString();` together with the proper checks for `null` values.

**Comment by incanus** [comment]
I'm for @zugaldia's second suggestion of just wrapping/abstracting as well as making safe `null` checks. Could return an empty string, then check for that in the calling code if we ever want a conditional around, say, displaying a phone number line in a view.

**Comment by incanus** [comment]
Possibly dumb Java question here, but should I use reflection to get at members such as `text`, `address`, etc., or create a `HashMap` instead and move the members to that for easy retrieval by such a `getProperties()`?

**Comment by bleege** [comment]
I'd recommend avoiding reflection as it is a very costly operation in Java.  What may make sense is to use Java 8s Optional type or roll are own optional getter methods assuming the potential properties are all known a head of time.

**Comment by zugaldia** [comment]
@incanus Yeah, I don't see a need for reflection here. The challenge here is that not only we don't have guaranteed fields according to the standard, but also, each property in the `JsonObject` can have a different type. For now, the way we've solved it is to expose a number of generic methods (`getStringProperty()`, `getNumberProperty()`, ...) in [`Feature`](https://github.com/mapbox/mapbox-java/blob/master/libjava/lib/src/main/java/com/mapbox/services/commons/geojson/Feature.java#L217) to make accessing those fields easier (still no `null` checks though).

**Comment by incanus** [comment]
What I'm not grasping (and sorry, this is like Java 101 stuff here) is that `CarmenFeature` doesn't have properties (other than the ones it inherits from `Feature`), but instead members such as `text`, `placeName`, and `address`. Should we instead move those to the properties object?

**Comment by incanus** [comment]
Discussed with @zugaldia. The clarification point here is that we are only querying fields already in the `Feature`-inherited `properties`.
