### ISSUE TITLE
map matching criteria

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#163]
When setting the map matching profile, we currently push users to use `DirectionsCriteria.PROFILE_DRIVING` which is from the direction v4 package. Android studio by default wants to import the more recent v5 directions criteria object. This causes map matching to fail. In addition we plan to deprecate v4 in the future. Therefore, we should create a `MapMatchingCriteria` object that contains the correct profiles, making it easier on the user to import the correct package.

cc: @zugaldia

**Comment by zugaldia** [comment]
> When setting the map matching profile, we currently push users to use DirectionsCriteria.PROFILE_DRIVING which is from the direction v4 package

This is intended as currently Map Matching is following the syntax for `v4`, however I agree that we should expose a separate `MapMatchingCriteria` (even if it repeats constants) so that we can keep the deprecation tag on `v4` directions while not doing the same with Map Matching.
