### ISSUE TITLE
Check that direction response contains a route

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#166]
We are checking if the response is null and make the assumption that if the response isn't null we have at least 1 route which isn't accurate. We should add a check that makes sure the list is greater then 0.

https://github.com/mapbox/mapbox-java/blob/master/libandroid/app/src/main/java/com/mapbox/services/android/testapp/directions/DirectionsV5Activity.java#L121

cc: @zugaldia

**Comment by cammace** [comment]
While trying to find a route which causes this to happen so I could write a test, I found that every directions api call I made returned a route with at least blank fields, for example making this call:

```
https://api.mapbox.com/directions/v5/mapbox/walking/0.000,0.0000;0.0000,0.0000?access_token=pk.eyJ1IjoiZ2licmFuZ2F5dGFuIiwiYSI6ImNpcGZ1cXo4azAwMmJ0Y21qZXZkOWI1OXkifQ.Jn6vQJEv01QbxsHwpLcjXQ&geometries=polyline
```

will result in this output: 

```
{"routes":[{"legs":[{"steps":[],"summary":"","duration":0,"distance":0}],"geometry":"_sJurH??","duration":0,"distance":0}],"waypoints":[{"name":"Maron Lane","location":[0.049234,0.059515]},{"name":"Maron Lane","location":[0.049234,0.059515]}],"code":"Ok"}
```

the JsonArray has 1 object. Do you have a good example which has a `OK` response but no route so I can write this test?

**Comment by mghildiy** [comment]
Is this issue still open to work upon?

**Comment by cammace** [comment]
With 3.0, we intercept the API callback and check first if it was successful and whether or not the list of routes is empty. This check was originally meant for checking in some of our, now nonexisting testapp activities.
