### ISSUE TITLE
Verify compliance with RFC 7946 for GeoJson

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#177]
As @sgillies explains in [RFC 7946, The GeoJson Format](https://sgillies.net/2016/08/11/rfc-7946-the-geojson-format.html), GeoJSON is now an internet standard: RFC 7946.

There are a few changes in the spec and there are a few things that developers need to do to keep up. Let's make sure our GeoJson implementation follows all:
- [x] Coordinate reference systems are no longer in the core of the specification; use CRS84 longitude and latitude with GeoJSON from now on.
- [x] Don’t extend coordinate arrays with linear referencing measure, timestamps, or other variables.
- [ ] Follow the math and physics right-hand rule (not the surveyor’s right-hand rule) when forming polygon rings.
- [ ] Construct bounding boxes so they are not ambiguous at the Earth’s poles and antimeridian.
- [ ] Split geometries that cross the antimeridian into parts that do not cross it.
- [ ] Do extend GeoJSON, but don’t change its semantics.
- [ ] Don’t write longitude and latitude values with more than 7 decimal places of precision.
- [ ] Avoid using GeometryCollection when possible.
- [ ] Reference RFC 7946 from now on instead of http://geojson.org.

/cc: @cammace @ivovandongen

**Comment by cammace** [comment]
- [ ] Coordinate reference systems are no longer in the core of the specification; use CRS84 longitude and latitude with GeoJSON from now on.

[section 4](https://tools.ietf.org/html/rfc7946#section-4)

> The coordinate reference system for all GeoJSON coordinates is a geographic coordinate reference system, using the World Geodetic System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units of decimal degrees.  This is equivalent to the coordinate reference system identified by the Open Geospatial Consortium (OGC) URN urn:ogc:def:crs:OGC::CRS84.  An OPTIONAL third-position element SHALL be the height in meters above or below the WGS 84 reference ellipsoid.  In the absence of elevation values, applications sensitive to height or depth SHOULD interpret positions as being at local ground or sea level.

I don't see any conflicts with our `Position` object and this spec. Only thing might be that in the absence of elevation values, we return null.

- [ ] Don’t extend coordinate arrays with linear referencing measure, timestamps, or other variables.

When setting or getting GeoJSON coordinates in MAS, it is a `List<List<Position>>` with the Position object not allowing for extra variables

 - [ ] Follow the math and physics right-hand rule (not the surveyor’s right-hand rule) when forming polygon rings.

I don't think we enforce this currently, can you confirm @zugaldia?

- [ ] Construct bounding boxes so they are not ambiguous at the Earth’s poles and antimeridian.

Without looking into this, I imagine the same scenario occurs as a linestring, polygon, etc.

- [ ] Split geometries that cross the antimeridian into parts that do not cross it.

We don't have any checks for this currently. If I create a linestring that crosses the antimeridian, we aren't spliting it and therefore, wrapping occurs:

<img src="https://cloud.githubusercontent.com/assets/5652865/21728714/ae55e710-d415-11e6-8b91-360ba1f6ee4a.png" width=360/>

- [ ] Do extend GeoJSON, but don’t change its semantics.

[section 7.1](https://tools.ietf.org/html/rfc7946#section-7.1)
We should be all good here.

- [ ] Don’t write longitude and latitude values with more than 7 decimal places of precision.

No enforcement of this is being done in the `Position` object.

- [ ] Avoid using GeometryCollection when possible.

[section 3.1.8](https://tools.ietf.org/html/rfc7946#section-3.1.8)

**Comment by cammace** [comment]
I've ticketed out the individual things that need fixing for easier tracking. Closing in favor of these:

https://github.com/mapbox/mapbox-java/issues/263
https://github.com/mapbox/mapbox-java/issues/264
https://github.com/mapbox/mapbox-java/issues/265

> Don’t write longitude and latitude values with more than 7 decimal places of precision.

Proposed fix for this is in https://github.com/mapbox/mapbox-java/pull/259
