### ISSUE TITLE
Proguard update

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#178]
With the update to this SDK downstream, I'm hitting `com/mapbox/services` as a Proguard issue. We need to update the rules in `proguard-rules.pro` in this project. For now I will keep the whole package in the SDK downstream https://github.com/mapbox/mapbox-gl-native/issues/6077.

cc @cammace @zugaldia

**Comment by cammace** [comment]
reopening after a SNAPSHOT was built and tested using the testapp, we are still missing something in the ProGaurd rules

**Comment by tobrun** [comment]
Is there a way to check this locally first?
