### ISSUE TITLE
Bring Turf.bbox to libjava

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#196]
Original documentation is [here](http://turfjs.org/docs/#bbox) and code is [here](https://github.com/Turfjs/turf/blob/master/packages/turf-bbox/index.js).

This can be used, for example, to create a `LatLngBounds` object as input to `CameraUpdate` to fit an object in the screen (e.g. a route).

**Comment by cammace** [comment]
Support for this was added in https://github.com/mapbox/mapbox-java/pull/366
