### ISSUE TITLE
Improve JSON fixtures in tests

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#197]
Currently, we've got a mix of JSON content embedded within the code, and some other as separate fixture files. We should be consistent and move multi-line JSON to separate files.

See https://github.com/mapbox/mapbox-java/pull/192#issuecomment-247299027 for background.

**Comment by cammace** [comment]
I have gotten rid of `BaseGeoJSON` in favor of separate fixtures in https://github.com/mapbox/mapbox-java/pull/253. Am I missing anymore or are we safe to close @zugaldia?

**Comment by zugaldia** [comment]
Great job with https://github.com/mapbox/mapbox-java/pull/253. This is good for now, we can ticket out other issues as they arise independently.
