### ISSUE TITLE
RouteUtils getDistanceToStep not measuring correctly

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#205]
Currently `RouteUtils.getDistanceToStep` method measures straight through route ignoring curves and the actual geometry of the route. I've made a demo in the testapp requesting a directions route, drawing the route and then measuring the distance of the last step and drawing the exact same points the `getDistanceToStep` method measures:

<img src="https://cloud.githubusercontent.com/assets/5652865/19535137/96470d64-9614-11e6-870d-9fb3f3c38118.png" width=360/>

We should be measuring the exact geometry of the route

cc: @zugaldia

**Comment by cammace** [comment]
Thinking maybe we should introduce a new method called `getDistanceToNextStep` which will always get the distance to next step in the route from a given position. `getDistanceToStep` I assume is being used for detecting when the users off route?

**Comment by zugaldia** [comment]
> `getDistanceToStep` I assume is being used for detecting when the users off route?

Right (note that method snaps the current location to the route). We might even want to rename it to `getDistanceToCurrentStep` to avoid confusions.

**Comment by zugaldia** [comment]
The problem we're seeing here, that also affects other methods from the `RouteUtils` class is that `TurfMisc.pointOnLine()` chooses the closest point in the geojson structure, which sometimes is far from the user location, and even within offroute conditions. We need a different approach to avoid these situations.

**Comment by cammace** [comment]
With the merge of #222, this issue should be fixed now. I've also added a `getDistanceToNextStep()` method for measuring remaining distance between user and next step. You'll find this in https://github.com/mapbox/mapbox-java/pull/228.
