### ISSUE TITLE
CameraUpdateFactory.newLatLngBounds() not returning greatest possible zoom

### ISSUE THREAD

**Issue by ahuang13** [mapbox/mapbox-java#211]
```
/**
 * Returns a CameraUpdate that transforms the camera such that the specified latitude/longitude
 * bounds are centered on screen at the greatest possible zoom level.
 * You can specify padding, in order to inset the bounding box from the map view's edges.
 * The returned CameraUpdate has a bearing of 0 and a tilt of 0.
 *
 * @param bounds  Bounds to match Camera position with
 * @param padding Padding added to the bounds
 * @return CameraUpdate Final Camera Position
 */
public static CameraUpdate newLatLngBounds(@NonNull LatLngBounds bounds, int padding)
```

The "... at the greatest possible zoom level" guarantee does not always hold true. The resulting zoom (and center) will vary depending on the initial bearing of the map when the CameraUpdate is applied.

When the map starts out at 0-degree bearing, the "greatest possible zoom level" will hold true. If the map starts out at any non-zero bearing, however, we will likely get a suboptimal zoom level with `newLatLngBounds()`.

**Comment by cammace** [comment]
This is actually a bug we are tracking in both https://github.com/mapbox/mapbox-gl-native/issues/2259 and https://github.com/mapbox/mapbox-gl-native/issues/4796. Closing ticket in favor of those issues.

**Comment by ahuang13** [comment]
👍
