### ISSUE TITLE
Double-check latitude-longitude order in Polyline-encoded Map Matching API response handling

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-java#212]
We recently discovered that the Map Matching API returns points encoded in longitude-latitude order when Polyline-encoded geometries are requested. (The Polyline specification requires latitude-longitude order.) The issue will be fixed on the server side shortly. This ticket is a reminder to double-check whether any code or test code assumes longitude-latitude order when decoding these points into Position objects.

/cc @cammace @danpat

**Comment by zugaldia** [comment]
Related: https://github.com/mapbox/mapbox-java/issues/284.
