### ISSUE TITLE
Add missing map matching parameters and response getters

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#234]
We are missing `coordTimes`, `confidence`, `distance`, and `duration`

cc: @zugaldia

**Comment by cammace** [comment]
Note that after further looking into this, all of these are properties and might be considered optional. Not sure if we want to add convenience methods similar to what we did with `matchedPoints`.

**Comment by jl-skyline** [comment]
Only handle property getters on map matching response.

**Comment by zugaldia** [comment]
@jl-skyline After https://github.com/mapbox/mapbox-java/pull/270 was merged, what's missing here? Or are we good to close this ticket?

**Comment by jl-skyline** [comment]
this ticket is good to close with providing methods for a response. 
the coordstimes, mentioned above, is a request parameter and needs a bit more than just a convenience methods which is captured in task #271.

**Comment by cammace** [comment]
`coordTimes` is the only one missing still and https://github.com/mapbox/mapbox-java/issues/271 was created to track this. Closing.
