### ISSUE TITLE
Cant Restrict Panning of map while in offline mode- Android

### ISSUE THREAD

**Issue by shivthepro** [mapbox/mapbox-java#235]
Not able to restrict panning of map to offline areas while in offline mode 

### Steps to trigger behavior

 1.Download Offline Map
 2.Turn off your data connection
 3.Pan to the unavailable area. You are probably lost while you are in the unavailable area in offline mode.

### Expected behavior
Map panning must be restricted to the unavailable area while in offline mode.

![screenshot_2016-12-03-11-01-39-527_com ck ckmapbox](https://cloud.githubusercontent.com/assets/9254310/20857153/80fa515c-b949-11e6-9f53-a29b90bc952d.png)

**Comment by cammace** [comment]
Limiting the viewport movement is something we haven't implemented yet (see https://github.com/mapbox/mapbox-gl-native/issues/3602). For now you can navigate to a downloaded region, see [this snippet of code](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/offline/OfflineManagerActivity.java#L296-L318) on how to do this. In the future, map related issues belong in https://github.com/mapbox/mapbox-gl-native
