### ISSUE TITLE
Geocoder address returns null value

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#242]
The structure of the JSON response has recently changed and we are no longer capturing the fact that `address` (and other fields) are properties of the `Feature` object. E.g.:

```
"properties": {
        "wikidata": null,
        "landmark": false,
        "tel": "(202) 332-5074",
        "address": "2024 Pierce Mill Rd NW",
        "category": "landscaping, gardener, landscape, lawn care",
        "maki": "garden"
}
```

**Comment by cammace** [comment]
From [the Carmen spec](https://github.com/mapbox/carmen/blob/master/carmen-geojson.md#feature-properties), feature properties aren't guaranteed. To get these properties you can do something like this:

```java
if(feature.hasNonNullValueForProperty("address")) {
    String address = feature.getStringProperty("address");
}
```

**Comment by zugaldia** [comment]
Right. And [right now](https://github.com/mapbox/mapbox-java/blob/master/libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/models/CarmenFeature.java#L67-L73) we're assuming `address` is a field of the response instead of a feature property, hence the always `null` value.
