### ISSUE TITLE
Import project in AS

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#246]
I wasn't able to import the whole project (java/android) at once. It didn't seem to find modules and run configurations.

@cammace is this normal workflow? (opening into 2 seperate projects)

I think adding a top level build.gradle could solve this issue.

**Comment by cammace** [comment]
Opening libandroid should also open libjava.

**Comment by tobrun** [comment]
Nice, it works. Would it be possible of adding support to open from the root folder?

**Comment by cammace** [comment]
🤔 not sure about that. I find it kind of inconvenient that the bitrise.yml isn't in the root folder either

**Comment by tobrun** [comment]
looked a bit into this but would require changing project structure. Closing for now.
