### ISSUE TITLE
Document the migration from version 1.3.1 to 2.0

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#254]
With the release of 2.0 in the future, we have several API breaking changes. We should add a document in this repo or within the Wiki page that walks through all the changes for users to update easier.

cc: @zugaldia

**Comment by zugaldia** [comment]
Done as part of https://github.com/mapbox/mapbox-gl-native/wiki/Android-4.x-to-5.0-update.

**Comment by cammace** [comment]
Also the documentation for 2.0 can be [found here](https://www.mapbox.com/android-docs/mapbox-services/).
