### ISSUE TITLE
Add methodscount badge to the project.

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#26]
Likely on the `README.md` file.

**Comment by zugaldia** [comment]
@cammace Let's do this when we release `1.1.0`, https://github.com/mapbox/mapbox-java/pull/44 should help with the method count.

**Comment by cammace** [comment]
[Heres the updated readme](https://github.com/mapbox/mapbox-java/blob/readme-changes/README.md) and the #29 PR. The badge found on methodscount.com is static and wont change when new SDK versions arrive. I'll look for a more automated solution.

**Comment by cammace** [comment]
As mentioned above, method count badge is static and will need to be updated with each new release, once added to release notes, we can close this issue, #29 has been merged and 1.1.0 `README.md` is up!

**Comment by zugaldia** [comment]
I added a note to update the badge in our launch checklist in https://github.com/mapbox/mapbox-java/issues/55. We're ready to close this one. Thanks @cammace !
