### ISSUE TITLE
Correctly follow spec when creating polygon rings

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#263]
Follow the math and physics right-hand rule (not the surveyor’s right-hand rule) when forming polygon rings.

**Comment by zugaldia** [comment]
I'm removing this one from the milestone to help wrap up the 2.0 release, @cammace feel free to re-add if we should bump its priority.

**Comment by cammace** [comment]
Looking further into this issue:

> Note: the [GJ2008] specification did not discuss linear ring winding order. For backwards compatibility, parsers SHOULD NOT reject Polygons that do not follow the right-hand rule.

Since Mapbox-java is a parser client, this should be ignored. Closing.
