### ISSUE TITLE
Correctly construct bounding boxes across antimeridian.

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#264]
Construct bounding boxes so they are not ambiguous at the Earth’s poles and antimeridian.

**Comment by zugaldia** [comment]
I'm removing this one from the milestone to help wrap up the 2.0 release, @cammace feel free to re-add if we should bump its priority.

**Comment by zugaldia** [comment]
@osana @LukasPaczos  You were looking at a similar thing recently in the context of https://github.com/mapbox/mapbox-gl-native/pull/11807. What's your take on this ticket?
