### ISSUE TITLE
Split geometries when crossing antimeridian.

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#265]
> Split geometries that cross the antimeridian into parts that do not cross it.

We don't have any checks for this currently. If I create a linestring that crosses the antimeridian, we aren't spliting it and therefore, wrapping occurs:

<img src="https://cloud.githubusercontent.com/assets/5652865/21728714/ae55e710-d415-11e6-8b91-360ba1f6ee4a.png" width=360/>

**Comment by zugaldia** [comment]
I'm removing this one from the milestone to help wrap up the 2.0 release, @cammace feel free to re-add if we should bump its priority.

**Comment by cammace** [comment]
This issue shouldn't break any APIs and cause a Semver versioning. I'm okay with the removal

**Comment by zugaldia** [comment]
Related: https://github.com/mapbox/mapbox-java/issues/264.

cc: @osana
