### ISSUE TITLE
Add Position check for correct order

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#266]
When creating a Position object, many users accidentally switch up the latitude and longitude values. I propose adding a check so that if the latitude is over `90.0` we throw an error. While this wont always catch the error, it might help out users. We can also make the `invalid position` error more clear on this issue.

**Comment by zugaldia** [comment]
I like it. I wouldn't throw an error but a warning, as the user might be handling coordinates that need to be wrapped.

Related: https://github.com/mapbox/mapbox-java/issues/283.
