### ISSUE TITLE
Add test for location engine

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#275]

**Comment by zugaldia** [comment]
@cammace agreed that the lack of tests isn't ideal. Are there any specific behaviors that you'd like to see tested?

cc: @Guardiola31337

**Comment by cammace** [comment]
The location engine is prone the memory leaks, does it make sense to test around this idea? Such as removing all the listeners, etc.

**Comment by cammace** [comment]
Closing as this ticket is too broad for action. My hope is that in the future we will add test for this :)
