### ISSUE TITLE
Make Carmen feature easier to save in Realm database

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#278]
Currently, Realm offers saving of [mostly primitive types](https://realm.io/docs/java/latest/#field-types) therefore it isn't possible to directly save a Carmen Feature. Saving Carmen Feature is ideal when you want to store recent queries. Thoughts @zugaldia?

**Comment by zugaldia** [comment]
@cammace You can always serialize/deserialize any of our API models to a `String` (with Gson)?
