### ISSUE TITLE
Add `mapbox/driving-traffic` support to the list of directions profiles

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#290]
Documentation is here: https://www.mapbox.com/api-documentation/#directions.

**Comment by cammace** [comment]
note in the documentation the number of waypoints is limited to 3 (not the usual 25), we should look into throwing an exception if more then 3 are added to the request.

> Requests using the driving-traffic profile can specify up to 3 waypoints.

**Comment by srabenja** [comment]
@zugaldia I'll look into it.

**Comment by zugaldia** [comment]
Thanks @srabenja . In case it helps, you might wanna add a new test fixture for this specific type of request. Test fixtures are listed in the [`Makefile`](https://github.com/mapbox/mapbox-java/blob/master/Makefile#L82-L84).

**Comment by cammace** [comment]
https://github.com/mapbox/mapbox-java/pull/292 has been merged, closing.
