### ISSUE TITLE
Track method count in metrics dashboard

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#291]
Capturing required steps from https://github.com/mapbox/mapbox-java/pull/170#issuecomment-270094298 here:

---

- Record a metric to CloudWatch. Have a look at https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/log_binary_size.sh for code. I assume you only want to log the overall method count, not an explosion chart as displayed above (since that'd be difficult to plot over time). 
- Publish the aggregate of the last N days to S3 so that we can create a public dashboard as in binary size (if you don't do this, you can still look at the graphs in CloudWatch)

To publish metrics, run something like this:

```
aws --region us-east-1 cloudwatch put-metric-data \
    --metric-name "Dex" \
    --unit "Count" \
    --value XXXXX
```

I'm not sure we need a `--dimension` parameter, and I can't think of any sensible dimensions for this metric, unless you want to calculate individual namespaces and create a stack chart with the data.

**Comment by cammace** [comment]
Sonarqube will handle tracking of method count for us. Going ahead and closing.
