### ISSUE TITLE
Overlapping dependency with Android SDK

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#32]
When copy pasting example from blog
```java
    MapboxStaticImage staticImage = new MapboxStaticImage.Builder()
                .setAccessToken(getString(R.string.mapbox_access_token))
                .setStyleId(SyncStateContract.Constants.MAPBOX_STYLE_SATELLITE)
                .setLon(lon).setLat(lat)
                .setZoom(15).setBearing(45).setPitch(60)
                .setWidth(500).setHeight(500)
                .setRetina(true)
                .build();
```

Android Studio is automatically importing an Androd SDK dependency instead of this repo. 

![screen shot 2016-04-23 at 12 06 23](https://cloud.githubusercontent.com/assets/2151639/14760724/dcc463dc-094b-11e6-9302-f4715a002148.png)

![screen shot 2016-04-23 at 12 08 12](https://cloud.githubusercontent.com/assets/2151639/14760734/1481fadc-094c-11e6-920d-eee0bb9ce018.png)

I'm suggesting renaming the class/package to something different?

**Comment by tobrun** [comment]
Update: is seems there is no SyncStateContract class in this repo...

**Comment by tobrun** [comment]
cc @zugaldia @cammace

**Comment by zugaldia** [comment]
@tobrun It looks like Studio jumped the gun here but still, happy to rename the `Constants` class to avoid confusions. Mmmh, `ConstantsServices`?

**Comment by zugaldia** [comment]
@tobrun I don't see any `SyncStateContract` in the blog post either https://www.mapbox.com/blog/mapbox-android-services. This seems like an import glitch. I'm gonna keep the `Constants` name for now and will split into subclasses as the class grows like we do in https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants.

Please reopen if you still find any problems.
