### ISSUE TITLE
Add back android-services and java-service modules

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#330]
Previous to 2.0 we only had two modules, `mapbox-android-services` and `mapbox-java-services` which were removed in favor of smaller modules which makes sense. We should still offer these packages to users however and just bundle the smaller modules inside them so users can just switch the dependency version if needed.

cc: @zugaldia

**Comment by zugaldia** [comment]
I don't think this is gonna work. The refactor didn't kill those modules names, it just changed its content. This is defined on [`libjava-services/gradle.properties`](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libjava-services/gradle.properties#L1) and [`libandroid-services/gradle.properties`](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-services/gradle.properties#L1). We'd need to create new names for these meta-packages which I think it'd only be more confusing.
