### ISSUE TITLE
Redirect to version-specific module documentation

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-java#331]
[This repository’s homepage](http://mapbox.github.io/mapbox-java/) mentions the smaller modules created in #251, but the links point to nonexistent pages such as http://mapbox.github.io/mapbox-java/api/libjava-core/. Each such page needs to be a redirect to the latest version of the module, for example http://mapbox.github.io/mapbox-java/api/libjava-core/2.0.0-beta.1/.

/cc @cammace

**Comment by cammace** [comment]
The repo links to https://www.mapbox.com/mapbox-java/#introduction now, where the user can access the javadoc pages.
