### ISSUE TITLE
Consider implementing a geometry formatter

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#35]
See: https://github.com/mapbox/mapbox-gl-native/pull/4802

cc: @1ec5

**Comment by 1ec5** [comment]
“Value methods” refers to category methods on NSValue for boxing and unboxing (serializing and unserializing) struct and primitive types that the SDK uses heavily. That code is very specific to how Objective-C works, so I don’t think it’s relevant to this library.

**Comment by zugaldia** [comment]
Thanks for the clarification @1ec5 .

**Comment by zugaldia** [comment]
> That code is very specific to how Objective-C works, so I don’t think it’s relevant to this library.

Also superseded by more current navigation work.
