### ISSUE TITLE
Library Manifest

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#369]
Looking over the Manifest merging documentation, it looks like service and even user permissions can be merged into users application (only AAR modules) therefore, removing requirement for users to include the telemetry and navigation services inside their application manifest.

**Comment by cammace** [comment]
cc: @zugaldia

**Comment by zugaldia** [comment]
@cammace @tobrun wouldn't this Manifest entry be better added to the SDK Manifest instead (for telemetry)?

**Comment by cammace** [comment]
It should work in either case. Their manifest priorities (the order they are merged) match the dependency order (the order they appear in your Gradle dependencies block). The merger tool can logically match every XML element from one manifest to a corresponding element in the other manifest. I think it makes more sense to place the service inside the telemetry module rather then GL-native since this is where the service is actually maintained.

**Comment by cammace** [comment]
Closing in favor of: https://github.com/mapbox/mapbox-gl-native/issues/8317
