### ISSUE TITLE
Bump SNAPSHOT To Next Version

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-java#37]
MAS `1.0.0` was officially released on 19-April-2016 ( #3 ), however `1.0.0-SNAPSHOTS` continue to be built.  Let's bump this to a new version number (doesn't have to be final) like `1.1.0-SNAPSHOT` so that new work is visibly seen to be different from the `1.0.0` final release.

/cc @zugaldia @tobrun @cammace @danswick

**Comment by zugaldia** [comment]
@bleege Thank you, For future releases I edited https://github.com/mapbox/mapbox-java/issues/3#issuecomment-211556326 to make it more specific that not only a rename is required but a version bump too.

**Comment by bleege** [comment]
Perfect!  👍
