### ISSUE TITLE
Add CI instrumentation testing

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#380]
To catch regressions that only show at runtime, we need to hook up the [app](https://github.com/mapbox/mapbox-java/tree/master/mapbox/app) module to Firebase Test Lab and run these tests as part of our PR workflow. Since we don't have any espresso tests in this module, I'm thinking about leveraging the Robo tests from Firebase Test Lab:

> Robo test is a test tool that is integrated with Firebase Test Lab for Android. Robo test analyzes the structure of your app's UI and then explores it methodically, automatically simulating user activities. Unlike the UI/Application Exerciser Monkey test, Robo test always simulates the same user activities in the same order when you use it to test an app on a specific device configuration with the same maximum depth and timeout settings.

cc @zugaldia

**Comment by zugaldia** [comment]
@tobrun Great approach 👍
