### ISSUE TITLE
Navigation.setBearing isn't handling the destination bearing correctly

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#387]
when passing the bearing values into the direction api parameter, it's required to pass 2 bearing values but we are currently only passing one, this causes an instant crash since we throw an exception.

**Comment by zugaldia** [comment]
For reference, the Directions API docs are [here](https://www.mapbox.com/api-documentation/#directions).

**Comment by cammace** [comment]
Fixed https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-services/src/main/java/com/mapbox/services/android/navigation/v5/MapboxNavigation.java#L257
