### ISSUE TITLE
Localization: Not working for Languages with different Decimal Separator

### ISSUE THREAD

**Issue by pdiegmann** [mapbox/mapbox-java#39]
Hi,

I just wanted to let you know, that the current version of your library is not working for many foreign devices, e.g. German, French, ..., on which a comma instead of a dot is used for decimal separation.
The line in question is probably [MapboxDirections.java:262](https://github.com/mapbox/mapbox-java/blob/master/libjava/lib/src/main/java/com/mapbox/services/directions/v4/MapboxDirections.java#L262) resulting in
`https://api.mapbox.com/v4/directions/mapbox.driving/-77.047237,38.892255;-77.019759,38.903568.json...` for English / American devices and in `https://api.mapbox.com/v4/directions/mapbox.driving/-77,047237,38,892255;-77,019759,38.903568.json...` for e.g. German devices.
The latter request is failing, BTW.

**Comment by zugaldia** [comment]
Good catch @pdiegmann. We just pushed a fix that should be available in the next SNAPSHOT if you want to try it tomorrow.

**Comment by pdiegmann** [comment]
Great, fix! Thanks, @zugaldia!
