### ISSUE TITLE
Lost Location Updates not coming through

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#392]
Been looking into a bug downstream related to location updates in https://github.com/mapbox/mapbox-gl-native/issues/8428. Though we were not hooked into `requestLocationUpdates` it's still not receiving any location updates except for the `lastKnownLocation`. Been testing the LocationEngine example in this repo and confirming the same behavior.

Steps to reproduce:
 - open mock locations app and start a mock route
 - open test app from this repo and navigate to `Location Engine` Activity
 - select `Lost` as location provider
 - you see the screen updating with `lastKnownLocation`
 - no follow-up updates are delivered
 - reopening the activity and reselecting LOST updates the UI once but no follow-up updates are delivered.

cc @mapbox/android

**Comment by tobrun** [comment]
![ezgif com-video-to-gif 23](https://cloud.githubusercontent.com/assets/2151639/24037894/a6711404-0aff-11e7-9d54-82ea77bc28c0.gif)

**Comment by tobrun** [comment]
I was able to get a [sample project](https://gist.github.com/tobrun/197b32f9f32d264604bd4b8f5b3b66f7) working with LOST:

![ezgif com-video-to-gif 24](https://cloud.githubusercontent.com/assets/2151639/24038024/0996e91e-0b00-11e7-9273-ec7632744c83.gif)

**Comment by tobrun** [comment]
![ezgif com-video-to-gif 26](https://cloud.githubusercontent.com/assets/2151639/24038241/dc55dba8-0b00-11e7-800d-b30b84cb36a5.gif)

:rocket:

**Comment by cammace** [comment]
allowing devs to set their own interval and fastest interval depending on the application would help remedy this. https://github.com/mapbox/mapbox-java/issues/395
