### ISSUE TITLE
OnLocationChanged listener always stops after a small number of calls 

### ISSUE THREAD

**Issue by KatieBarnett** [mapbox/mapbox-java#398]
Android SDK version 5.0.0
MAS version 2.0.0
Test device: HTC One M8 5.0.2

I am using the `onLocationChanged` listener but it seems to stop after a small number of calls (usually 2-7). It is stopped sooner if I actually do some work in an async task within the listener.
It seems like the location mode tracking also stops. 
I am spoofing my location movement using another app (and I have tried a couple to see if that is the issue, mostly I use Lockito).
Interestingly, the latitude and longitude I am logging at each `onLocationChanged` call are identical.

I am not calling `removeLocationEngineListener` anywhere in this activity.

Note I am also experiencing issue #386 in a different part of my app (different activity).

Every time I get the following entries in the logs: 
```
03-20 16:18:47.869 26338-26338/com.ibm.events.android.pb D/LocationSource: Provider disabled: network
03-20 16:18:47.869 26338-26338/com.ibm.events.android.pb D/LocationSource: Provider disabled: network
03-20 16:18:48.529 26338-26338/com.ibm.events.android.pb I/SensorManager: unregisterListenerImpl++: listener = com.mapbox.mapboxsdk.maps.widgets.MyLocationView$CompassListener@b7f97ac
```

I call the location permission check from the `onMapReady` function and on success of that call the below method. 

Example code:
```
    private void initNavigation() {

        try {
        map.getTrackingSettings().setDismissAllTrackingOnGesture(true);
 map.getTrackingSettings().setMyLocationTrackingMode(MyLocationTracking.TRACKING_FOLLOW);
        map.setMyLocationEnabled(true);

            // Initiate location tracking
            LocationEngineListener locationListener = new LocationEngineListener() {

                @Override
                public void onConnected() {
                    // Nothing
                }

                @Override
                public void onLocationChanged(Location location) {
                    if (location != null) {
                        Log.d(TAG, "Location changed " + location.getLatitude() + " " + location.getLongitude());
                    }
                }
            };
            locationService.addLocationEngineListener(locationListener);
            locationService.requestLocationUpdates();
        } catch (SecurityException e) {
            // Do nothing, this should have already been handled
        }
    }

**Comment by KatieBarnett** [comment]
Apologies, looks like this issue was caused by something within my app. After a refactor today it seems to be working.

**Comment by cammace** [comment]
A few tips to make this work, call `map.setMyLocationEnabled(true);` before enabling map tracking. I just merged an enhancement that allows you to give your own update interval among other options. Setting this to 0 should give you the quickest update, you'll either need to try it out using the SNAPSHOT or from master here. 

Another thing you can do the help debugging this is to open up Google Maps and start a navigation session. Let it run in the background and see if you location listener gets updated more frequently.
