### ISSUE TITLE
Log SDK version

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#399]
To help developers report their current version one solution would be to always log the current SDK version (including date information to help with SNAPSHOTs) during map instantiation. This could be low-priority `verbose` logging.

Maps SDK: https://github.com/mapbox/mapbox-gl-native/issues/8471

**Comment by mghildiy** [comment]
What would be appropriate place to insert the log?

**Comment by mghildiy** [comment]
Intellij seems to have the feature, but Eclipse may not have this.
