### ISSUE TITLE
RouteProgress not changing current step

### ISSUE THREAD

**Issue by Naroh091** [mapbox/mapbox-java#410]
Hello everyone, 

We're using the latest MAS to make use of the new navigation features in our app. We managed to make the `onProgressChangeListener` work, but everytime we move and gets called the currentStep value is always the same inside the `RouteProgress` object, even when the step should have been changed. 

It does detect we're moving and the `getDistanceRemainingOnStep()` method returns decreasing values while the location changes. These are some of the values obtained (`getDistanceRemainingOnStep()` and `getUpComingStep().getManeuver().getInstruction()`):

```
Connected to the target VM, address: 'localhost:8677', transport: 'socket'
Breakpoint reached at [...]Activity$6.onProgressChange(TripNavigationActivity.java:279)

Merge left onto Avenida Príncipe de Asturias (GJ-10)
37.02268425877319

Breakpoint reached at [...]Activity$6.onProgressChange(TripNavigationActivity.java:279)

Merge left onto Avenida Príncipe de Asturias (GJ-10)
31.778971831952337

Breakpoint reached at [...]Activity$6.onProgressChange(TripNavigationActivity.java:279)

Merge left onto Avenida Príncipe de Asturias (GJ-10)
19.969374863882468

Breakpoint reached at [...]Activity$6.onProgressChange(TripNavigationActivity.java:279)

Merge left onto Avenida Príncipe de Asturias (GJ-10)
5.442811782234332

Breakpoint reached at [...]Activity$6.onProgressChange(TripNavigationActivity.java:279)

Merge left onto Avenida Príncipe de Asturias (GJ-10)
0.0

Breakpoint reached at [...]Activity$6.onProgressChange(TripNavigationActivity.java:279)

Merge left onto Avenida Príncipe de Asturias (GJ-10)
0.0

Breakpoint reached at [...]Activity$6.onProgressChange(TripNavigationActivity.java:279)

Merge left onto Avenida Príncipe de Asturias (GJ-10)
0.0
```

As you can see once the step has been reached it just returns 0.0 as the distance and never changes to the next step. 

Since the documentation is on the works I don't know if this is a bug or there's something we need to do to update the current step.

**Comment by cammace** [comment]
The current step index is changed depending on the users entry angle into the next steps maneuver. Is this occurring on every route you are trying to navigate along? I have not seen the behavior myself before. 

Also, just a heads up, the documentation has [moved locations](https://www.mapbox.com/android-docs/mapbox-services/2.0.0/getting-started/) and been updated.

**Comment by Naroh091** [comment]
We used the emulator (with a KML file with the route) to make the tests, so I guess that should be the issue then, right?. 

I'll try again tomorrow using a real device (and actually doing the route)

**Comment by Naroh091** [comment]
Well, after testing in a real device while walking the route I can confirm this is working correctly. 
Thank you!
