### ISSUE TITLE
MapboxDirections.Builder requires unnecessary generics

### ISSUE THREAD

**Issue by ben-manes** [mapbox/mapbox-java#414]
The builder is defined as,
```java
public static class Builder<T extends Builder> extends MapboxBuilder
```
and has no subclasses.

The usage examples in the unit tests are,
```java
MapboxDirections client = new MapboxDirections.Builder()
  // ...
  .build();
```
which produces a warning due to raw types, e.g.
```
MapboxDirections.Builder is a raw type. References to generic type 
MapboxDirections.Builder<T> should be parameterized.
```

The client-side solution is to either suppress the warning or fulfill the contract,
```java
MapboxDirections client = new MapboxDirections.Builder<MapboxDirections.Builder<?>>()
```
Both of these are ugly, with suppression a little less so as the above is ridiculous.

Since the generics serve no purpose, please remove them.

**Comment by cammace** [comment]
The cause for having a generic type for many of our APIs is due to support for RxJava. See PR https://github.com/mapbox/mapbox-java/pull/304 for more details. Where exactly are you seeing this warning, inside the log or as a lint warning? Is this inside Android Studio or a different IDE? I'm not seeing any warning and the first code snippet you provided is the correct way for building the `MapboxDirections` object.

**Comment by ben-manes** [comment]
I see. I must have missed that subclass when I searched the repository.

The warning appears in javac and Eclipse. I use this server-side.

**Comment by cammace** [comment]
Does this fix your issue or are you still seeing a lint warning?

**Comment by ben-manes** [comment]
It explains the issue. I had to suppress the warning when upgrading to the v2 library, but I don't consider that a proper "fix" for users. I suppose the simplest fix would be to adopt a `newBuilder` factory method to provide the ugly return type, which would be backwards compatible. But the raw type warning is a valid flaw of the current library's API design.

**Comment by ben-manes** [comment]
The reason why you don't see this is because your build does not turn on javac linting. That is a good practice to follow and you can do so as,

```gradle
tasks.withType(JavaCompile) {
  options.compilerArgs << '-Xlint:all'
}
```

Then you will see warnings such as,

```java
warning: [rawtypes] found raw type: Builder
      MapboxDirections client = new MapboxDirections.Builder()
                                                    ^
  missing type arguments for generic class Builder<T>
  where T is a type-variable:
    T extends Builder declared in class Builder
```

**Comment by jpshelley** [comment]
Its also not a clear conversion to Kotlin due to the raw generics.

**Comment by cammace** [comment]
@Guardiola31337 would you happen to have any ideas on how we could improve this builder. Originally, I was pushing for using AutoValues but from what I put together in https://github.com/mapbox/mapbox-java/pull/491, this would cause several breaking changes.

**Comment by cammace** [comment]
Moving forward with my previous comment, 3.0.0 we are switching up the API to use AutoValue for the majority of the libraries APIs which removes the generic issue described in this discussion.

**Comment by ben-manes** [comment]
Thanks! I use AutoValue and its superb.

Please also consider enabling lint, and perhaps using ErrorProne, to catch these types of oversights.

**Comment by cammace** [comment]
Added AutoValue throughout the entirely rewritten Mapbox Java 3.0 release (coming soon), also added errorprone and sonarqube for better tracking. Thanks for all the ideas @ben-manes, feel free to give the code a look over and contribute if you see any issues, the new codes in https://github.com/mapbox/mapbox-java/tree/mb-java-3.0.0

**Comment by ben-manes** [comment]
Thanks @cammace. It looks good so excited to give it a try. The only addition I would suggest is to enable lint (as shown above).

**Comment by cammace** [comment]
lint is only for Android correct? The entire project is Java only now :)

**Comment by ben-manes** [comment]
Android has its own lint concept. I use this on the server-side, where javac has its own linter.

**Comment by jehutyno** [comment]
It's still a big problem in Kotlin because it doesn't rely on raw type.
See same issue here : https://youtrack.jetbrains.com/issue/KT-17186

**Comment by cammace** [comment]
@jehutyno are you using the code in master (3.0.0)? Or 2.x?

**Comment by jehutyno** [comment]
@cammace I'm using the code on 2.2.9
