### ISSUE TITLE
Improve permissions management

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-java#419]
Per [Permissions wrong requested for devices with API level 22 or lower](https://github.com/mapbox/mapbox-gl-native/issues/8424) we should improve how permissions are managed and ensure consistency between apps.

We should consider the following options:

- Use a 3rd party library like [Dexter](https://github.com/Karumi/Dexter)
  - Not reinventing the wheel :white_check_mark:
  - Simplifies the process of requesting permissions at runtime :white_check_mark:
  - Adds a new dependency to SDK 🤔 
  - [Caveat](https://commonsware.com/blog/2015/11/09/you-cannot-hold-nonexistent-permissions.html) ❌ 
- Improve [`PermissionsManager`](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/permissions/PermissionsManager.java)
  - Reinventing the wheel? 🤔 
  - Not adding a new dependency :white_check_mark:
  - Deal with the [caveat](https://commonsware.com/blog/2015/11/09/you-cannot-hold-nonexistent-permissions.html) mentioned before ❌ 

In both options Android deals with when [permissions](https://developer.android.com/training/permissions/requesting.html) are requested (pre/post Android 6.0) and shows the dialogs wisely :white_check_mark:

Thoughts? Comments?

@mapbox/android

**Comment by cammace** [comment]
Note that both [coarse and fine location permissions](https://developer.android.com/reference/android/Manifest.permission.html#ACCESS_COARSE_LOCATION) have been around since API 1 and shouldn't fall into the issue described in the article above. Perhaps we should narrow the scope of what the permission manager can handle or indeed fix this up. usage of the permission manager is optional anyways, and the developer has the option to handle it manually or use a third party library such as Dexter.

**Comment by zugaldia** [comment]
I agree with @cammace above. Let's start by listing which specific features we need, that `PermissionsManager` isn't currently providing. Depending on the list of requirements, we could then decide whether an external dependency is worth it.

**Comment by zugaldia** [comment]
From what I can see in https://github.com/mapbox/mapbox-gl-native/pull/8559/files, those two methods can easily be brought into `PermissionsManager` and an external dependency wouldn't be required (unless there are additional requirements).

**Comment by cammace** [comment]
@Guardiola31337 what's the status of this issue? I am going ahead and removing it from the 2.2.0 milestone.

**Comment by cammace** [comment]
@Guardiola31337 @electrostat Can this be moved to the new telem repo or closed if you guys feel this functionality is no longer needed.
