### ISSUE TITLE
Handler could be null

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-java#436]
[`handler`](https://github.com/mapbox/mapbox-java/blob/master/mapbox/app/src/main/java/com/mapbox/services/android/testapp/location/MockLocationEngine.java#L86) could be `null` which would make the app to crash.

Following snippet will fix the issue.
```java
if (handler != null) {
  handler.postDelayed(new LocationUpdateRunnable(), UPDATE_INTERVAL_MS);
}
```

**Comment by cammace** [comment]
closing in favor of https://github.com/mapbox/mapbox-navigation-android/issues/5
