### ISSUE TITLE
Fix developer config creation task

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-java#451]
Current [task](https://github.com/mapbox/mapbox-java/blob/master/mapbox/app/gradle-config.gradle) is not working when you don't have `MAPBOX_ACCESS_TOKEN` environment variable set. Actually, it always creates a file in which `mapbox_access_token` is `null` which throws a `MapboxConfigurationException` crashing the app.

It's fixed in [`mapbox-navigation-android`](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/app/developer-config.gradle) so porting those changes would fix the issue.

**Comment by SourceNode** [comment]
I am interested in taking this open issue for resolution.

**Comment by Guardiola31337** [comment]
Go for it @SourceNode 💪

**Comment by osana** [comment]
@Guardiola31337  can we close that issue?

**Comment by Guardiola31337** [comment]
Yeah. This was superseded by https://github.com/mapbox/mapbox-java/pull/688 👀 https://github.com/mapbox/mapbox-java/pull/603#issuecomment-350873180

Closing here.
