### ISSUE TITLE
404 Error on Doc link from https://www.mapbox.com/about/open/

### ISSUE THREAD

**Issue by it33** [mapbox/mapbox-java#453]
https://mapbox.github.io/mapbox-java/

![image](https://cloud.githubusercontent.com/assets/177788/25318929/564e3afa-284c-11e7-9e9f-1dffa9484ead.png)

Maybe out-of-date link from webpage? https://www.mapbox.com/about/open/

![image](https://cloud.githubusercontent.com/assets/177788/25318934/62fd476e-284c-11e7-8c45-f04932f3a59a.png)

**Comment by zugaldia** [comment]
cc: @cammace @langsmith

**Comment by langsmith** [comment]
I will fix this

**Comment by cammace** [comment]
Link has been fixed, thanks for reporting @it33
