### ISSUE TITLE
Rename APIs in documentation

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#455]
Two APIs are being renamed to a shorter name: `Optimized Trips API` is now `Optimization API`, and `Directions Matrix API` is now `Matrix API`. Let's update the docs (README, website, test app, Javadoc...) for the next version.

Note that this changes does not affect the URLs or request/response models, only the names of the APIs themselves.

cc: @cammace

**Comment by cammace** [comment]
We've made the changes throughout 3.0 for this naming change. Should be good to close :)
