### ISSUE TITLE
Release Mapbox Services 2.1.1

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#466]
This ticket tracks the final release of Mapbox Android Services `v2.1.0`. The leading feature in this release includes both the inclusion of the Directions Matrix and Optimized Trips APIs among an abundance of other bug fixes.

### Highlights
* Updates to LOST `3.0.0`: https://github.com/mapbox/mapbox-java/pull/462
* Fixed location timestamp issue: https://github.com/mapbox/mapbox-java/pull/463
* Updated library dependencies: https://github.com/mapbox/mapbox-java/pull/464
* correct units for `LegAnnotation.speed`: https://github.com/mapbox/mapbox-java/pull/460

### Release checklist @cammace @zugaldia 

- [x] Finish merging PRs that exist on the `2.1.1` milestone
- [x] Run through testapp/demo app and test all activities
- [x] Change version name to `2.1.1` in `gradle.properties`
- [x] Publish `2.1.1` artifact to Maven Central
- [x] Change version name back to `2.2.0-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `v2.1.1` in GitHub
- [x] Update dependencies in the Maps SDK

### Post-release @langsmith

- [x] Update `README.md`
- [x] Update Javadoc and docs in https://www.mapbox.com/android-docs/mapbox-services/latest/getting-started/
- [x] Update install instructions in https://www.mapbox.com/android-sdk/#mapbox_android_services
- [x] Update config files in /android-sdk and /help repos
- [x] Update the gradle files for demo and wearable demo apps

/cc: @mapbox/mobile

**Comment by cammace** [comment]
Over to you @langsmith

**Comment by cammace** [comment]
@langsmith the readme can be updated to `2.2.0-SNAPSHOT` now. https://github.com/mapbox/mapbox-java/blob/master/mapbox/gradle.properties#L2

**Comment by langsmith** [comment]
@cammace ☝️  👉  https://github.com/mapbox/mapbox-java/pull/473

**Comment by langsmith** [comment]
@cammace , assigning this ticket to you because the remaining task is java doc generation which you said you do...

**Comment by cammace** [comment]
PR opened adding the Javadoc. Closing
