### ISSUE TITLE
Self Hosting

### ISSUE THREAD

**Issue by saeedrooyekhat** [mapbox/mapbox-java#483]
How can i use from mapbox with self hosting? 

Platform:android
Mapbox Services version : com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.2@aar

**Comment by cammace** [comment]
`com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.2@aar` is the Map SDK in a [different repo](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android). Can you describe a bit more on what you are trying to do?
