### ISSUE TITLE
Release MAS 2.1.2

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#487]
In preparation for the final release of the Maps SDK v5.1.0 we're publishing today a maintenance release of MAS that includes incremental updates and stability fixes.

### Highlights

* Updates to LOST `3.0.1` which fixes a bug where location requests were too aggressive https://github.com/mapbox/mapbox-java/pull/486
* Expose `MockLocationEngine` as part of the public API https://github.com/mapbox/mapbox-java/pull/476
* Update style versions to `v10` and add traffic styles https://github.com/mapbox/mapbox-java/pull/478
* Fix static marker annotation URL generation https://github.com/mapbox/mapbox-java/pull/479
* Add convert distance method to `TurfHelper` https://github.com/mapbox/mapbox-java/pull/481
* Add new SSL certs for 2018/2019 https://github.com/mapbox/mapbox-java/pull/484

### Release checklist @cammace @zugaldia 

- [x] Change version name to `2.1.2` in `gradle.properties`
- [x] Publish `2.1.2` artifact to Maven Central
- [x] Change version name back to `2.2.0-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `v2.1.2` in GitHub
- [x] Update dependencies in the Maps SDK

### Post-release @langsmith

- [x] _If_ there's a new SNAPSHOT version, then update this repo's `README.md` file
- [x] Update Javadoc for the MAS docs section
- [x] Update the `compile 'com.mapbox.mapboxsdk:mapbox-android-services:x.x.x'` line in the Gradle section of [the MAS overview page](https://www.mapbox.com/android-docs/mapbox-services/overview/)
- [x] Update the `compile 'com.mapbox.mapboxsdk:mapbox-android-ui:2.1.2'` line in the Android demo app's gradle file

/cc: @mapbox/mobile

**Comment by zugaldia** [comment]
MAS is now live on Maven Central (https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-services/2.1.2/), follow up PR for the Maps SDK is now pending review on https://github.com/mapbox/mapbox-gl-native/pull/9311.

@langsmith over to you, thanks.

**Comment by langsmith** [comment]
@cammace [made javadocs for this release](https://www.mapbox.com/android-docs/api/mapbox-java/libjava-services/2.1.2/index.html)
