### ISSUE TITLE
MockLocationEngine better handle Android lifecycle 

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-java#497]
Currently if you deactivate the `MockLocationEngine` (like on config change) you need a `DirectionsRoute` and user `Position` to re-activate and start sending updates again.  If we can handle this within the class itself, dealing with state changes would be much easier

cc: @cammace

**Comment by cammace** [comment]
Closing since the mock location engine now lives in the nav repo: https://github.com/mapbox/mapbox-navigation-android/issues/447
