### ISSUE TITLE
Expose exit numbers on route steps

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-java#498]
`LegStep` should have a property corresponding to the `exits` property that was implemented in Project-OSRM/osrm-backend#4215. This property contains the [exit number](https://en.wikipedia.org/wiki/Exit_number) of the exit at the route step’s maneuver.

/ref mapbox/MapboxDirections.swift#146
/cc @cammace

**Comment by cammace** [comment]
Resolved in 3.0.0, Closing.

**Comment by 1ec5** [comment]
Are you referring to the `LegStep.exit` property added in #303? That’s the “nth exit” for roundabout maneuvers, not the alphanumeric highway [exit number](https://en.wikipedia.org/wiki/Exit_number) for off-ramp maneuvers. I don’t see anything in this repository that corresponds to the [`RouteStep.exits`](https://www.mapbox.com/api-documentation/#routestep-object) property in the Directions API response.

**Comment by 1ec5** [comment]
@cammace pointed out that this is indeed implemented on the mb-java-3.0.0 branch, which I was unaware of:

https://github.com/mapbox/mapbox-java/blob/9d3111643642cf63ce3c0699d7fa1523dba5bb30/services-directions/src/main/java/com/mapbox/directions/v5/models/LegStep.java#L166-L173

By the way, here’s the more verbose documentation we have for this property in MapboxDirections.swift:

https://github.com/mapbox/MapboxDirections.swift/blob/763ae9fe23ba727238b67dd8df45fd3651326c06/MapboxDirections/MBRouteStep.swift#L787-L791

I figured it was important to provide lots of detail here because it’s easy to confuse it with that roundabout exit number property.
