### ISSUE TITLE
LocationEngineListener Problem.

### ISSUE THREAD

**Issue by Larnoo** [mapbox/mapbox-java#500]
**Platform:** Android
**Mapbox Services version:**

### Steps to trigger behavior

 1. `MyCustomLocationEngine extends LocationEngine`
 2.  But MyCustomLocationEngine don't have a 'onConnected' callback method.
 3. What I can do for the `LocationEngineListener` method `onConnected()`?

If I don't call the the `LocationEngineListener` method `onConnected()`, what will happens?
@tobrun

**Comment by tobrun** [comment]
If you don't call onConnected, the listeners reqistred to your LocationEnige will not be notified that they can request Location events. If the system your are encapsulating doesn't have the concept of connected I would advice to hook into activate instead. 

```
  @Override
  public void activate() {
    // "Connection" is immediate here
    for (LocationEngineListener listener : locationListeners) {
      listener.onConnected();
    }
  }
```

Calling this question answered, let us know if you have any other questions!
