### ISSUE TITLE
TelemetryUtils unnecessary CPU usage during touch events

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#501]
During panning and dragging, we are seeing CPU is consumed by TelemetryUtils, specifically context.getSystemService() calls and operations on TelephonyManager. TelemetryUtils.class.getSimpleName() is also expansive because it will use reflection to get the string.

One possible solution would be to move all pushEvents to a HandlerThread with low priority that gets created and destroyed during onCreate and onDestroy of MapView. Alternatively, we could have Telemetry events built later at a Service thread instead of the main thread as well as caching system services in a non static instance.

**Comment by cammace** [comment]
@Guardiola31337 @electrostat has this issue been resolved? Can we close this and move to the appropriate repo?
