### ISSUE TITLE
Add set language interface into all the services.

### ISSUE THREAD

**Issue by LornTao** [mapbox/mapbox-java#503]
@zugaldia 
In order to set a default language when customize the map out of the English language areas. Optimization, Map Matching, and Directions also should support a language parameter. We should do the same for these services as [Geocoding Service here](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libjava-services/src/main/java/com/mapbox/services/api/geocoding/v5/MapboxGeocoding.java#L553-L556).

cc/ @cammace

**Comment by cammace** [comment]
I've added language support for the Directions API (see https://github.com/mapbox/mapbox-java/pull/504) and Optimization API (see https://github.com/mapbox/mapbox-java/pull/506). I'll continue adding more language options to the other APIs as I go through updating them.

**Comment by cammace** [comment]
Finished adding all language params in https://github.com/mapbox/mapbox-java/pull/507 for all APIs. Will be available in MAS 2.2.0 release
