### ISSUE TITLE
NullPointerExcetion When Using MapboxGeocoding.getObservable()

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-java#51]
The `service` object is always null when `MapboxGeocoding.getObservable()` is called which results in a NullPointerException.  This is due to the the [internal `service` object being referenced directly](https://github.com/mapbox/mapbox-java/blob/c4215912dfd22ee3ce8a189b8ad409cc4c25b472/libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/MapboxGeocoding.java#L97) instead of calling `getService()` which is what's responsible for the object's creation.

```java
java.lang.NullPointerException: Attempt to invoke interface method 'rx.Observable com.mapbox.services.geocoding.v5.GeocodingService.getObservable(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
    at com.mapbox.services.geocoding.v5.MapboxGeocoding.getObservable(MapboxGeocoding.java:96)
```

![screen shot 2016-04-30 at 5 29 33 pm](https://cloud.githubusercontent.com/assets/989928/14938914/9ea8b2ac-0ef9-11e6-8034-def9885de7fb.png)

/cc @zugaldia

**Comment by bleege** [comment]
The only thing that remains is to add a data test to the end of the `testObservable()` to ensure that it's working as expected.  We'll reuse the code from `testContext()`, but I need to learn more about how RxAndroid is expected to work with this before hand.  Will discuss with @zugaldia next week to finish this issue. 

```java
        List<FeatureContext> contexts = response.body().getFeatures().get(0).getContext();
        assertEquals(contexts.get(4).getId(), "country.12862386939497690");
        assertEquals(contexts.get(4).getText(), "United States");
        assertEquals(contexts.get(4).getShortCode(), "us");
```

**Comment by zugaldia** [comment]
Merged! Thanks @bleege .
