### ISSUE TITLE
Proguard rule missing

### ISSUE THREAD

**Issue by gabrieloshiro** [mapbox/mapbox-java#514]
**Platform: Android**
**Mapbox Services version: 2.1.3**

### Steps to trigger behavior

 1. Launching app on Debug, GeocoderAutoCompleteView is properly displayed.
 2.Launching the same app on release with proguard `minifyEnabled true` option will cause GeocoderAutoCompleteView not show the autocomplete suggestion fields.

### Expected behavior

GeocoderAutoCompleteView should be displayed the same way on debug and release.

### Actual behavior

No suggestion fields are displayed for GeocoderAutoCompleteView on release (when proguard `minifyEnable true`) (with `minifyEnabled false` everything works fine)

Here is the warning:

```
An exception occured during performFiltering()!
  java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.mapbox.services.api.geocoding.v5.models.GeocodingResponse.getFeatures()' on a null object reference
      at com.mapbox.services.android.ui.geocoder.GeocoderAdapter$GeocoderFilter.performFiltering(GeocoderAdapter.java:479)
      at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:148)
      at android.os.HandlerThread.run(HandlerThread.java:61)
```

Can anyone help me?

**Comment by cammace** [comment]
Hey in preparation for the 2.2.0 release, I ran through our testapp with ProGaurd enabled and did run into a few crashes and added some new rules. However, when testing the geocoder widget, I ran into no issues and was able to get search results. Can you update to 2.2.0 later when released and see if the issues resolved?

**Comment by cammace** [comment]
Stale, closing.
