### ISSUE TITLE
Deserializer for geocoder language json fields.

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#515]
#512 adds support for requesting multiple languages but the response currently isn't handling additional json fields `text_{language}`, `place_name_{language}` and `language_{language}` since the field name depends on different languages. We will need to use a custom deserializer to handle these different fields.

cc: @zugaldia

**Comment by zugaldia** [comment]
Now need to reopen, this is being tracked here: https://github.com/mapbox/mapbox-java/issues/446#issuecomment-440333335.
