### ISSUE TITLE
Location Tracker is not released

### ISSUE THREAD

**Issue by ovivoda** [mapbox/mapbox-java#518]
**Platform: mapbox-android-sdk:5.0.2
**Mapbox Services version: mapbox-android-services:1.3.1

`com.mapbox.mapboxsdk.maps.MapboxMap.setMyLocationEnabled(true)` - starts the the location tracker and it keeps it on even if 

`com.mapbox.mapboxsdk.maps.MapboxMap.setMyLocationEnabled(false)`

is called later on.

The only way to close the location tracker is to close the application which uses Mapbox android SDK

### Steps to trigger behavior

 1. `com.mapbox.mapboxsdk.maps.getMapAsync`
 2. `com.mapbox.mapboxsdk.maps.MapboxMap.setMyLocationEnabled(true)`
 3. `com.mapbox.mapboxsdk.maps.MapboxMap.setMyLocationEnabled(false)`

### Expected behavior

After point 3 I expect location tracker to be turned off. Instead location tracker is still on until I close the application.

### Actual behavior

The location system icon is still enable and location tracker is not released

![location_on](https://user-images.githubusercontent.com/5989047/28452768-e084a8f8-6dfc-11e7-8306-f51aad1f22c6.png)

**Comment by cammace** [comment]
Can you try upgrading to the latest dependencies? Map SDK: `5.1.1` and Mapbox-Java: `2.1.3` (will become `2.2.0` later today).

**Comment by cammace** [comment]
Closing since this is stale if you are still seeing this issue using the latest SDK versions, please let me know and I can further look into it.

**Comment by ovivoda** [comment]
I tested it with Map SDK: 5.1.1 and Mapbox-Java: 2.2.0 and the issue is still there.

**Comment by cammace** [comment]
cc: @Guardiola31337 @electrostat to ensure the correct eyes are looking over this.

**Comment by cammace** [comment]
Stale, closing
