### ISSUE TITLE
add exit field in legStep object.

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#525]
cc: @zugaldia

**Comment by anant2614** [comment]
Hi, I intend to take up this task and I'm new here.Can someone please guide me on how to build the project after doing the initial setup ?

**Comment by zugaldia** [comment]
@anant2614 Great to hear - I'd love to help you finalize the set up. You should be able to import the `mapbox` folder like a regular Android Studio project. Then, you could run the Test App like any regular app to verify your changes. Do you have any specific questions or issues?

**Comment by anant2614** [comment]
@zugaldia I have done my setup and have run the Test App as well.Just trying to figure out why some actions  are crashing the app on my phone.

**Comment by zugaldia** [comment]
> Just trying to figure out why some actions are crashing the app on my phone.

Please do [open a ticket](https://github.com/mapbox/mapbox-java/issues/new) for each issue you're observing, I'll make sure to follow up (thanks!).

**Comment by anant2614** [comment]
Sure.Well this was due to the token missing. 
Regarding the exit field, where and how  will this field be used ?

**Comment by cammace** [comment]
Hey @anant2614, the [directions API documentation](https://www.mapbox.com/api-documentation/#routestep-object) mentions `exits` as a new request option. More specific:
> exits: String with the exit numbers or names of the way. Optionally included, if data is available.

The getter/setter will go inside the [LegStep class](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/LegStep.java). You'll probably need to either update the test fixtures or find a new directions route that includes exit information in order to write the test.

**Comment by anant2614** [comment]
@cammace I have updated the test fixture and added a new test after the required changes.Raised the PR: #530.

**Comment by cammace** [comment]
This has been added in the 3.0.0 branch, closing.
