### ISSUE TITLE
Add equals, to string and hash to locationEngine

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#526]
There's currently no way to determine if one location is equal to another.

**Comment by Abrasha** [comment]
Hi @cammace. I can help you with that. 

Please, can you describe by which criteria we should compare two LocationEngine instances?

Am I right that changes should be added to [LocationEngine](https://github.com/mapbox/mapbox-java/blob/71d308031865e362e984e048d21331df843c9a99/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/LocationEngine.java) file?

I will also add proper unit tests for `equals` and `hashCode`

**Comment by cammace** [comment]
Hey @Abrasha, thanks for your interest in contributing to this repo, we are actually in the middle of extracting the locationEngine logic out of this library and moving it to a different repo, thus adding these changes wouldn't matter much here. If you are interested in taking a look at the next release 3.0.0, i'd recommend checking out the https://github.com/mapbox/mapbox-java/tree/mb-java-3.0.0 branch.

**Comment by cammace** [comment]
Moved to the appropriate repo for tracking this. Closing.
