### ISSUE TITLE
Android O crash at startup 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#527]
Ticket originally from https://github.com/mapbox/mapbox-gl-native/issues/9649.

**Platform: Android**
**Mapbox SDK version: 5.1.1**

We recently released an update of our Android app with Mapbox SDK 5.1.1. We've noticed a lot of crashes through Fabric/Crashlytics from telemetry. Is there a way to disable telemetry? If not, ill link the crash log below. 

The crash seems to happen when Mapbox tries to enable telemetry. 

```
Fatal Exception: java.lang.RuntimeException
Unable to create application com.roadtrippers.RoadtrippersApplication: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.roadtrippers/com.mapbox.services.android.telemetry.service.TelemetryService }: app is in background uid UidRecord{143a0b4 u0a262 RCVR idle procs:1 seq(0,0,0)}
...
com.mapbox.services.android.telemetry.MapboxTelemetry.setTelemetryEnabled(MapboxTelemetry.java:308)
```

Full crash details: http://crashes.to/s/c42a8c0da9b

**Comment by DejanRistic** [comment]
Just noting here that the issue has now been reported once for `6.0.1`. So it may not be 💯 related to O. The crash link will show the 1 on `6.0.1` as well.

**Comment by cammace** [comment]
This issue has been resolved @Guardiola31337 @electrostat, going ahead and closing.
