### ISSUE TITLE
version 2.2.0 missing libjava-services-rx part?

### ISSUE THREAD

**Issue by artshell** [mapbox/mapbox-java#531]
version 2.2.0 missing libjava-services-rx part?

**Comment by cammace** [comment]
Looks like the [RX module](https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-java-services-rx/) got published on Maven during the release?

**Comment by artshell** [comment]
@calfarome 
my project config:

```java
repositories {
        mavenCentral() // jcenter() works as well because it pulls from Maven Central
        jcenter()
        maven { url "https://jitpack.io" }
    }
```
```java
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    testCompile 'junit:junit:4.12'

   // ... other

    compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.1@aar'){
        transitive=true
    }
    compile 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.0'

    // ... other
}
```
Strange to say, At external libraries inside, mapbox-java-services-2.2.0 package missing libjava-services-rx part . Other way search key 'MapboxGeocodingRx' by android studio search everywhere action notying result.

**Comment by artshell** [comment]
- mapbox-android-services-2.2.0
- mapbox-android-telemetry-2.2.0
- mapbox-java-core-2.2.0
- mapbox-java-geojson-2.2.0
- mapbox-java-services-2.2.0

but misssing:
- mapbox-java-services-rx-2.2.0

**Comment by cammace** [comment]
Stale. closing
