### ISSUE TITLE
Reuse connection pool under multiple thread access

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#535]
Looks like our current approach to building an `OkHttpClient` is failing under multi-threaded applications, which is making us not reuse the connection pool potentially provoking an out of memory crash under some circumstances. This is probably because [`getOkHttpClient()`](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libjava-services/src/main/java/com/mapbox/services/api/MapboxService.java#L64-L81) isn't `synchronized`.

cc: @cammace @tobrun

**Comment by osana** [comment]
@zugaldia @cammace  I will go ahead and add `synchronized`  to `MapboxService.getOkHttpClient()` method. 

Any suggestions on how to test this?

**Comment by zugaldia** [comment]
> Any suggestions on how to test this?

@osana Could you build instances of an API client (e.g. MapboxGeocoding) with two scenarios: 1) same thread, and 2) different threads and then check if you observe any differences in the total `connectionCount` returned by the OkHttpClient? We'd like to compare this result before and after applying https://github.com/mapbox/mapbox-java/pull/734.

**Comment by osana** [comment]
Created a new issue to prove that #734 indeed fixed #736 
--> #736
