### ISSUE TITLE
Only onRunning gets triggered!

### ISSUE THREAD

**Issue by simpatiamd** [mapbox/mapbox-java#538]
Platform: Android 6.0
**Mapbox Services version:**

### Steps to trigger behavior

 1.  In fragment:
 @Override
    public void onResume() {
        super.onResume();
        //add navigation listeners
        mainActivity.navigation.addNavigationEventListener(this);
        mainActivity.navigation.addOffRouteListener(this);
        mainActivity.navigation.addProgressChangeListener(this);
        mainActivity.navigation.addMilestoneEventListener(this);
    }

 2. Overrided listeners:
//shows if user started navigation session or ended it
    @Override
    public void onRunning(boolean running) {
        if(running){
            //change flag
            startNavigation = true;
        } else {
            startNavigation = false;
        }
    }

    //off-route listener
    @Override
    public void userOffRoute(Location location) {
        //show user off route dialog
        Toast.makeText(getContext(), "Return to route!!!", Toast.LENGTH_LONG).show();
    }

    //progress change listener
    @Override
    public void onProgressChange(Location location, RouteProgress routeProgress) {
        showGpsHelpInfo(routeProgress.getCurrentLegProgress().getCurrentStep().getName(),String.valueOf(routeProgress.currentLegProgress().currentStepProgress().getDistanceRemaining()),
                routeProgress.getCurrentLegProgress().getUpComingStep().getManeuver().getModifier());
    }

    //milestone event listener
    @Override
    public void onMilestoneEvent(RouteProgress routeProgress, String instruction, int identifier) {
        playStepInfoSound(instruction);
       
        }

    }

 3. Start navigation:
//start mapbox navigation engine
        mainActivity.navigation.startNavigation(route);

### Expected behavior
Expect to be triggered all 4 listeners
### Actual behavior
Only onRunning() gets called

**Comment by cammace** [comment]
The navigation SDK can actually be found inside [this repo](https://github.com/mapbox/mapbox-navigation-android). Closing this issue but will open an issue in navigation if you are seeing this issue in the latest version of the SDK, which version are you seeing this on?
