### ISSUE TITLE
Not showing my nearby places.

### ISSUE THREAD

**Issue by prashantwosti** [mapbox/mapbox-java#54]
I'm using GeocoderAutoCompleteView to get nearest POI with respect to proximity but its strange that I'm not getting results of nearby places. I'm from Nepal, currently living in Kathmandu. 

```
autocomplete.setType(GeocodingCriteria.TYPE_POI);
autocomplete.setProximity(Position.fromCoordinates(
                27.6796678, 85.3490278));
```

Google's geocoding works fine in the same case. Why not mapbox's?

**Comment by zugaldia** [comment]
@prashantwosti Thanks for using our geocoder and for the  feedback. Unfortunately, we don't currently support Nepal in our geocoder. You can see a coverage list in https://www.mapbox.com/geocoding/#coverage.

Also, though it won't help in this case, note that the `Position.fromCoordinates()` constructor takes a `double longitude, double latitude`, in that order, so in your case you should do `autocomplete.setProximity(Position.fromCoordinates(85.3490278, 27.6796678));`

Closing now, keep the feedback coming.

/cc: @geohacker

**Comment by prashantwosti** [comment]
So any workaround to make it work with mapbox.  This will affect my whole project. Damn!

**Comment by zugaldia** [comment]
@prashantwosti Please keep an eye on https://www.mapbox.com/geocoding/#coverage and https://www.mapbox.com/api-documentation/#geocoding, we'll update them as soon as we expand coverage or include new features. Thanks again for checking the geocoder!
