### ISSUE TITLE
Release 2.2.1

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#542]
In preparation for the 5.1.3 release of the Map SDK we are releasing a new version of the Mapbox Java SDK. 

### Release checklist @cammace @zugaldia 

- [x] Change version name to `2.2.1` in `gradle.properties`
- [x] Publish `2.2.1` artifact to Maven Central
- [x] Change version name back to `2.3.0-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `v2.2.1` in GitHub
- [x] Update dependencies in the Maps SDK

### Post-release @langsmith

- [x] _If_ there's a new SNAPSHOT version, then update this repo's `README.md` file
- [x] Update Javadoc for the MAS docs section
- [x] Update the `constants.js` file in `android-docs` repo so that `compile 'com.mapbox.mapboxsdk:mapbox-android-services:x.x.x'` line is updated in [the Gradle section of the MAS overview page](https://www.mapbox.com/android-docs/mapbox-services/overview/)
- [x] Update the `compile 'com.mapbox.mapboxsdk:mapbox-android-ui:X.X.X'` line in the Android demo app's Gradle file

/cc: @mapbox/mobile

**Comment by langsmith** [comment]
Done 🎆
