### ISSUE TITLE
New directions callback

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#548]
We can create a `ServiceCallback` which includes an additional callback `onNoRoute` which is invoked when the response returns 0 routes. This would remove the boilerplate code needed every time a request is made:

```java
if (response.body() == null) {
   Log.e(LOG_TAG, "No routes found, make sure you set the right user and access token.");
  return;
}
if (response.body().routes().size() < 1) {
  return;
}
```

and the new callback would look something like:

```java
builder.build().enqueueCall(new MapboxService.ServiceCallback<T>() {
      @Override
      public void onResponse(Response<T> response) {

      }

      @Override
      public void onNoRoute(Response<T> response) {

      }

      @Override
      public void onFailure(Throwable t) {

      }
    });
```

cc: @zugaldia

**Comment by zugaldia** [comment]
> We can create a ServiceCallback which includes an additional callback onNoRoute which is invoked when the response returns 0 routes.

This would only be useful for directions requests, however that `ServiceCallback` would apply to all API services. Wouldn't it be better if we could simply do `response.body().hasRoutes()` and have that method be syntactic sugar for the `response.body().routes().size() < 1` check?

**Comment by cammace** [comment]
We are now having to be a middleman between the request and the incoming response for the directions API due to having to fill in the `RouteOptions` object (stores request information). Essentially what I'm doing is when `enqueueCall` or `executeCall` are called, I first check that the response has at least 1 route as described in the original comment above. 

Currently, if a DirectionsRoute _does not_ exist in the response, I simply hand the response off the the developers implemented callback using:

```java
callback.onResponse(call, response);

// or for executeCall:
return Response.success(response.body(), response.headers());
```

Which will still require developers to run the checks again before interacting with the object. We can skip this requirement by instead, if we internally detect there isn't a DirectionsRoute inside the response, invoke the devs `callback.onFaluire()` by passing the onResponse and removing the need to do the checks, thus, the Response coming from onResponse will always include at least 1 directionsRoute. 

The developer would still be using the same default Retrofit Callback as always but we'd be filtering out API errors and passing them to onError rather than onResponse. 

If this sounds like a good idea, we can modify the code to do this and also add this feature to the other modules. Can also be introduced later on since it wont break any APIs.

**Comment by zugaldia** [comment]
Thanks for the context describing the current painpoint. Currently, `onResponse` is invoked whenever we received an HTTP response, regardless of content, and `onFailure` otherwise. The lack of a route, or of a geocoding result (to use another API as an example), looks like a different type of issue. Would it be possible to address this API shortcoming at the Nav SDK level?

**Comment by cammace** [comment]
By rerouting the HTTP response internally, I'm able to add if checks and reroute the response to `onFailure` if the response returns with no route, throwing my own runtime exception. This requires nothing on the user's end and makes `response.body().routes()` nonnull. In any case, we can do this later down the road since it doesn't break any APIs but rather only modifies the behavior of the response.

**Comment by cammace** [comment]
We should be good to close here, Now that we essentially are the middleman between Retrofit and the actual user, we can check and verify values as needed.

**Comment by zugaldia** [comment]
> We should be good to close here, Now that we essentially are the middleman between Retrofit and the actual user, we can check and verify values as needed.

Could you point me at where is this done, in the nav SDK? Where otherwise?

**Comment by cammace** [comment]
Since we need to create the routeoptions we must check if certain values are null, these checks are done in both the execute and enqueue calls inside MapboxDirections class.

**Comment by zugaldia** [comment]
Thanks for the explanation @cammace .
