### ISSUE TITLE
Explore CircleCI Git Tag Job Execution to better support automated releases

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-java#551]
First class tag support for Workflows in CircleCI was announced recently 🎉 
We could take advantage of [CircleCI Git Tag Job Execution](https://circleci.com/docs/2.0/workflows/#git-tag-job-execution) to better support our automated releases and make the process more pleasant/easier.

cc/ @cammace @zugaldia @tobrun

**Comment by cammace** [comment]
Closing since we are tracking this at a higher level for matching release automation throughout all our repos.
