### ISSUE TITLE
LineString parallel offset method

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#554]
While refactoring the GeoJSON module to use AutoValue, I have been referencing Shapely and their GeoJSON support. They have a function called parallelOffset in `linestring.py` which might be useful but I'm not completely sure. Any interest in adding this to this SDK?

cc: @zugaldia

**Comment by zugaldia** [comment]
What does `parallelOffset` do? Would the nav SDK or related products benefit from it?

**Comment by cammace** [comment]
My understanding after re-reading the documentation is that this would provide functionality turf could offer us. Closing.
