### ISSUE TITLE
Port toGeoJSON 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#564]
[toGeoJSON](https://github.com/mapbox/togeojson) is node.js library that allows to convert KML and GPX  files to GeoJSON. Most of Mapbox technologies use GeoJSON though other geographic data formats exist (KML from Google Earth or GPX for GPS traces). Having a way to convert from these formats to GeoJSON in java would be usefull for usage in the Android binding in gl-native.

**Comment by cattcal** [comment]
Any update for this? I need to display a kml on the map. Thanks
