### ISSUE TITLE
Geocoder wikidata

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#57]
Geocoder now includes wikidata information. MAS needs to include getter and setter methods. [API-documentation](https://www.mapbox.com/api-documentation/#response-format)

cc: @zugaldia

**Comment by zugaldia** [comment]
Related geocoding need: https://github.com/mapbox/mapbox-java/issues/59

**Comment by zugaldia** [comment]
Related as well, we need to make sure we're properly handling the `maki` string field now that Maki 3 is live.
