### ISSUE TITLE
Release Mapbox-Java v2.2.4

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#572]
### Release checklist @cammace

- [x] Change version name to `2.2.4` in `gradle.properties`
- [x] Publish `2.2.4` artifact to Maven Central
- [x] Change version name back to `2.3.0-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `v2.2.4` in GitHub
- [x] Update dependencies in the Maps SDK

### Post-release @langsmith

~~- [ ] _If_ there's a new SNAPSHOT version, then update this repo's `README.md` file~~
- [x] Update Javadoc for the MAS docs section
- [x] Update the `constants.js` file in `android-docs` repo so that `compile 'com.mapbox.mapboxsdk:mapbox-android-services:x.x.x'` line is updated in [the Gradle section of the MAS overview page](https://www.mapbox.com/android-docs/mapbox-services/overview/)
- [x] Update the `compile 'com.mapbox.mapboxsdk:mapbox-android-ui:X.X.X'` line in the Android demo app's Gradle file
- [x] Update version # in config files in /help @langsmith
- [x] Update version # in [Store Locator kit](https://github.com/mapbox/store-locator-android)

/cc: @mapbox/android

**Comment by langsmith** [comment]
@cammace , my checkboxes are done. Close when you're done 👍

**Comment by cammace** [comment]
Changelog updated in https://github.com/mapbox/mapbox-java/pull/578
