### ISSUE TITLE
Support API level 14

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#575]
We currently support API level 15 as our min SDK. However, we hear from developers that it'd be useful to lower that requirement to API level 14. This will require changes to some of our dependencies that also require 15+. Let's use this ticket to research whether this is a possibility.

cc: @cammace

**Comment by cammace** [comment]
In 3.0 no all our modules will not have any dependency on Android, therefore, this ticket can be closed. This is also being tracked in the telem repo in https://github.com/mapbox/mapbox-telemetry-android/issues/100.
