### ISSUE TITLE
Support MapboxAccountManager

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#58]
The Mapbox SDK is introducing a [`MapboxAccountManager`](https://github.com/mapbox/mapbox-gl-native/issues/5004) as a centralized place for developers to configure their apps to use Mapbox technology on Android. We want to enable this as well in MAS to handle token management, for ease of use and consistency.

/cc: @bleege

**Comment by cammace** [comment]
I'm thinking we can close this ticket since access tokens are only needed when making API request. This is fairly common practice from what I've seen unless someone else has a better idea?

**Comment by zugaldia** [comment]
Yes - this can be closed. Now that this repo is a pure Java solution this unification across Android products is no longer necessary.
