### ISSUE TITLE
Mapbox 5.1.x not working well on old Androids like Jelly Bean?

### ISSUE THREAD

**Issue by leocarona** [mapbox/mapbox-java#589]
After upgrading Mapbox from 5.0.x to 5.1.x, I began having a few issues on Android 4.1.2, and my project (as well as Mapbox as long as I know) sets minSdkVersion to API 15. 

I've been using custom markers (as suggested [here](https://github.com/mapbox/mapbox-gl-native/issues/3756#issuecomment-181285795) #3756) and it works just fine with Mapbox 5.0.x. Though, after upgrading to Mapbox 5.1.x I began having issues with zoom (double tap does zoom in as excepted, but pinching doesn't work at all), and when a Marker in clicked, rarely a infoWindow opens (I couldn't find a standard of when it usually opens, but most often nothing is happening when a marker is clicked).

**Comment by cammace** [comment]
I have moved your ticket over to the correct repo.
