### ISSUE TITLE
Release Mapbox-Java 2.2.6

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#594]
In preparation for the 0.6.2 release of the Navigation SDK we are releasing a new version of the Mapbox Java SDK. This includes

- Fix for Matrix source and destination returning null rather than the true value [#588](https://github.com/mapbox/mapbox-java/pull/588)
- Add optional locationEngine dependencies [#502](https://github.com/mapbox/mapbox-java/pull/502)

### Release checklist @cammace

- [x] Change version name to `2.2.6` in `gradle.properties`
- [x] Publish `2.2.6` artifact to Maven Central
- [x] Change version name back to `2.3.0-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `v2.2.6` in GitHub
- [x] Update dependencies in the Maps SDK

### Post-release @langsmith

- [x] ~ _If_ there's a new SNAPSHOT version, then update this repo's `README.md` file~
- [x] Update Javadoc for the MAS docs section
- [x] Update the `constants.js` file in `android-docs` repo so that `compile 'com.mapbox.mapboxsdk:mapbox-android-services:x.x.x'` line is updated in [the Gradle section of the MAS overview page](https://www.mapbox.com/android-docs/mapbox-services/overview/)
- [x] Update the `compile 'com.mapbox.mapboxsdk:mapbox-android-ui:X.X.X'` line in the Android demo app's Gradle file
- [x] Update version # in config files in /help @langsmith
- [x] Update version # in Store Locator project

/cc: @mapbox/android

**Comment by zugaldia** [comment]
Are we good to close here?

**Comment by langsmith** [comment]
Yep, all done 🎆 🍾
