### ISSUE TITLE
GeocodingResponse always return zero result

### ISSUE THREAD

**Issue by altaf2892** [mapbox/mapbox-java#599]
> it returns result if i manually set lat long otherwise it Always return zero result 

` LatLng position = map.getProjection().fromScreenLocation(new PointF(dropLocation.getLeft() + (dropLocation.getWidth() / 2), dropLocation.getBottom()));
                    if (map != null) {
                        map.clear();

                    }

                    final com.mapbox.mapboxsdk.annotations.Marker marker = map.addMarker(new MarkerOptions()
                            .position(position)
                            .title("Loading addres"));
                    map.selectMarker(marker);

                    MapboxGeocoding client = new MapboxGeocoding.Builder()
                            .setAccessToken(getString(R.string.mapboxkey))
                            .setCoordinates(Position.fromCoordinates(position.getLongitude(), position.getLatitude()))
                            .setGeocodingType(GeocodingCriteria.TYPE_ADDRESS)
                            .build();

                    Log.e("position",position.getLatitude()+" ,"+position.getLongitude());

                    client.enqueueCall(new Callback<GeocodingResponse>() {
                        @Override
                        public void onResponse(Call<GeocodingResponse> call, Response<GeocodingResponse> response) {
                            List<CarmenFeature> results = response.body().getFeatures();
                            String address = null;
                            if (results.size() > 0) {
                                CarmenFeature feature = results.get(0);
                                address = feature.getAddress() + " " + feature.getText();
                                Log.e("address", address);
                                marker.setTitle(address);
                                // Update Address Pin's InfoWindow With Address
                                if (marker != null) {
                                    marker.setTitle(TextUtils.isEmpty(address) ? "No address found" : address);
                                }
                            } else {
                                if (marker != null) {
                                    marker.setTitle(TextUtils.isEmpty(address) ? "No address found" : address);
                                }
                            }

                        }

                        @Override
                        public void onFailure(Call<GeocodingResponse> call, Throwable t) {

                        }
                    });
`

**Comment by cammace** [comment]
Can you give me a sample request like you did above:
```java
 MapboxGeocoding client = new MapboxGeocoding.Builder()
                        .setAccessToken(getString(R.string.mapboxkey))
                        .setCoordinates(Position.fromCoordinates(position.getLongitude(), position.getLatitude()))
                        .setGeocodingType(GeocodingCriteria.TYPE_ADDRESS)
                        .build();
```

but also include the coordinates? Depending on the region you're in, we might not have the data you need.

**Comment by cammace** [comment]
Stale, closing.
