### ISSUE TITLE
Add fromJson to all API response models

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#606]
Now that we are using AutoValue, the response objects which get created during the serialization of JSON require a type adapter factory which can often be confusing in times when you want to deserialize a JSON string into a DirectionsResponse for example. Doing so without adding the type adapter factory will result in:

```
Failed to invoke public com.mapbox.directions.v5.models.DirectionsRoute() with no args
```

To make this easier, I'm proposing we add a static factory method to all API model classes which would looks something like:

```java
public static DirectionsResponse fromJson(String json) {
  return GsonBuilder().registerTypeAdapterFactory(DirectionsAdapterFactory.create()).create()
      .fromJson(directionsRoute, DirectionsResponse.class);
}
```

cc: @zugaldia

**Comment by zugaldia** [comment]
I like it. If I understand it correctly, this would bring functionality consistent with what we already provide for other types like GeoJSON (https://github.com/mapbox/mapbox-java/blob/master/mapbox/libjava-geojson/src/main/java/com/mapbox/services/commons/geojson/Feature.java#L130-L142). Correct?

**Comment by cammace** [comment]
Exactly, this is inspired by the trouble I ran into when [debugging this](https://github.com/mapbox/mapbox-navigation-android/blob/d8615f799e9c1a02b2006d8a011269d40f8ad797/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationLauncher.java#L47). AutoValue Gson type adapter factory [documentation](https://github.com/rharter/auto-value-gson/blob/master/README.md#factory) for reference.

**Comment by lilykaiser** [comment]
Is this still in progress?

**Comment by jethro-2018** [comment]
This would be great.

**Comment by zugaldia** [comment]
This landed for directions models with https://github.com/mapbox/mapbox-java/pull/854.

@jethro-2018 could you share a bit more about your use case (service, serialization needed, ...)? Thanks!
