### ISSUE TITLE
Out of Memory Adreno GSL

### ISSUE THREAD

**Issue by NonowPoney** [mapbox/mapbox-java#61]
Hello, 

I realized an application like Waze (GPS Nagivation)  with MapBox

But with some devices i have a Out Of Memory like this : 

> 05-10 15:40:52.744: W/Adreno-GSL(11228): <sharedmem_gpumem_alloc_id:1498>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
> 05-10 15:40:52.744: E/Adreno-GSL(11228): <gsl_memory_alloc_pure:2044>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
> 05-10 15:40:52.798: W/Adreno-GSL(11228): <sharedmem_gpumem_alloc_id:1498>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
> 05-10 15:40:52.798: E/Adreno-GSL(11228): <gsl_memory_alloc_pure:2044>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
> 05-10 15:40:52.799: W/Adreno-GSL(11228): <sharedmem_gpumem_alloc_id:1498>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
> 05-10 15:40:52.799: E/Adreno-GSL(11228): <gsl_memory_alloc_pure:2044>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
> 05-10 15:40:52.799: W/Adreno-GSL(11228): <sharedmem_gpumem_alloc_id:1498>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
> 05-10 15:40:52.799: E/Adreno-GSL(11228): <gsl_memory_alloc_pure:2044>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
> 05-10 15:40:52.800: W/Adreno-GSL(11228): <sharedmem_gpumem_alloc_id:1498>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
> 05-10 15:40:52.800: E/Adreno-GSL(11228): <gsl_memory_alloc_pure:2044>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
> 05-10 15:40:52.800: W/Adreno-GSL(11228): <sharedmem_gpumem_alloc_id:1498>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
> 05-10 15:40:52.800: E/Adreno-GSL(11228): <gsl_memory_alloc_pure:2044>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
> 05-10 15:40:52.811: W/Adreno-ES20(11228): <core_glBufferData:1175>: GL_OUT_OF_MEMORY
> 05-10 15:40:52.811: W/Adreno-GSL(11228): <sharedmem_gpumem_alloc_id:1498>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
> 05-10 15:40:52.811: E/Adreno-GSL(11228): <gsl_memory_alloc_pure:2044>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
> 05-10 15:40:52.811: W/Adreno-GSL(11228): <sharedmem_gpumem_alloc_id:1498>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
> 05-10 15:40:52.811: E/Adreno-GSL(11228): <gsl_memory_alloc_pure:2044>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
> 05-10 15:40:52.812: A/libc(11228): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x54 in tid 12921 (Map Thread)
> 05-10 15:41:15.692: W/libc(11228): pthread_create failed: couldn't allocate 1040384-byte stack: Out of memory
> 05-10 15:41:15.692: E/libutils.threads(11228): androidCreateRawThreadEtc failed (entry=0xb6d24a95, res=11, errno=0)
> 05-10 15:41:15.692: E/libutils.threads(11228): (android threadPriority=0)

this occurs after a few minutes of using app.

For information, my application runs with MapBox 3.2.0,

I wonder if people have had this worries, 

Where does this problem come from ?

**Comment by zugaldia** [comment]
@NonowPoney Thank you for the report. This seems like an issue with http://github.com/mapbox/mapbox-gl-native not with this project (we're only at version `1.1.0` and you mention you're using `3.2.0`).

Could you please open a ticket in https://github.com/mapbox/mapbox-gl-native/issues/new instead? Also, note that we've recently released `4.0.1` for the Mapbox Android SDK, you might want to try with the latest version to see if the problem persists. Thanks.
