### ISSUE TITLE
Method lineWidth not found when creating NavigationMapRoute

### ISSUE THREAD

**Issue by turey** [mapbox/mapbox-java#610]
**Platform:**
LG-H871
Android 7.0

**Mapbox Services version:**
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.1@aar') {
        transitive=true
    }
    compile 'com.mapbox.mapboxsdk:mapbox-android-services:2.3.0-SNAPSHOT'
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0-SNAPSHOT'
    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.0-SNAPSHOT') {
        transitive = true
    }

### Steps to trigger behavior

 1. Create the app described in https://www.mapbox.com/help/android-navigation-sdk/
 2. Run the app.
 3. Click on the map.

### Expected behavior
The pin will appear on the map and a route will be drawn to it.

### Actual behavior
E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.NoSuchMethodError: No static method lineWidth(Lcom/mapbox/mapboxsdk/style/functions/CameraFunction;)Lcom/mapbox/mapboxsdk/style/layers/PropertyValue; in class Lcom/mapbox/mapboxsdk/style/layers/PropertyFactory; or its super classes (declaration of 'com.mapbox.mapboxsdk.style.layers.PropertyFactory' appears in /data/app/com.hall.thomas.test-2/split_lib_dependencies_apk.apk:classes19.dex)
at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addNavigationRouteLayer(NavigationMapRoute.java:371)
at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.initialize(NavigationMapRoute.java:179)
at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:156)
at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:135)

**Comment by tarballz** [comment]
I am having this issue as well.

**Comment by cammace** [comment]
Moving this ticket to the correct repo. https://github.com/mapbox/mapbox-navigation-android/issues/437
