### ISSUE TITLE
java documentation missing API

### ISSUE THREAD

**Issue by caopeng000** [mapbox/mapbox-java#618]
**Platform:**
**Mapbox Services version:**
com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.4@aar

### Actual behavior
java documentation missing API，such as  turf.flatten(multiGeometry);，turf.mask(polygon, mask);These api are reflected in the web sdk,Can you add it?

**Comment by cammace** [comment]
Are you requesting we add turf Methods? We are tracking these as separate issues and if you specifically need one, open an individual ticket explaining the reason for needing it and we will try getting it into the SDK as soon as possible. Closing this one since it is unclear what you are wanting.

**Comment by caopeng000** [comment]
I want to implement nested geo fences.How to do it？


![ymgxc bbv s4hwd 7y ybu](https://user-images.githubusercontent.com/7322422/32202405-7a371d54-be17-11e7-85e0-fcfcb3a9efa8.png)

**Comment by cammace** [comment]
I split it off into an individual ticket https://github.com/mapbox/mapbox-java/issues/620, please follow that format for other turf methods when needed
