### ISSUE TITLE
Create util for combining Direction routes together

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#619]
In some occasions, users will need to combine direction routes into one. We can either just do the geometry or add all the other information.

cc: @zugaldia

**Comment by zugaldia** [comment]
In particular we're looking at:

1. A way to create a new `DirectionsRoute` from others. Something like `DirectionsRoute.from(List<DirectionsRoute> routes)` that returns a combined `DirectionsRoute`.

2. Expose not only the encoded geometry (`getGeometry`/`setGeometry` as strings) but also expose the decoded object (e.g. `getGeometryObject`/`setGeometryObject` as GeoJSON).

**Comment by zugaldia** [comment]
@franciskim Would the functionality described on https://github.com/mapbox/mapbox-java/issues/619#issuecomment-340614249 meet your usecase, or would you need something different?

cc: @osana for roadmap prioritization.

**Comment by zugaldia** [comment]
@mapbox/navigation-android Do you currently have any usecases where this functionality could be useful?

**Comment by devotaaabel** [comment]
@zugaldia What exactly would be combined? In your example `DirectionsRoute.from(List<DirectionsRoute> routes)` what would the new `DirectionsRoute` be getting from the list of routes?

**Comment by zugaldia** [comment]
@devotaaabel Thanks for the 👀 - I realize now that the ticket failed to mentioned that this is intended for physically connected routes that are consecutive, so the resulting route would be the natural union of the individual pieces.

In any case, this seems to be an edge case that doesn't need to be covered by the SDK at the moment. The workaround is to use existing APIs to achieve the same result. Something like:

```
ArrayList<Position> resultGeometry;
for (DirectionsResponse response : responses) {
    DirectionsRoute directionsRoute = ((DirectionsResponse) object).getRoutes().get(0);
    
    // Convert the polyline string into a list of Position objects
    List<Position> routePoints = PolylineUtils.decode(directionsRoute.getGeometry(), 6);
    
    // Chop off the first coordinate if appending to existing data, otherwise use entire geometry;
    int startPos = resultGeometry.size() > 0 ? 1 : 0; 

    // Concatenate the route points, removing the first point if we're appendin
    resultGeometry.addAll(startPos, routePoints);
}

// Generate a polyline encoded string from the accumulated points.
String resultGeometryString = PolylineUtils.encode(resultGeometry, 6);
```
