### ISSUE TITLE
Port Turf Mask

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#620]
Takes any type of polygon and an optional mask and returns a polygon exterior ring with holes.

Originally requested by @caopeng000

**Comment by caopeng000** [comment]
This means that you can provide the relevant api it？

**Comment by cammace** [comment]
This means that we will be tracking work on adding this to the SDK here. No timeline on when this will happen but we _do_ accept contributions :wink:

**Comment by caopeng000** [comment]
We are now on this demand is still very important. java sdk there is no other way to achieve this demand, thanks

**Comment by caopeng000** [comment]
：眨眼：

**Comment by zugaldia** [comment]
@caopeng000 Could you tell us a bit more about your usecase?
