### ISSUE TITLE
Crash due to MapboxTelemetry (No virtual method initialize)

### ISSUE THREAD

**Issue by amanzan** [mapbox/mapbox-java#626]
Suddenly I am getting a weird crash without changing anything related to Mapbox. Any help would be really appreciated

**Platform: Android**
**Mapbox SDK version: 5.2.0-beta.3**

### Steps to trigger behavior
 1. Run app

### Expected behavior
No crashes

### Actual behavior
FATAL EXCEPTION: main Process: com.example.myapp, PID: 16817 java.lang.NoSuchMethodError: No virtual method initialize(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Lcom/mapbox/services/android/telemetry/location/LocationEngine;)V in class Lcom/mapbox/services/android/telemetry/MapboxTelemetry; or its super classes (declaration of 'com.mapbox.services.android.telemetry.MapboxTelemetry' appears in /data/app/com.example.myapp-4RgMqGrrEFZc1X5nPn936g==/base.apk:classes84.dex) at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:58) at com.example.myapp.App.onCreate(App.java:128) at 

android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791) at android.app.ActivityThread.-wrap1(Unknown Source:0) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) at android.os.Handler.dispatchMessage(Handler.java:105) at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6541) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

11-02 10:10:35.386 16817-16817/com.example.myapp E/CrashlyticsCore: Failed to execute task. java.util.concurrent.TimeoutException at java.util.concurrent.FutureTask.get(FutureTask.java:206) at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:44) at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:251) at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068) at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063) at java.lang.Thread.dispatchUncaughtException(Thread.java:1953)

**Comment by Danny-James** [comment]
I'm Also Recieveing This Same Error. [#464](https://github.com/mapbox/mapbox-navigation-android/issues/464)

**Comment by cammace** [comment]
```
initialize(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Lcom/mapbox/services/android/telemetry/location/LocationEngine;)V in class 
```

https://github.com/mapbox/mapbox-java/pull/627 should have fixed this issue, can you refresh your dependency cache and try again?

**Comment by cammace** [comment]
Stale, closing.
