### ISSUE TITLE
MapMatching API returns invalid turn-by-turn navigation steps/maneuvers

### ISSUE THREAD

**Issue by jameslshannon** [mapbox/mapbox-java#640]
I'm using the MapMatching API from Android to convert a pre-determined cycling route (from a GPX file) into a routable DirectionsRoute for use in the MapBox Android SDK using parameter steps=true as follows:

```
MapboxMapMatching client = new MapboxMapMatching.Builder()
    .setAccessToken(Mapbox.getAccessToken())
    .setProfile(MapMatchingCriteria.PROFILE_CYCLING)
    .setCoordinates(coords)
    .setSteps(true)
    .build();

retrofit2.Response<MapMatchingResponse> response = client.executeCall();
```

However, despite returning a valid DirectionsRoute object with legs, steps & road names that correspond to the original co-ordinates provided, there are only ever 2 steps per leg and the 2nd step of each leg always contains the maneuver instruction "You have arrived at your nth destination" (where n = integer) or "You have arrived at your destination" with no obvious reason for the difference.

So instead of seeing the expected turn-by-turn instructions for the entire route, the user gets very short instructions from leg to leg and never any turn maneuver icons (other than the 'arriving at destination' one) which results in a very poor navigation user experience as there are effectively no turn-by-turn directions provided.

I assume this isn't the intended behaviour for the navigation steps returned from a MapMatching API call. Is this a known bug or intended behaviour, as whilst the geometry returned is valid, the turn-by-turn navigation instructions are unusable?

Thanks,

James

**Comment by ericrwolfe** [comment]
@jameslshannon thanks for reporting. 

This is an upstream issue with the Map Matching API (https://github.com/Project-OSRM/osrm-backend/issues/4669) and the team is evaluating a potential fix.

cc @coxchapman @miccolis

**Comment by cammace** [comment]
Since this is an issue with the API rather than this specific library, I'm going ahead and closing. Once this is fixed upstream, Mapbox Java should have no issues supporting the correct behavior.
