### ISSUE TITLE
2.2.8 to 2.2.9 upgrade fails during build

### ISSUE THREAD

**Issue by snkashis** [mapbox/mapbox-java#641]
**Platform:** OSX 10.12.6 - Android Studio 3
**Mapbox Services version:** 2.29

### Steps to trigger behavior
1.Include following files in build.gradle

    implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.4@aar'){
        transitive=true
    }

    implementation 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.9'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:2.2.9'

 2.Run debug variant on attached Android device(Moto E 2nd Gen)

### Expected behavior
Build+Run should succeed (and it does on 2.2.8)

### Actual behavior
Build fails with 
Execution failed for task ':app:transformClassesWithAndroidGradleClassShrinkerForDebug'.

Relevant lines look to be 
com/mapbox/mapboxsdk/location/LocationSource.getLastLocation:()Landroid/location/Location; references unknown class member: com/mapzen/android/lost/api/FusedLocationProviderApi.getLastLocation:()Landroid/location/Location;
com/mapbox/mapboxsdk/location/LocationSource.removeLocationUpdates:()V references unknown class member: com/mapzen/android/lost/api/FusedLocationProviderApi.removeLocationUpdates:(Lcom/mapzen/android/lost/api/LocationListener;)V
com/mapbox/mapboxsdk/location/LocationSource.requestLocationUpdates:()V references unknown class member: com/mapzen/android/lost/api/FusedLocationProviderApi.requestLocationUpdates:(Lcom/mapzen/android/lost/api/LocationRequest;Lcom/mapzen/android/lost/api/LocationListener;)V

All Console output
Executing tasks: [:app:assembleDebug]

Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Using the built-in class shrinker for an Instant Run build. Build won't be obfuscated.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
:app:buildInfoDebugLoader
:app:preBuild UP-TO-DATE
:app:extractProguardFiles UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:checkDebugManifest UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:prepareLintJar UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:processDebugGoogleServices
:app:mergeDebugResources UP-TO-DATE
:app:createDebugCompatibleScreenManifests UP-TO-DATE
:app:processDebugManifest
:app:splitsDiscoveryTaskDebug UP-TO-DATE
:app:processDebugResources
:app:generateDebugSources
:app:javaPreCompileDebug
:app:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:packageInstantRunResourcesDebug
:app:transformClassesWithProfilers-transformForDebug
:app:checkManifestChangesDebug
:app:transformClassesWithAndroidGradleClassShrinkerForDebug
-useuniqueclassmembernames is ignored by the built-in class shrinker.
-allowaccessmodification is ignored by the built-in class shrinker.
com/mapbox/mapboxsdk/location/LocationSource.getLastLocation:()Landroid/location/Location; references unknown class member: com/mapzen/android/lost/api/FusedLocationProviderApi.getLastLocation:()Landroid/location/Location;
com/mapbox/mapboxsdk/location/LocationSource.removeLocationUpdates:()V references unknown class member: com/mapzen/android/lost/api/FusedLocationProviderApi.removeLocationUpdates:(Lcom/mapzen/android/lost/api/LocationListener;)V
com/mapbox/mapboxsdk/location/LocationSource.requestLocationUpdates:()V references unknown class member: com/mapzen/android/lost/api/FusedLocationProviderApi.requestLocationUpdates:(Lcom/mapzen/android/lost/api/LocationRequest;Lcom/mapzen/android/lost/api/LocationListener;)V
:app:transformClassesWithAndroidGradleClassShrinkerForDebug FAILED
:app:buildInfoGeneratorDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithAndroidGradleClassShrinkerForDebug'.
> Warnings found during shrinking, please use -dontwarn or -ignorewarnings to suppress them.

**Comment by cammace** [comment]
In 2.2.9 I believe the LOST location provider was increased to the latest. @Guardiola31337 do you have any suggestions on how to resolve this issue?

**Comment by Guardiola31337** [comment]
@snkashis 
Bumping `mapbox-android-sdk` dependenxy to the latest version [`5.2.0`](https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v5.2.0) should fix your issue.

Let us know if it solves your problem.

**Comment by snkashis** [comment]
Yes, builds and runs fine with
```
implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0@aar'){
        transitive=true
    }

implementation 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.9'
implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:2.2.9'
```

**Comment by Guardiola31337** [comment]
@snkashis Great to hear, thanks for the update.

Closing.
