### ISSUE TITLE
Duration of route (and leg) is not equal to the sum of duration annotations

### ISSUE THREAD

**Issue by palto-blubek** [mapbox/mapbox-java#642]
**Platform:** Android
**Mapbox Services version:** `com.mapbox.mapboxsdk:mapbox-android-navigation:2.2.8`

### Steps to trigger behavior

(This is probably more of an API issue, but I'm not sure there's a bugtracker for it?)

When calling `MapboxDirections`, the resulting route has a duration that is always greater than the sum of the duration annotations.

For instance, this call:
```
curl -H 'User-Agent: MapboxJava/2.1.0-SNAPSHOT (5c3deb2) Linux/3.10.0+ (i686)' -H 'Host: api.mapbox.com' --compressed 'https://api.mapbox.com/directions/v5/mapbox/driving-traffic/2.326867,48.851533;2.323004,48.847481?access_token=TOKEN&alternatives=false&geometries=polyline6&overview=full&steps=true&bearings=221.599976,45;&annotations=duration,distance&language=fr'
```
(please replace TOKEN by a valid token)

returns a route with duration `138.7`
and if you take the sum of all duration annotations, you get `129.7`

### Expected behavior

It should be consistent.

### Actual behavior

It is different.

**Comment by cammace** [comment]
This is indeed an API related issue but one that isn't easily resolvable and comes from the precision used for these calculations. The longer the route, the more likely the duration and distance will diverge. One solution that can sometimes help, If, for example, you are running calculations locally using the duration value is to increase precision using `geometries=polyline6` like you already are.

For now, if you need to have matching calculations, you'll need to use some Turf Methods to do the calculations locally thus, giving you far closer precision. These calculations are coming from OSRM, you might find more information in that repo.
