### ISSUE TITLE
MapboxStaticImage - provide option to specify position as LatLng

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-java#65]
We have been using the [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native) for our main apps and our now integrating the static map api. It would be great if we can use the same `LatLng` location objects here to keep consistency. Especially as we built out our support methods based on the `LatLng` and like to re-use those.

**Comment by zugaldia** [comment]
Unfortunately we don't have access to `LatLng` objects from the main SDK in MAS. But what we can do is to add a `setLocation(Position position)` method in addition to the the individual coordinate setters.
