### ISSUE TITLE
Directions test

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#650]
While working on the Navigation SDK I noticed a few issues that should be tested and ensured work properly:

- [ ] null bearing value as a way to skip a coordinate
- [ ] single annotation
- [ ] multiple infinity radiuses getting added correctly
- [ ] directionsError class
- [ ] exclude field in mapboxDirections

**Comment by zugaldia** [comment]
@mghildiy [Contributions](https://github.com/mapbox/mapbox-java/blob/master/CONTRIBUTING.md) are always welcome, please let us know if you have any questions.

cc: @osana
