### ISSUE TITLE
Write test to ensure incorrect routes are handled correctly

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#651]
We should add a fixture to force the directions API to give us an invalid response, this way we know we are handling it correctly. a trip from Australia to New Zealand should cause many issues :)
```json 
https://api.mapbox.com/directions/v5/mapbox/driving-traffic/146.27737562210257,-31.025917567144113;170.7787312265949,-44.043193503705204.json?access_token=<token>&steps=true&overview=full
```

**Comment by mghildiy** [comment]
If this is still open, I can look into it.
