### ISSUE TITLE
Finish writing missing Javadoc

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#653]
There are some classes which are missing Javadoc completely, It would be nice to work with iOS to match up our docs and ensure the APIs exposed are correct. Follow the style guild layed out in this [blog post](http://blog.joda.org/2012/11/javadoc-coding-standards.html) and remember that this repo requires that every public method have a `@since` tag included.

cc: @mapbox/android

**Comment by mghildiy** [comment]
I would take it.
Do you have specific classes in mind to be worked upon?Or I can just start adding Javadoc wherever they are missing?

**Comment by cammace** [comment]
> Do you have specific classes in mind to be worked upon?Or I can just start adding Javadoc wherever they are missing?

You've got it, whereever, we are missing it. Simplist way to find out what's missing is to just run `make javadoc` inside the project root folder and fixing all the errors/warnings.

**Comment by langsmith** [comment]
Current errors <img width="1378" alt="screen shot 2018-08-29 at 8 13 06 am" src="https://user-images.githubusercontent.com/4394910/44797189-6f2afb80-ab63-11e8-93f8-a9fae657b6a4.png">
<img width="1378" alt="screen shot 2018-08-29 at 8 13 01 am" src="https://user-images.githubusercontent.com/4394910/44797191-6f2afb80-ab63-11e8-8e76-defaeeb33277.png">

**Comment by zugaldia** [comment]
@langsmith I think the images are listed in the wrong order, does this mean only 4 `@return` elements are left to have full Javadoc throughout the project?

**Comment by langsmith** [comment]
whoops, wrong order. Yes @zugaldia those 4 are missing. Resolved them in #883
