### ISSUE TITLE
libjava - make ServiceException an unchecked exception

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-java#66]
As the current validations that throw the Service Exception are mostly programming errors, it makes sense to make ServiceException an unchecked exception to avoid unneeded boilerplate in the consuming code.

One exception (no pun intended to this) is the the image size validation as these could potentially be more data driven. Although not checking for 0/negative integers on the caller side might as well be considered a programming error.

**Comment by zugaldia** [comment]
Good point. I like the [approach here](https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html):

>  If a client can reasonably be expected to recover from an exception, make it a checked exception. If a client cannot do anything to recover from the exception, make it an unchecked exception.

We might need to have two different types of exceptions to cover both situations.

**Comment by cammace** [comment]
Would this also apply to the TurfException?
