### ISSUE TITLE
Change namespacing in modules?

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#661]
In 3.0 we have modified the namespacing from `com.mapbox.services.api.directions.v5` (2.x) to `com.mapbox.directions.v5` (3.x) with no reason other than not having the versions collide causing issues importing. Do we want to revisit this and modify them before the first beta release?

cc: @zugaldia @Guardiola31337

**Comment by zugaldia** [comment]
_If_ we ultimately need to change the namespace to avoid collisions with pre 3.x classes, I'd like to do it in a consistent manner easy to remember. For example, we could rename the 2.x namespace `com.mapbox.services.api.directions.v5` to `com.mapbox.services3.api.directions.v5` in 3.x, and so on (i.e. adding a number to the root package a la OkHttp - `okhttp3.OkHttpClient`).

**Comment by Guardiola31337** [comment]
Fixed via https://github.com/mapbox/mapbox-java/pull/664

Closing.
