### ISSUE TITLE
Update /api-documentation

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#684]
The documentation on `mapbox.com/api-documentation` will need to be updated to reflect the 3.0 changes.

**Comment by langsmith** [comment]
For example, in https://www.mapbox.com/api-documentation/?language=Java#directions

![screen shot 2018-07-16 at 4 39 33 pm](https://user-images.githubusercontent.com/4394910/42788856-e334b68e-8916-11e8-8af5-3da50f2e8edd.png)
