### ISSUE TITLE
Add Geocoder geometry interpolated field

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#697]

**Comment by tobrun** [comment]
Could you add some context to this issue?

**Comment by cammace** [comment]
Sorry for neglecting to put info on this one, originally was just a reminder to myself to add it. 

Inside the CarmenFeature object, there is now an additional field called `geometry.interpolated` to go along with the `geometry.type`, `geometry.coordinates`, etc. The documentation gives this description for it: A boolean value indicating if an address is interpolated along a road network. This field is only present when the feature is interpolated. This field is optional (nullable).

https://www.mapbox.com/api-documentation/#response-object

cc: @osana
