### ISSUE TITLE
Util to convert MapMatchingMatching object to DirectionsRoute

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#705]
if a user wants to convert a MapMatchingMatching object to a DirectionsRoute, they have to manually construct the directionsRoute using it's builder. It would be nice if MapMatchingMatching offered a `toDirectionsRoute()` api.

**Comment by osana** [comment]
DirectionRoute could be generated as follows:
```  
public DirectionsRoute toDirectionRoute() {
    return DirectionsRoute.builder()
      .legs(legs())
      .geometry(geometry())
      .weightName(weightName())
      .weight(weight())
      .duration(duration())
      .distance(distance())
    .build();
  } ```

The only question remains how routeOptions could generated. As @danesfeder  pointed out we might need to do Equivalent of https://github.com/mapbox/mapbox-java/blob/master/services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java#L192-L217

cc @cammace @ivovandongen

**Comment by danesfeder** [comment]
In a re-routing scenario (in the navigation UI library) we use all of the values from `RouteOptions` to make the same type of directions request as the one that requested the previous `DirectionsRoute`
