### ISSUE TITLE
Geocoding: wrong fallback language both for searching & displaying

### ISSUE THREAD

**Issue by dts-ait** [mapbox/mapbox-java#715]
I have a problem with the geocoding API being too eager on using English.

I try to get geocoding results in German using either their untranslated name (which is in German for my area of interest in Austria) or name:de (if present in OSM). Therefore I use .setLanguages("de") when setting up the MapboxGeocoding instance:

``new MapboxGeocoding.Builder().setAccessToken(Mapbox.getAccessToken()).setLocation(queryString)
.setCountry("at").setLanguages("de").setBbox(15.9190264, 47.9604263, 16.8154602, 48.4575424).build();``

I want to clarify my problem with these two OSM objects:
- a park with only a name tag: https://www.openstreetmap.org/way/28272436 (Schönbornpark)
- a museum with both name and name:en tags: https://www.openstreetmap.org/node/666750600 (Volkskundemuseum)

**Problem with search**
Searching for the park using its name works as expected. But when searching for "Volkskundemuseum" (its German name and normal name-tag) the museum does not show up in the results. When searching for its English name it does.

**Problem with result text for displaying**
What I expect is that the CarmenFeature.getPlaceName() in the search results look like this:
- Schönbornpark, Josefstadt, Wien 1080
- Völkerkundemuseum, Laudongasse 15-19, Josefstadt, Wien 1080

Again, for the park this works fine, but for the museum the English name is returned:
- Austrian Museum of Folk Life and Folk Art, Laudongasse 15-19, Josefstadt, Wien 1080

**Possible solution**
In case this behaviour is not due to a misconfiguration of my MapboxGeocoding instance I would propose that in case setLanguages() is used the following should happen:
- for displaying: the names should be extracted by first checking if a 'name:<language>' is present and if not to fall back to 'name' (not 'name:en').
- for searching: either use the same logic as for displaying - or maybe even better: use all available name tags, i.e. all translations, for searching

**Comment by zugaldia** [comment]
Hey @dts-ait thanks for the report. I'm trying to understand if this is an issue with the Java Geocoding client which is part of this project, or if this is a behavior you're observing with our API product. Could you try repeating the same queries on our [API playground](https://www.mapbox.com/api-playground) and see if in that case you obtain the expected results instead? This would help us figure out Mapbox team to follow up, thanks!

**Comment by dts-ait** [comment]
Hello @zugaldia, thank you for following up on this issue. I can reproduce the problem as elaborated above with the API playground.

**Comment by osana** [comment]
moved to mapbox/geocoading-feedback for further triage (see above)

**Comment by dts-ait** [comment]
@osana could you provide a link to the new issue? Thank you

**Comment by osana** [comment]
@dts-ait we are tracking this issue internally and will report here once we get more information from the team working on geocoding.
