### ISSUE TITLE
Release 2.2.10

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#728]
This is a bug fix release for the Mapbox Java 2.x.x series which fixes the following:

- Updates OkHttp to `3.10.0`
- moves internal method previously used in OkHttp and places it directly into telemetry package.

### Release checklist

- [x] Change version name to `2.2.10` in `gradle.properties`
- [x] Publish `2.2.10` artifact to Maven Central
- [x] Change version name back to `2.3.0-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `v2.2.10` in GitHub
- [x] Update dependencies in the Maps SDK

### Post-release @langsmith

- [x] ~_If_ there's a new SNAPSHOT version, then update this repo's `README.md` file~
- [x] Update Javadoc for the MAS docs section
- [x] Update the `constants.js` file in `android-docs` repo so that `compile 'com.mapbox.mapboxsdk:mapbox-android-services:x.x.x'` line is updated in [the Gradle section of the MAS overview page](https://www.mapbox.com/android-docs/mapbox-services/overview/)
- [x] Update version # in config files in /help @langsmith
- [x] Update version # in cn @langsmith
- [x] Update version # in Studio Preview @langsmith
- [x] Update version # in pthfndr @langsmith
- [x] Update version # in [Store Locator kit](https://github.com/mapbox/store-locator-android)
- [x] Update version # in [mapbox.cn/android-sdk](https://www.mapbox.cn/android-sdk/)  _note:_ it lives in `/www.mapbox.com` @langsmith
- [x] Update version # in [plugins](https://github.com/mapbox/mapbox-plugins-android) @langsmith
- [x] Colleen fyi @colleenmcginnis 

/cc: @mapbox/android

**Comment by langsmith** [comment]
Do all of the projects need to be updated to 2.2.10 @cammace @osana ?  I'm thinking no and that it's fine to keep everything at 3.0.0-beta.3 . Let me know though...

**Comment by cammace** [comment]
The Javadoc should be the only thing that needs to be added to `android-docs`. Since it's a 2.2.10 you'll want to checkout `mas-2.x.x` branch -> open `gradle.properties` -> temporarily change the version to `2.2.10` -> Run `make javadoc` from the root project folder -> do the normal process of moving each of the 7 produced javadocs to an `android-docs` branch.

**Comment by langsmith** [comment]
All done 🎉 🍾
