### ISSUE TITLE
Remove Mapbox Brand Colors

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-java#73]
Mapbox SDKs shouldn't contain Mapbox's brand colors from the [Base Styleguide](https://www.mapbox.com/base/) as they're for Mapbox projects and branding.  While it's totally cool for apps and Web sites to make use of them on their own, the SDKs shouldn't provide them as a supported resource as "they could change at any minute and include some styles specific to our brand."

https://github.com/mapbox/mapbox-java/blob/25278b4bba1b4db642fec3e248944edd4dc29cd3/libandroid/lib/src/main/res/values/colors.xml#L4-L22

**Comment by zugaldia** [comment]
@bleege good catch, this would be fixed in v1.2.0.
