### ISSUE TITLE
Add Polylabel support on the Java SDK

### ISSUE THREAD

**Issue by grillorafael** [mapbox/mapbox-java#742]
Hi!

I'm currently using Mapbox GL sdk and building a tiny vector tile server for my polygon database. My server is using Scala/Java at the moment and I was looking for an implementation of `Polylabel` for java. 

I think this library is probably the right place to have so I would like to know if there are any plans to add support to it in the near future.

Best, Rafael.

**Comment by zugaldia** [comment]
Hey @grillorafael, thanks for your note. If I understand correctly, you're suggesting a port of [polylabel](https://github.com/mapbox/polylabel) to Java, right? If so, could you also tell us a bit more about your use-case?

**Comment by grillorafael** [comment]
Hi @zugaldia yes.

We have a tile server of polygons and the polygons have names contained. Would be good to calculate the label position through this method and return as a layer within the tile server. To display similarly to how the vector layers native to mapbox display

**Comment by zugaldia** [comment]
@grillorafael Thank you for the extra information - we're currently prioritizing work around Turf so I don't see getting to Polylabel short term, we'll post back to this ticket if that changes.

**Comment by mghildiy** [comment]
If objective is elaborated a little bit more, may be I can chip in.

@grillorafael , @zugaldia

**Comment by grillorafael** [comment]
The use case is:

We rolled out our own Mapbox Vector Tile server to deliver our own GIS database info. We currently use Mapbox to render and  https://github.com/wdtinc/mapbox-vector-tile-java to generate the protobufs.

We would also like to add to our server the labels for our elements. Therefore having polylabel in java implementation would allow to return a better location of the label.
