### ISSUE TITLE
onProgressChange not working

### ISSUE THREAD

**Issue by A1ecm** [mapbox/mapbox-java#745]
I have an onProgressChange method that just isn't getting called when my progress is is changing.
This is my code:
`        @Override
        public void onProgressChange (Location location, RouteProgress routeProgress){
            Toast.makeText(getBaseContext(), "Progress changing ", Toast.LENGTH_SHORT).show();
            Toast.makeText(getBaseContext(), "Distance remaining: " + stepDistanceRemaining, Toast.LENGTH_SHORT).show();
            if (stepDistanceRemaining < 50) {
                Log.i(TAG, "NextStepComing");
                sendManeuver(routeProgress);
            }
        }
` 
While troubleshooting i also found that the onLocationChanged method isn't working either.

**Comment by danesfeder** [comment]
Hey @A1ecm, how are you adding this listener?  Can you provide a code snippet?  Also, which version of the SDK are you using?

**Comment by A1ecm** [comment]
I just have this method written. Is that nog enough? Do I have to call it somewhere? I'm using version 5.5.0
