### ISSUE TITLE
Release 3.0-beta.4

### ISSUE THREAD

**Issue by osana** [mapbox/mapbox-java#750]
**A few weeks have passed since the last beta release of 3.0. Quite a few bugs have been squashed since then including:**
- Make GeometryCollection implement Geometry
- Turf functions rename to reflect changes in turfjs.org
- Add type and modifier to BannerText
- Add Degrees and Driving Side to BannerText 
- IAE: Unexpected char when making directions request
- Leaking some unnecessary dependencies to the end users
- restricted and tunnel values added to the exclude criteria
- added baseUrl to RouteOptions
- Make getOkHttpClient synchronized

### Release checklist @cammace

- [x] Change version name to `3.0.0-beta.4` in `gradle.properties`
- [x] Publish `3.0.0-beta.4` artifact to Maven Central
- [x] Change version name back to `3.0.0-SNAPSHOT`
- [x] Update `CHANGELOG.md`
- [x] Tag `v3.0.0-beta.4` in GitHub
- [x] Update dependencies in the Maps SDK

### Post-release @langsmith

- [x]  ~If there's a new SNAPSHOT version, then update this repo's `README.md` file~
- [x] Update Javadoc for the MAS docs section
- [x] Update the `constants.js` file in `android-docs` repo so that `compile 'com.mapbox.mapboxsdk:mapbox-android-services:x.x.x'` line is updated in [the Gradle section of the MAS overview page](https://www.mapbox.com/android-docs/mapbox-services/overview/)
- [x] Update the demo app
- [x] Update version # in config files in /help @langsmith
- [x] Update version # in Store Locator project
- [ ] Update version # in Studio Preview
- [x] Update version # in cndocs in /help

/cc: @mapbox/android

**Comment by langsmith** [comment]
@osana , stable 3.0.0 is about to go out, so the Studio Preview checklist item above is now stable. Studio Preview will get stable 3.0.0

Close this ticket?
