### ISSUE TITLE
Method LineString.fromPolyline divides coordinates by 10

### ISSUE THREAD

**Issue by vicobz** [mapbox/mapbox-java#752]
#### Expected Behavior

When I call `fromPolyline(geometry, PRECISION_6)` method from `LineString` class in order to parse a geometry String into a list of features to update a GeoJson source, I'm expecting the resulting `LineString` object to render accurately the coordinates held by this geometry.

#### Current Behavior

All coordinates values held by the resulting `LineString` object are divided by 10.
For example, `[2.2862036, 48.8267868]` is resulting in `[0.22862036, 4.88267868]`.

#### Steps to Reproduce

Call the above method `fromPolyline`.

#### Context (Environment)
I'm using `com.mapbox.mapboxsdk:mapbox-android-sdk:5.5.0` version on Android O with OnePlus 5 concurrently with several Mapbox plugins (last releases).

This could be related to #353.

**Comment by mghildiy** [comment]
Can you provide your geometry string?

**Comment by vicobz** [comment]
@mghildiy Not exactly the same as when I wrote the issue although quite equivalent: `qn_iHgp}LzCy@xCsAsC}PoEeD_@{A@uD_@Sg@Je@a@I_@FcAoFyGcCqFgQ{L{CmD`

**Comment by cammace** [comment]
We use this static factory [pretty heavily](https://github.com/mapbox/mapbox-navigation-android/search?utf8=%E2%9C%93&q=linestring.from&type=) in the Mapbox Navigation and haven't noticed any issues with the geometric Points being off. If you are using the latest beta of this library and still having issues, maybe something to do with your Locale?

**Comment by vicobz** [comment]
@cammace I'm using the latest beta, will try to investigate on this when I get some time. About my `Locale`, to what extent can this affect the conversion of polylines ?

**Comment by osana** [comment]
Added tests did not show any problems. Closing
