### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by mghildiy** [mapbox/mapbox-java#754]
I cloned the repo for this project,and run 'gradle build' command on windows platform:

I get a character encoding issue for line number 72 for LegStep.java. Asked for solution  [here](https://stackoverflow.com/questions/49344937/file-encoding-issue-in-gradle-build/49344979?noredirect=1#comment85690076_49344979).
To move ahead, I just removed the characters causing the issue.

Tried to build again, but this tile got too many check style issues.

**Comment by osana** [comment]
@mghildiy  Thank you for reporting the issue. 
A couple of notes:
Please run `./gradelw build` command instead.

There are seem to be several checkstyle errors that prohibit command line build to run to completion. I will create a PR to fix this.

**Comment by osana** [comment]
@mghildiy  you should be able to build the project from command line using:
```./gradlew assemble```
