### ISSUE TITLE
Include ProGuard instructions in readme

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#755]
Since the libraries we release are `.jar` files, they don't include ProGuard rules file which would normally be appended to an android apps proGuard file. We should add a section in the readme which specifies exactly what to add in the end users proguard file for each library.

cc: @langsmith @osana

**Comment by langsmith** [comment]
Related https://github.com/mapbox/mapbox-android-demo/issues/649

**Comment by LukasPaczos** [comment]
Every project using `mapbox-java` should keep the `proguard` rules up-to-date with the upcoming readme section in order for it to build.

/cc @mapbox/android

**Comment by zugaldia** [comment]
Noting that though the README was never updated, Mapbox SDKs are including ProGuard rules for this project that can be used as a good reference to other projects. Recent example from the Maps SDK: https://github.com/mapbox/mapbox-gl-native/pull/13103.
