### ISSUE TITLE
Android Directions API: mistake in url call due to locale String#format

### ISSUE THREAD

**Issue by Bentipa** [mapbox/mapbox-java#761]
There is a problem in the String#format function, used to format the long and lat into the backend call url.

#### Expected Behavior
The URL should look like this:
...directions/mapbox.driving/11.904957,48.289594;11.890870,48.297570.json

#### Current Behavior
...directions/mapbox.driving/11,904957,48,289594;11,890870,48,297570.json

#### Possible Solution
To make this work you should pass the Locale to the format function:
String.format(Locale.US, obj, args);

#### Steps to Reproduce
Use the Method in e.g. Germany 

I didn't find an android repo so it's maybe wrong here ^^

**Comment by cammace** [comment]
This has been reported before and I believe I've previously made the fix for this. Can you confirm your using the latest beta?

**Comment by Bentipa** [comment]
I looked into the repo and there was only one version so I don't know if it's the latest.
    implementation('com.mapbox.mapboxsdk:mapbox-android-directions:1.0.0@aar') {
        transitive = true
    }

**Comment by cammace** [comment]
This is an extremely old version of our directions API/SDK. Instead, use 

```groovy
implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:3.0.0-beta.4'
```
