### ISSUE TITLE
Test missing for public static method in PolylineUtils.java

### ISSUE THREAD

**Issue by mghildiy** [mapbox/mapbox-java#766]
Going through the code, I found private static methods not having direct tests(they may be called from context of some other test though).Like this one in PolylineUtils.java:

private static double getSqSegDist(Point point, Point p1, Point p2)

Would it hurt if we change access specifier to default,and then have such methods tested directly?
If its agreed upon, I can take this.

@cammace

**Comment by tobrun** [comment]
Would it be possible to test the [public method](https://github.com/mapbox/mapbox-java/blob/113a6b46512dfad42e2b024eaf83765eb16a9a32/services-geojson/src/main/java/com/mapbox/geojson/utils/PolylineUtils.java#L188) instead?

**Comment by mghildiy** [comment]
Sure.Public methods should be first priority.

**Comment by mghildiy** [comment]
Hi,

I have a query here.
PolylineUtils.getSqDist() method would come into picture when I try to write test. This method,as name suggests, gives square of the distance between 2 input points. It uses Euclidean distance formula. But we are dealing with lat-long coordinates. So doesn't it make distance formula used a misfit here?

**Comment by cammace** [comment]
The Polyline Utils has methods ported over from other open source libraries. Mainly the [android-maps- utils](https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/PolyUtil.java) for encoding/decoding a linestring and the simplify.js project for simplifying linestrings. I'd recommend checking there first to see how testing's being done. If we are missing any test found in those projects directly related to the PolylineUtils class, we surely would love to port them over :)

**Comment by mghildiy** [comment]
Some google research tells that tolerance is basically expressed in pixels.

**Comment by mghildiy** [comment]
Hi,
I have points in raw form in a .txt file(got them from test for simplify.js). I need to create List<Point> from it.
Is there already a method implemented to do this?
And then I would also need to compare output Points with another list of points. It may also be implemented somehow already.

@tobrun 
@cammace 
@zugaldia

**Comment by mghildiy** [comment]
As I wrote the test, I found that output of the simplification algorithm is different from the expected output(which I got from test for simplify.js) for two points.
It seems to me expected output is not correct, because the 2 points which are different are not in input point list.Algorithm doesn't introduce any new point, it just removes/retains points. So output may be different in terms of number of points or point retained but there is no question of a totally new point in the output.

**Comment by tobrun** [comment]
Not sure if I completely follow but to move this issue forward could you:
 a) track down where the issue occurred
 b) reproduce with a test
 c) fix the issue and thus making the test pass

Thank you for contributing and making mapbox-java better!
