### ISSUE TITLE
getAddress() isn't working

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#77]
trying `getAddress()` like so:

    response.body().getFeatures().get(i).getAddress()

returns a null or empty string. Doesn't look like [the API](https://www.mapbox.com/api-documentation/#response-format) has this field anymore.

cc: @zugaldia

**Comment by cammace** [comment]
Further investigating, it seems to work when reverse geocoding. Closing as this is an issue with the geocoder API, if it's an issue at all.

**Comment by zugaldia** [comment]
@cammace does this need any documentation work on our side to make this clearer to MAS users?
