### ISSUE TITLE
Isolines (Contours)

### ISSUE THREAD

**Issue by NataliaSamoilovich** [mapbox/mapbox-java#778]
Hello.
We are using your sdk for offline maps functionality. We have our own provider of tiles.
Our app is for fishmen. We have coordinates and deeps for lakes in it. And we need to create a map with contours for these deeps and appropriate coordinates.
Example pic: http://big-okun.ru/wp-content/uploads/2016/04/suhodolskoe1-02-00.png

Could you suggest any solution of this task?

Thanks, 
Natali

**Comment by langsmith** [comment]
Hey @NataliaSamoilovich ,

I don't think we're at the point where we can support this for offline. However, for the time being, you should check out the rainfall timelapse example in our Android demo app 

https://github.com/mapbox/mapbox-android-demo/blob/tvn-update-dds-examples/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/AddRainFallStyleActivity.java

![ezgif com-resize](https://user-images.githubusercontent.com/4394910/38147673-49373dd0-3421-11e8-9be4-19eb6065397d.gif)

You have your data and could make stacked `FillLayer`s for each bathymetry color level that you want. The numbers in your sample screenshot could be done with a `SymbolLayer`.

**Comment by langsmith** [comment]
I also made [this ticket](https://github.com/mapbox/mapbox-android-demo/issues/668) in our Android demo app repo. Conversation can continue over there. Closing this ticket because it's not a Mapbox Java SDK issue.
