### ISSUE TITLE
Increase test coverage of webservice libraries

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#784]
One of the reasons why we had to patch up the 3.0.0 release with 3.0.1 is that we didn't have any tests for validating the models received as result from our webservice. To protect us from similar regressions we need increase the reach of out testsuite and validate gson parsing for our webservice libraries. Atm we tests two things: 
  - validating creation and mocking webservice calls (eg. [MapboxDirectionsTest](https://github.com/mapbox/mapbox-java/blob/master/services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java)). 
  - pulling in fixtures (eg. [geocoding](https://github.com/mapbox/mapbox-java/blob/master/Makefile#L53))

I'm suggesting adding another layer of testing by loading the result from the fixtures inside the respective model object. While we could validate each field with its value, these tests will become a pain to write and maintain. Therefor I'm suggesting using reflection on the model objects and iterating its fields to validate if we didn't receive default values (eg. null/empty string?). If we received a a default value, this will indicate there is an issue with parsing (eg. missing `@SerializedName`).

cc @osana @danesfeder @zugaldia

**Comment by zugaldia** [comment]
The reflection idea is interesting. I'm cc'ing @electrostat here because we're starting to think of a similar approach to test the schema in https://github.com/mapbox/mapbox-events-android.

**Comment by mghildiy** [comment]
I am in for any kind of test related activities.Please let me know.
Would love to contribute to main development too, but some bureaucratic issues are involved.

**Comment by zugaldia** [comment]
@mghildiy Go for it, what would be your approach to tackle this issue?

**Comment by tobrun** [comment]
flagging that my WIP in #785 didn't turn out as I hoped, looking forward to your approach here @mghildiy

**Comment by mghildiy** [comment]
Name a file I can experiment with.
