### ISSUE TITLE
Update navigation icons with new release

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#79]
Ref: https://github.com/mapbox/directions-icons

**Comment by cammace** [comment]
Is this still something that needs to be done in MAS or can we close this?

**Comment by zugaldia** [comment]
We already have them as part of the sample app in https://github.com/mapbox/mapbox-java/tree/master/mapbox/app/src/main/res/drawable. I'd like to update them with the latest version. Not a release blocker.

**Comment by zugaldia** [comment]
Reading https://github.com/mapbox/mapbox-java/issues/127 and wondering if it'd make sense to have an icons-specific module.

**Comment by zugaldia** [comment]
Closed via https://github.com/mapbox/mapbox-java/issues/313.
