### ISSUE TITLE
java.awt.Color is unresolved on Android

### ISSUE THREAD

**Issue by freszu** [mapbox/mapbox-java#790]
java.awt.Color is unresolved on Android.
It is being used in a few places since 3.0 for example in StaticMarkerAnnotation class.
#### Expected Behavior

For support on android platform awt packages rather should be avoided.
#### Current Behavior

Unresolved reference.
#### Steps to Reproduce

1. Create new app
2. Add mapbox dependencies
3. 
```
private fun createMarker(position: Position): StaticMarkerAnnotation? {
        return StaticMarkerAnnotation.builder()
            .lnglat(Point.fromLngLat(position.longitude,position.latitude))
            .color(java.awt.Color) //unresolved
            .name(Constants.PIN_LARGE)
            .build()
    }
```

#### Possible Implementation

Revert to old way of passing colors with strings or create own mapbox wrapper for colors.

**Comment by osana** [comment]
Thank you for reporting this. color() on the Builder should be changed to take either hex value for color, and maybe another version that would take r, g, b

@cammace
