### ISSUE TITLE
Android Navigation route get ssl error

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-java#795]
_Originally opened in Navigation repo: https://github.com/mapbox/mapbox-navigation-android/issues/867_

Looks like a timeout while trying to hit the Directions API in China.

### Steps to trigger behavior

 1. request route api in Navigation 
 2. logcat show Failed to load sprite: failed to connect ssl Failed to load source traffic: SSL handshake timed out
 I think maybe the SSL timeour, we are in China, what is problem?

**Comment by cammace** [comment]
Tagging @osana to investigate further into this issue. One thing to note is that the base URL can be changed to hit our `.cn` endpoint. This will also require getting a China specific access token.

**Comment by danesfeder** [comment]
Yeah thanks @cammace.  This doesn't look like an issue on our side https://github.com/mapbox/mapbox-navigation-android/issues/867#issuecomment-382604626 - going to go ahead and close.
