### ISSUE TITLE
Port Turf line-slice-along

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-java#799]
Original documentation is [here](http://turfjs.org/docs#lineSliceAlong) and code is [here](https://github.com/Turfjs/turf/tree/master/packages/turf-line-slice-along/).

> Takes a line, a specified distance along the line to a start Point, and a specified distance along the line to a stop point and returns a subsection of the line in-between those points.
>
> This can be useful for extracting only the part of a route between two distances.

Turf `lineSliceAlong` is now needed for inside the Navigation SDK 👀 https://github.com/mapbox/mapbox-navigation-android/issues/604#issuecomment-382365153

cc @osana

**Comment by cammace** [comment]
Really, this turf method is just a combination of two turf methods we already offer, PointOnLine and LineSlice. This should be rather easy to add to the `TurfMisc` class.
