### ISSUE TITLE
button into popup or snippet

### ISSUE THREAD

**Issue by navarrete0** [mapbox/mapbox-java#80]
Hello, i want to know if i can insert a button with an event into a popup or in the snippet parameter, becouse i cant see it in documentation, issues or code.

Thanks you very much,
Diego.

**Comment by zugaldia** [comment]
@navarrete0 If you're referring to adding a button within a map InfoWindow, you could always create a custom Android View inside an adapter. You have an example of this in action in [`InfoWindowAdapterActivity`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/infowindow/InfoWindowAdapterActivity.java).

Closing this ticket as this isn't the right repo anyway, if you have any other issues, please follow up in https://github.com/mapbox/mapbox-gl-native.

/cc: @cammace
