### ISSUE TITLE
Detect a type of maneuver?

### ISSUE THREAD

**Issue by atomike-toxic** [mapbox/mapbox-java#801]
I would like to check a condition when the route indicates to turn left or right. I use mapbox as a navigation SDK.

In their technical documentation, he tells us that we can use StepManeuver object:

Example:

```
{
  "bearing_before": 299,
  "bearing_after": 202,
  "type": "turn",
  "modifier": "left",
  "location": [
    13.424671,
    52.508812
  ],
  "instruction": "Turn left onto Adalbertstraße"
}
```
What interests me is the value "modifier" which can be associated with "left" or "right".

So I would like to create a condition "if turn left then [...]" and "if turn right then [...]". But I do not know if this is possible and I do not know how to do it, thank you very much for your help.

**Comment by zugaldia** [comment]
cc: @mapbox/navigation-android for your input.

**Comment by danesfeder** [comment]
Hey @atomike-toxic, yeah this is definitely possible:

In the navigation SDK, you can access route data along the `DirectionsRoute` with the `RouteProgress` object provided by a `ProgressChangeListener`:

```
navigation.addProgressChangeListener(new ProgressChangeListener() {
        @Override
        public void onProgressChange(Location location, RouteProgress routeProgress) {
          LegStep upcomingStep = routeProgress.currentLegProgress().upComingStep();
          if (upcomingStep.maneuver().modifier().contains("left")) {
            // Do left turn work 
          }
          if (upcomingStep.maneuver().modifier().contains("right")) {
            // Do right turn work 
          }
        }
      });
```

In the future, if you have other questions about implementing our SDKs, please direct them to https://stackoverflow.com/questions/tagged/mapbox.  We keep an eye on these questions as well.  This way your questions have better visibility to other developers who may be experiencing the same problem.
