### ISSUE TITLE
MapMatching to DirectionsRoute conversion uses coordinates for RouteOptions

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-java#803]
When generating [`RouteOptions`](https://github.com/mapbox/mapbox-java/blob/master/services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java#L208) from a map matching response, we use the coordinates that were used to originally make the request. 

Map matching has concepts of coordinates as well as waypoints.  In order for `RouteOptions` to be properly consumed in the navigation SDK, we will need the waypoints rather than the larger (possibly) list of coordinates.

The problem is waypoints are optional when making map matching requests, so we may not have a list to be used for the `RouteOptions`.  If this is the case, I think it may be safe to take the first and last coordinate from the coordinates list.  

cc @osana @1ec5 @bsudekum (for how / if this is handled in the swift library)

**Comment by 1ec5** [comment]
Map Matching API support was implemented in mapbox/MapboxDirections.swift#236.

> The problem is waypoints are optional when making map matching requests, so we may not have a list to be used for the `RouteOptions`.  If this is the case, I think it may be safe to take the first and last coordinate from the coordinates list.  

According to [this documentation](https://www.mapbox.com/api-documentation/#retrieve-a-match), if `waypoints` is omitted from the request, then all coordinates are treated as waypoints in the response.

**Comment by bsudekum** [comment]
> As far as I can tell, MapboxDirections.swift no longer enforces any waypoint limits statically on the client side.

This is correct.

**Comment by danesfeder** [comment]
Per documentation added in https://www.mapbox.com/android-docs/navigation/overview/map-matching/, we've defined a way to use map matching with navigation (also aligned with iOS).  This work is no longer needed.
