### ISSUE TITLE
Mapbox direction is not working

### ISSUE THREAD

**Issue by nomanr** [mapbox/mapbox-java#81]
Hi there,
I am trying to use mapbox here in Pakistan but I am unable to get any directions here.
What I am doing is, I click on anywhere in map and get two `Positions`.
Response is 200 but I am not represented with any Duration, Directions, Distance and Polyline points. Everything is zero

Here's the code snippet

```
 MapboxDirections client = new MapboxDirections.Builder()
                .setAccessToken(getStringRes(R.string.mapbox_acces_token))
                .setOrigin(origin)
                .setDestination(destination)
                .setProfile(DirectionsCriteria.PROFILE_DRIVING)
                .setSteps(true)
                .build();

        client.enqueueCall(new Callback<DirectionsResponse>() {
            @Override
            public void onResponse(Call<DirectionsResponse> call,
                                   Response<DirectionsResponse> response) {
                LOG(TAG, "response code : " + response.code());
                if (response.body() == null) {
                    Log.e(TAG, "No routes found, make sure you " +
                            "set the right user and access token.");
                    return;
                }

                currentRoute = response.body().getRoutes().get(0);
                drawRoute(currentRoute);
            }
```

Also when I use autocomplete, I only get results from USA?? 
Another problem is whenever I click on map and try to reverse geocode it, It doesn't respond in any POIs but just name of the City. 

Thanks

**Comment by cammace** [comment]
Glad to hear you are using Mapbox Android Services for your directions/geocoding needs. For future questions please contact us through [this page](mapbox.com/contact) for a quicker response. To answer your questions:

1. **Direction not working**: I will need more information to help you troubleshoot this if the problem still occurs but this error is typically caused when you don't switch around your latitude, longitude values. The `position` should look like this: `Position.fromCoordinates(Longitude, Latitude);`.

2. **Geocoder not working**: POI and address data is only available in certain countries, here's [a coverage map](https://www.mapbox.com/geocoding/#coverage) showing the countries we have data for. I'd like to point out that we are adding new countries rapidly into our dataset.

I hope this solves the issues you're having!
