### ISSUE TITLE
Add toJson consistently to all API response objects

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#814]
Some objects like the [geocoding response](https://github.com/mapbox/mapbox-java/blob/master/services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/models/CarmenFeature.java#L286) include a `toJson` method which makes the response easily serializable and to log. However, other responses like [`DirectionsResponse`](https://github.com/mapbox/mapbox-java/blob/master/services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsResponse.java) do not include one.

Let's add a `toJson` method to all API response objects.

Related: https://github.com/mapbox/mapbox-java/issues/662.

**Comment by lilykaiser** [comment]
Is this still in progress?

**Comment by zugaldia** [comment]
I believe this is still an issue, our APIs should be consistent across services.
