### ISSUE TITLE
Create static map with clusters

### ISSUE THREAD

**Issue by debjitk** [mapbox/mapbox-java#817]
How can i create a static map with map clusters ?

**Comment by osana** [comment]
@debjitk What is your use case for this? Usually clustering is related to an interactive aspect of a map (zoom changes results in clustering).

**Comment by debjitk** [comment]
@osana I need to show a static map with a few clustered markers on it. On action on to the static map a interactive map opens up in the app.

**Comment by osana** [comment]
@debjitk  Please consider using com.mapbox.mapboxsdk.snapshotter.MapSnapshotter
Here are a couple of examples of how it is used: https://github.com/mapbox/mapbox-android-demo/tree/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/snapshot

You can setup clustering on the interactive map and take a snapshot of it for you static image.

Static map in [com.mapbox.api.staticmap.v1.MapboxStaticMap](https://github.com/mapbox/mapbox-java/blob/master/services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/MapboxStaticMap.java) does not support clustering.
