### ISSUE TITLE
fromJson methods shouldn't instantiate Gson every single time they are invoked

### ISSUE THREAD

**Issue by freszu** [mapbox/mapbox-java#837]
WHat kind of issue is this?
**Bug/Feature request** 

fromJson method for all model creates lots of objects, gson is thread safe and it should be instantiated once with all the adapters included, it doesn't make any sense to create it every single time toJson is called. This can have huge impact if someone is deserializing list of points and decide to use provided method.
Before doing that it's important to verify that custom type adapters are thread safe and doesn't store and use any values like for example SimpleDateFormat which are not thread safe.

**Comment by freszu** [comment]
This will be especially an issue for people that use other deserialization libraries as new autovalue models doesn't play nice with them if you can't register generated GsonTypeAdapterFactory so they will be forced to use methods provided.

**Comment by osana** [comment]
Thank you for your input. We plan to have toJson/fromJson on all model classes
