### ISSUE TITLE
Request a String instead of Locale in MapboxDirections#Builder#language

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-java#838]
- Remove unnecessary `MapboxDirections#Builder#language(@Nullable Locale language)` API

https://github.com/mapbox/mapbox-java/blob/ac79724364c96daad2ff5bcdf749130c0de4bb9f/services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java#L507-L512

and make `MapboxDirections#Builder#language(@Nullable String language)` public

https://github.com/mapbox/mapbox-java/blob/ac79724364c96daad2ff5bcdf749130c0de4bb9f/services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java#L514

Ultimately, we were only requesting a `Locale` to get the `language` from it so I think it's fine if we only offer the option of passing in a language and avoid complexity (offering a clearer API IMO).

cc @danesfeder

**Comment by osana** [comment]
Could you give me a bit more background on what is not working  and how this change helps?

We need to make sure that we  handle en-US vs en-UK correctly.

cc @danesfeder @Guardiola31337 @devotaaabel

**Comment by tobrun** [comment]
I'm not sure if I follow:

> I think it's fine if we only offer the option of passing in a language and avoid complexity 

You are requesting to replace a enum like definition with a String which could have any value? This would make it more complex as the user doesn't know which String is valid (for example: do I need to use `English` or `en`?). 

In any case, if we would like to move forward with a String parameter, we should create a new StringDef that has the same content as the [supported languages table for the directions end point](https://www.mapbox.com/api-documentation/#instructions-languages).

**Comment by Guardiola31337** [comment]
@devotaaabel's comment
> I think part of the reason is that some of java's locales return incorrect/deprecated language strings, and we are using just the pure strings everywhere else, so when we add a locale to a builder currently we are doing `Locale(string)`

**Comment by osana** [comment]
@devotaaabel  this is good feedback. Could you give me an example.

**Comment by Guardiola31337** [comment]
@osana 
> Could you give me an example.

In `NavigationRoute` from the Nav SDK, the user should pass in a `String` to set the language 👀 https://github.com/mapbox/mapbox-navigation-android/blob/85d5d463456b6692c8a4ce51e72b0b38a7f3da54/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.java#L273-L288

We could also leave it as is (`Locale`) and refactor the Nav SDK. In any case, in order to keep consistency between MAS and the Nav SDK I think we should use the same approach across both. What do you think @danesfeder @devotaaabel?

**Comment by devotaaabel** [comment]
After a discussion with @osana , @danesfeder and @Guardiola31337 we have decided to stick with `Locale` and update the nav sdk to use Locale for consistency.
