### ISSUE TITLE
Polyline Simplification not working

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#86]
Shown in #85, when the tolerance is anything above 0, it will over simplify the polyline. to just a straight line.

cc: @zugaldia

**Comment by cammace** [comment]
Diving deeper, [this if statement](https://github.com/mapbox/mapbox-java/blob/master/libjava/lib/src/main/java/com/mapbox/services/commons/utils/PolylineUtils.java#L151-L154) is rarely true, only when the tolerance is 0 does it seem to work properly.

**Comment by cammace** [comment]
Replacing the `sqTolerance` value with `sqTolerance = 0.00001 * tolerance;` solves part of the issue. Because we are dealing with latitude, longitude, the distance values are much smaller. Multiplying the tolerance by 0.00001 is setting the distance tolerance to up to 1.1m if I'm correct.

**Comment by zugaldia** [comment]
Good catch. Reduced default to 0.00001.
