### ISSUE TITLE
Remove Java 8 features from geojson module

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#868]
Request to remove java 8 from geojson module and as result remove the static method decleration of toJson on the Geometry interface, see [here](https://github.com/mapbox/mapbox-java/blob/master/services-geojson/src/main/java/com/mapbox/geojson/Geometry.java#L26). Since the method isn't public can we patch this up without breaking semver?

cc @osana @zugaldia

**Comment by zugaldia** [comment]
@osana could you run with this? Ideally this would be part of the upcoming `f` Maps SDK release.

**Comment by osana** [comment]
@zugaldia @tobrun By making GeoJson and `abstract class` instead of an `interface` we do not need to remove any methods. Please see the PR if you are Ok with that

**Comment by tobrun** [comment]
afaik the only thing to address is reverting https://github.com/mapbox/mapbox-java/blob/master/services-geojson/src/main/java/com/mapbox/geojson/Geometry.java#L26 as this is a java 8 specific feature (static methods on interfaces). Next to that we need to set the compile version back to 1.7. I'm not seeing the need for the changes made in https://github.com/mapbox/mapbox-java/pull/833, those should compile with java 7 without a change?
