### ISSUE TITLE
Can i upload my own buildings floorplan and use this sdk to draw paths and for indoor navigation  

### ISSUE THREAD

**Issue by srbhagwatsrb** [mapbox/mapbox-java#874]
Can i upload my own building's floor plan and use this sdk to draw paths and for indoor navigation. I searched over demo app, but did not find feature to upload my own floorplan and play along with it? Any help?

**Comment by langsmith** [comment]
Hi @srbhagwatsrb . Thanks for your interest in Mapbox!  

[Here's information about using Mapbox for indoor floorplans](https://www.mapbox.com/help/indoor-floorplans/)

Here two Mapbox Android demo app examples that are related to indoor mapping:

https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/extrusions/Indoor3DMapActivity.java

https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/IndoorMapActivity.java

For reference, [Mapwize](https://www.mapwize.io/) is an example of the Mapbox platform being used for drawing paths, using floorplans, etc.
