### ISSUE TITLE
RouteOptions#fromJson is not working correctly

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-java#894]
[`RouteOptions#fromJson`](https://github.com/mapbox/mapbox-java/blob/master/services-directions/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java#L293) is not working correctly. I guess because how we're serializing / deserializing some of the fields i.e. when executing the request we're sending the fields correctly (snake case) 👀 https://github.com/mapbox/mapbox-java/blob/master/services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsService.java#L54 but we're not taking that into account when converting a `RouteOptions` object back from a JSON 👀 

```java
@Test
public void incorrectFromJson() {
  String routeOptionsJson = "{\n" +
          "\t\t\"profile\": \"auto\",\n" +
          "\t\t\"user\": \"mapbox\",\n" +
          "\t\t\"baseUrl\": \"https://api.mapbox.com\",\n" +
          "\t\t\"coordinates\": [{\n" +
          "\t\t\t\"type\": \"Point\",\n" +
          "\t\t\t\"coordinates\": [-3.707788, 40.395039]\n" +
          "\t\t}, {\n" +
          "\t\t\t\"type\": \"Point\",\n" +
          "\t\t\t\"coordinates\": [-3.712179, 40.401819]\n" +
          "\t\t}],\n" +
          "\t\t\"access_token\": \"TOP SECRET!!!\",\n" +
          "\t\t\"geometries\": \"polyline6\",\n" +
          "\t\t\"overview\": \"full\",\n" +
          "\t\t\"steps\": true,\n" +
          "\t\t\"bearings\": \";\",\n" +
          "\t\t\"continue_straight\": true,\n" +
          "\t\t\"annotations\": \"congestion,distance\",\n" +
          "\t\t\"language\": \"en\",\n" +
          "\t\t\"roundabout_exits\": true,\n" +
          "\t\t\"voice_instructions\": true,\n" +
          "\t\t\"banner_instructions\": true,\n" +
          "\t\t\"voice_units\": \"imperial\"\n" +
          "\t}";
  RouteOptions incorrect = RouteOptions.fromJson(routeOptionsJson);
  assertEquals("TOP SECRET!!!", incorrect.accessToken());
}
```

I'm running into a NPE because the access token doesn't get serialized 👀 

```
java.lang.NullPointerException: Null accessToken
```

Wondering if the same wrong behavior is happening for other objects across the different services. We should double check.

cc @osana

**Comment by osana** [comment]
@Guardiola31337  Thank you for reporting this
