### ISSUE TITLE
TurfMeasurement.distance - Cannot resolve symbol 'distance'

### ISSUE THREAD

**Issue by AdinhLux** [mapbox/mapbox-java#899]
Trying to assimilate the Java SDK to create some Applications with maps, I'm encountering this issue : 

TurfMeasurement**.distance**(TOWER_BRIDGE, LONDON_EYE, TurfConstants.UNIT_FEET);
**Cannot resolve symbol 'distance'**

This tutorial [(http://www.mapbox.com.s3-website-us-east-1.amazonaws.com/android-docs/java/overview/turf/](http://www.mapbox.com.s3-website-us-east-1.amazonaws.com/android-docs/java/overview/turf/)) is out of date ?

// Create a GeoJSON point representation of the locations.
private static final Point TOWER_BRIDGE = Point.fromLatLng(51.50551, -0.07515);
private static final Point LONDON_EYE = Point.fromLatLng(51.50348, -0.12043);

// Run the points through the Turf Measurement method and receive the distance.
TurfMeasurement.distance(TOWER_BRIDGE, LONDON_EYE, TurfConstants.UNIT_FEET);

**Comment by langsmith** [comment]
hey @AdinhLux , thanks for using Mapbox. 

https://www.mapbox.com/android-docs/java/overview/turf should be up-to-date .

Have you installed the Turf dependency like so: https://www.mapbox.com/android-docs/java/overview/turf/#gradle ? If you have, you should be able to add 

```java
import com.mapbox.turf.TurfConstants;
import com.mapbox.turf.TurfMeasurement;
```
