### ISSUE TITLE
Misconverting RouteOptions.coordinates  

### ISSUE THREAD

**Issue by salihaksit7** [mapbox/mapbox-java#937]
After I update com.mapbox.mapboxsdk:mapbox-android-navigation:0.23.0 to 0.24.1, DirectionsRoute.fromJson() method does not work. 

I have a Route object which includes mapbox RouteOptions, so I use 
`response.setRouteOptions(RouteOptions.builder()...coordinates(mapboxCoordinates).build());`
Then I call 
`DirectionsRoute.fromJson(gson.toJson(response),Route.class));` 

the output of `gson.toJson(response),Route.class)` is 

`"coordinates": [
  "coordinates":{
    [
      29.00319106143756,
      41.0664822277249
    ],
  "type":"Point" },
  "coordinates":{
  [
    28.999018001370928,
    41.07349904566078
  ],
  "type":"Point" }
],`

so it throws exception  

> java.lang.IllegalStateException: Not a JSON Array: {"coordinates":[29.00287708656681,41.066443676767186],"type":"Point"}

My mapboxCoordinates

> List<Point> mapboxCoordinates;
            mapboxCoordinates = new ArrayList<>();
            mapboxCoordinates.add(origin);
            mapboxCoordinates.add(destination);

 

My gradle: 

    implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:6.7.2') {
        transitive=true
    }

    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.24.1'
    implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.24.1') {
        transitive = true
    }

**Comment by osana** [comment]
@salihaksit7 Thank you for reporting this!  We look into this.

**Comment by salihaksit7** [comment]
@osana Did you get a chance to look into this?

**Comment by mkaradil** [comment]
I'm facing with the same problem

**Comment by osana** [comment]
@salihaksit7  I checked the RouteOptions test and there is a test for using 
RouteOptions.toJson() which works fine. 
Test: RouteOptions.toJson_fromJson()
I checked manually the output of RouteOptions.toJson() and it was fine.

Are you using your own gsonBuilder?  
The error that you are getting could have happened if incorrect TypeAdapter was serializing Points. 
You mention: DirectionsRoute.fromJson(gson.toJson(response),Route.class));

What did you mean by Route.class? DirectionsRoute.fromJson(gson.toJson(response),DirectionsRoute.class))

simple test case or failing unit test would be very helpful.

**Comment by salihaksit7** [comment]
@osana This is how I get error:
I have a Route class, which set by custom osrm backend server.

    import java.util.List;
    import com.google.gson.annotations.Expose;
    import com.google.gson.annotations.SerializedName;
    import com.mapbox.api.directions.v5.models.RouteOptions;
    
    public class Route {

    @SerializedName("geometry")
    @Expose
    private String geometry;
    @SerializedName("legs")
    @Expose
    private List<Leg> legs = null;
    @SerializedName("distance")
    @Expose
    private Double distance;
    @SerializedName("duration")
    @Expose
    private Double duration;
    @SerializedName("weight_name")
    @Expose
    private String weightName;
    @SerializedName("weight")
    @Expose
    private Double weight;

    @Nullable
    @SerializedName("voiceLocale")
    public  String voiceLocale = "tr-TR";

    @Nullable
    public RouteOptions routeOptions = null;

    @Nullable
    public String getVoiceLanguage() {
        return voiceLocale;
    }
    }

 Then I add RouteOptions manuelly,which works.

    myRouteObject.setRouteOptions(RouteOptions.fromJson("{\n" +
                            "  \"access_token\": \"YOUR_ACCESS_TOKEN\",\n" +
                            "  \"annotations\": \"speed,distance\",\n" +
                            "  \"banner_instructions\": true,\n" +
                            "  \"baseUrl\": \"https://api.mapbox.com\",\n" +
                            "  \"bearings\": \";\",\n" +
                            "  \"continue_straight\": true,\n" +
                            "  \"coordinates\": [[-3.707788,40.395039],[-3.712179,40.401819]]," +
                            "  \"geometries\": \"polyline6\",\n" +
                            "  \"language\": \"tr\",\n" +
                            "  \"overview\": \"full\",\n" +
                            "  \"profile\": \"driving-traffic\",\n" +
                            "  \"uuid\": " + UUID.randomUUID().toString() + "\",\n" +
                            "  \"roundabout_exits\": true,\n" +
                            "  \"user\": \"example_user\",\n" +
                            "  \"voice_instructions\": true,\n" +
                            "  \"voice_units\": \"metric\"\n" +
                            "}"));

I checked the data by routeOptions.toJson() :

    {"baseUrl":"https://api.mapbox.com","user":"example_user","profile":"driving-traffic","coordinates":[[-3.707788,40.395039],[-3.712179,40.401819]],"language":"tr","bearings":";","continue_straight":true,"roundabout_exits":true,"geometries":"polyline6","overview":"full","annotations":"speed,distance","voice_instructions":true,"banner_instructions":true,"voice_units":"metric","access_token":"YOUR_ACCESS_TOKEN","uuid":"b567ca28-2a1b-4681-ab7d-3393a24fa480\""}
![image](https://user-images.githubusercontent.com/17300221/52325398-e8bdf400-29f5-11e9-95c7-a45519ef1dfc.png)

You can realize that on picture, there is type "Point". On Json It does not exists.

Then I am trying to  convert my Route object to DirectionsRoute object, since for example NavigationMapRoute wants this type.  

    DirectionsRoute.fromJson(gson.toJson(myRouteObject, Route.class));

And this throw exceptions:

> java.lang.IllegalStateException: Not a JSON Array: {"coordinates":[-3.707788,40.395039],"type":"Point"}


But this code works on 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.23.0' . But I have to use at least 0.24.1 .

**Comment by osana** [comment]
The route of the problem is that Point could be serialized differently depending on the context.  If Point is a Geometry (part of Feature) it should be serialized with object "type" and "bbox" but if it is part of some coordinates list it should be serialized as and array. 

you are using your own gson to do toJson. Try adding : 
 gson.registerTypeAdapter(Point.class, new PointSerializer());

This will serialize Point as array of coordinates.

**Comment by salihaksit7** [comment]
Thanks @osana ,

                    gson.registerTypeAdapterFactory(DirectionsAdapterFactory.create());
                    gson.registerTypeAdapter(Point.class, new PointSerializer());

This solved my problem.
