### ISSUE TITLE
Decouple the snapshot creation between libandroid and libjava 

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-java#95]
When something changes in libjava, we are breaking libandroid because we are using the SNAPSHOT that's only updated nightly. 

cc: @zugaldia

**Comment by zugaldia** [comment]
I'm thinking that during development we could have something like this in `settings.gradle`:

```
include ':libjava'
project(':libjava').projectDir = new File(settingsDir, '../libjava')
```

and then in the `build.gradle` file something like:

```
dependencies {
    compile project(':libjava')
}
```

That way we'd be developing and building from master. Only at release time, we'd force the dependency to match a published version of the library.

**Comment by cammace** [comment]
Just tried your suggestion out briefly @zugaldia and it looks promising. One thing to note is that I had to change the file path to `'../libjava/lib'`.

**Comment by zugaldia** [comment]
@cammace Glad to hear. PR'ed in https://github.com/mapbox/mapbox-java/pull/113.

**Comment by zugaldia** [comment]
> It also now includes the libjava module in the libandroid project?

Yeah, it does for me too. Even more convenient :-)
