### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/mapboxsdk/location/LocationServices;

### ISSUE THREAD

**Issue by ceineke** [mapbox/mapbox-java#97]
I'm trying to develop an app using the android-maven-plugin, but unfortunately as soon as I add the mapbox sdk as a dependency and create the MapView element in my view, my relatively simple app fails to start with the following stacktrace. I attached the [effective POM](https://github.com/mapbox/mapbox-java/files/344342/effective-pom.txt) for good measure. I hope someone could help me out with this.

`07-01 20:46:23.313  2620  2620 E AndroidRuntime: Process: com.continuesoftware.tchotchke.android, PID: 2620
07-01 20:46:23.313  2620  2620 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.continuesoftware.tchotchke.android/com.continuesoftware.tchotchke.android.MainActivity}: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class com.mapbox.mapboxsdk.maps.MapView
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class com.mapbox.mapboxsdk.maps.MapView
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.app.Activity.setContentView(Activity.java:2166)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at com.continuesoftware.tchotchke.android.MainActivity.onCreate(MainActivity.java:18)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6237)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	... 9 more
07-01 20:46:23.313  2620  2620 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class com.mapbox.mapboxsdk.maps.MapView
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	... 17 more
07-01 20:46:23.313  2620  2620 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Native Method)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	... 22 more
07-01 20:46:23.313  2620  2620 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #37: Binary XML file line #37: Error inflating class com.mapbox.mapboxsdk.maps.widgets.MyLocationView
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:192)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:170)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	... 24 more
07-01 20:46:23.313  2620  2620 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #37: Error inflating class com.mapbox.mapboxsdk.maps.widgets.MyLocationView
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	... 28 more
07-01 20:46:23.313  2620  2620 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Native Method)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	... 32 more
07-01 20:46:23.313  2620  2620 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/mapboxsdk/location/LocationServices;
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.toggleGps(MyLocationView.java:362)
07-01 20:46:23.313  2620  2620 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.setEnabled
07-01 20:46:23.349  1528  1827 W ActivityManager:   Force finishing activity com.continuesoftware.tchotchke.android/.MainActivity
07-01 20:46:23.354  1184  1184 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
07-01 20:46:23.354  1184  1184 E libEGL  : called unimplemented OpenGL ES API
07-01 20:46:23.354  1184  1184 E SurfaceFlinger: glCheckFramebufferStatusOES error -1305234954
07-01 20:46:23.354  1184  1184 E SurfaceFlinger: got GL_FRAMEBUFFER_COMPLETE_OES error while taking screenshot
07-01 20:46:23.873  1528  1542 W ActivityManager: Activity pause timeout for ActivityRecord{a2785b4 u0 com.continuesoftware.tchotchke.android/.MainActivity t32 f}
07-01 20:46:30.880  1528  1881 I ActivityManager: Killing 2117:com.android.providers.calendar/u0a1 (adj 15): empty for 1806s
07-01 20:46:34.036  1528  1542 W ActivityManager: Activity destroy timeout for ActivityRecord{a2785b4 u0 com.continuesoftware.tchotchke.android/.MainActivity t32 f}`

**Comment by cammace** [comment]
Hey sorry to hear you are experiencing issues with the SDK, this looks like an issue related to the Mapbox Android SDK and not Mapbox Android Service (this repo). For future issues, please reach out to [Mapbox contact](https://www.mapbox.com/contact/).

From the logcat, your issue looks like it might be coming from either and issue with your XML or you are missing the telemetry service in your `AndroidManifest.xml`. Check your activity xml first:
> Binary XML file line #10: Binary XML file line #10: Error inflating class com.mapbox.mapboxsdk.maps.MapView 

and make sure the telemetry service is included:
`<service android:name="com.mapbox.mapboxsdk.telemetry.TelemetryService"/>`

Lastly, check your permissions and make sure you've included all the [requirements found here](https://www.mapbox.com/android-sdk/). Closing this ticket for now, let me know if you still are having issues and feel free to include some of your code so I can review it.
