### ISSUE TITLE
deprecated info window

### ISSUE THREAD

**Issue by ChekhWasTaken** [mapbox/mapbox-java#971]
Hello,

I have some troubles implementing an info window for markers. 

Markers and info window adapter are deprecated and use of annotations are encouraged. Using  [this](https://docs.mapbox.com/android/maps/examples/symbol-layer-info-window/) tutorial I have managed to add the info window, which opens on marker click. This approach renders the view on a canvas, then adds the bitmap as an image to layer, which then displays or hides the image based on feature property. There is a problem however: in my case info window has buttons several buttons. Now if the window had only one button, I could handle the click on the window itself, but as there are multiple buttons I don't know how to handle each button click.

**Comment by langsmith** [comment]
Hi @ChekhWasTaken . Thanks for using Mapbox.

The conversation about this in https://github.com/mapbox/mapbox-plugins-android/issues/649 is related to your issue above. We know that this is something that would be great to support, but it's not a top priority right now.
