### ISSUE TITLE
add @Keep annotations

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#980]
One of the typical issues we hit downstream, is integrating a mapbox-java dependency in an Android project using proguard. Since we generate jar files as binaries from this repository, we can't include a proguard mapping file. As a result we need to maintain the proguard mapping  downstream while ideally this is done in this repository instead.

An alternative way of providing proguard integration is using the `@Keep` annotation. This is used by proguard at compile time to determine to not obfuscate a method/class/.. etc. 

This issue tracks looking into adding this `@Keep` annotation. 

cc @mapbox/maps-android @mapbox/navigation-android

**Comment by osana** [comment]
Here are the links to [mabox-demo-app proguard rules ](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/proguard-rules.pro)
and [mapbox-gl-native proguard rules](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/proguard-rules.pro)

also talking to @Guardiola31337, @devotaaabel on what would make sense to ```@Keep``` from navigation side of things. 

From Android documentation : [```@Keep``` is typically used on methods and classes that are accessed only via reflection so a compiler may think that the code is unused.](https://developer.android.com/reference/android/support/annotation/Keep).

I think that mapbox-java classes are rarely used through reflection and thus compiler can detect that the classes are used and there is no need to ```keep``` those.  

@tobrun Did you have a specific class/classes in mind?

**Comment by zugaldia** [comment]
At least Gson uses reflection and requires some additional ProGuard rules ([example](https://github.com/google/gson/tree/master/examples/android-proguard-example)).

**Comment by osana** [comment]
I think this ticket talks about potentially putting `@Keep` next to the classes that we know for sure have to be kept and have the potential of being referenced through reflection. 

I agree that Gson uses reflection but I think all the TypeAdapters and Deserializers/ Serializers that are present in geojson module will be referenced and thus will be marked as a class that cannot be removed. 

There are TypeAdapters that come with Gson that we might be using through reflection but we cannot add `@Keep` for those, neither could we add a rule in the proguard rules file (as @tobrun pointed out).
