### ISSUE TITLE
Pure java project

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#983]
This project initially contained multiple Android related examples and code. We moved away from that to create java only libraries, tests and examples. Recently noticed that we are still using Android tooling under the hood (eg. android gradle tooling). This should be removed and will allow us to move to a higher Gradle version (this for example to fix issues as https://github.com/google/auto/issues/706#issuecomment-469561981).

cc @osana @zugaldia

**Comment by osana** [comment]
According to migration gradle [migration guide 4.0 -> 5.0](https://docs.gradle.org/current/userguide/upgrading_version_4.html#changes_5.0)  : 
Gradle 5 requires Java 8 to run.
This project is still Java 7 based

**Comment by zugaldia** [comment]
Looks like the Maps SDK is already [using Java 8](https://github.com/mapbox/mapbox-gl-native/search?q=sourceCompatibility&unscoped_q=sourceCompatibility) (correct me if I'm wrong @tobrun). If so, any reasons not to take the opportunity to move this project to Java 8 as well?

**Comment by osana** [comment]
@zugaldia what you cite refers to MaboxGLAndroidSDKLint and MapboxGLAndroidTestApp being on Java 8.
AFAIK J[ava 8 was removed](https://github.com/mapbox/mapbox-gl-native/pull/13193) from MapboxGLAndoridSDK

**Comment by tobrun** [comment]
For some clients we need to keep java 7 around for the maps sdk. In any case let's move forward on extracting android toolchain and just keep versions currently under 5. 

For the autovalue issue of packaging those additional files, we should look into just removing them from the jar with some gradle rule.

**Comment by osana** [comment]
@tobrun As far as tooling removal is concerned: https://github.com/mapbox/mapbox-java/pull/984
I will remove the additional files in a different PR then
