### ISSUE TITLE
Exclude AutoValue java files from jar

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-java#989]
Ticketing this out as we didn't have a public ticket tracking this: currently AutoValue enabled dependencies from this repo will include generate java files as part of the jar generated. 

![image](https://user-images.githubusercontent.com/2151639/55730457-88105f00-5a18-11e9-8f88-2f61ea759103.png)

Capturing from upstream that this is unneeded and these files can safely be removed:
 - https://github.com/google/auto/issues/706

Considering we aren't able to bump to gradle 5.0 due to java 8 requirement, we should find a way to exclude this files. Either through a [gradle configuration](https://stackoverflow.com/questions/19575474/gradle-how-to-exclude-a-particular-package-from-a-jar) or [pom.xml configuration](https://stackoverflow.com/questions/26083326/how-do-i-exclude-java-files-from-a-jar-in-maven-jar-plugin) or ..

cc @osana

**Comment by osana** [comment]
Got some movement but still have to figure out when and how to invoke it. 

Adding the following to build.gradle (in directions for example)
```
tasks.withType(Jar) {
  println '>>>>>>>>>> DIRECTIONS JAR >>>>>>>>>'
  source.each({
    if (it.toString().endsWith('.java')) {
      println '>>>>>>' + it
      exclude(it.toString())
    }})
    println 'excludes=' +excludes
}
```
Results java files being listed and added to the excludes list BUT  for some reason that task is being invoked during `./gradlew clean` and not druing `.gradlew test`
